server:
  port: 8086
  servlet:
    context-path: /
spring:
  cloud:
    refresh:
      refreshable: none
  jmx:
    enabled: false
  application:
    #服务名称(需要与config中的{application}位置正好拼成相应的git地址)
    name: eparkingThirdAPI
  security:
    user:
      name: admin
      password: 123456
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #测试服务器
    url: jdbc:mysql://rm-wz9d21p5za0w2ja2x313.mysql.rds.aliyuncs.com:3306/eparking?autoReconnect=true&initialTimeout=3&useUnicode=true&characterEncoding=utf-8
    username: eparking
    password: 20peraikgn14@
    http:
      multipart-maxFileSize: 10MB
      multipart-maxRequestSize: 10MB

eureka:
  instance:
    #hostname: ${spring.cloud.client.ip-address}
    hostname: yun2.eparking.top #外网地址
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10    #配置续约更新时间
    lease-expiration-duration-in-seconds: 10   #配置续约到期时间
    #优先使用IP地址注册服务
    #prefer-ip-address: true
  client:
    healthcheck:
      enabled: true #开启健康检查
    service-url:
      #注册中心
      defaultZone:  http://${spring.security.user.name}:${spring.security.user.password}@yun2.eparking.top:8086/eureka/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@yun2.eparking.top:8087/eureka/eureka/
  feign:
    httpclient:
      enabled: true
    hystrix:
      enabled: true
  hystrix:
    shareSecurityContext: true
    command:
      default:
        circuitBreaker:
          sleepWindowInMilliseconds: 100000
          forceClosed: true
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 600000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql
logging:
  level:
    com:
      api:
        dao: debug