package com.api.dao;

import com.api.dao.sqlProvider.CarEntrySqlProvider;
import com.api.entity.CarEntry;
import com.api.entity.CarEntryCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface CarEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    @SelectProvider(type=CarEntrySqlProvider.class, method="countByExample")
    long countByExample(CarEntryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    @DeleteProvider(type=CarEntrySqlProvider.class, method="deleteByExample")
    int deleteByExample(CarEntryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    @Delete({
        "delete from car_entry",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    @Insert({
        "insert into car_entry (id, member_id, ",
        "park_id, company_id, ",
        "car_plate, driver_card_img, ",
        "car_card_img, entry_time, ",
        "check_flog, dismiss, ",
        "level, check_userid, ",
        "checktime)",
        "values (#{id,jdbcType=INTEGER}, #{memberId,jdbcType=VARCHAR}, ",
        "#{parkId,jdbcType=INTEGER}, #{companyId,jdbcType=INTEGER}, ",
        "#{carPlate,jdbcType=VARCHAR}, #{driverCardImg,jdbcType=VARCHAR}, ",
        "#{carCardImg,jdbcType=VARCHAR}, #{entryTime,jdbcType=TIMESTAMP}, ",
        "#{checkFlog,jdbcType=INTEGER}, #{dismiss,jdbcType=VARCHAR}, ",
        "#{level,jdbcType=INTEGER}, #{checkUserid,jdbcType=INTEGER}, ",
        "#{checktime,jdbcType=TIMESTAMP})"
    })
    int insert(CarEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    @InsertProvider(type=CarEntrySqlProvider.class, method="insertSelective")
    int insertSelective(CarEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    @SelectProvider(type=CarEntrySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_card_img", property="driverCardImg", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_card_img", property="carCardImg", jdbcType=JdbcType.VARCHAR),
        @Result(column="entry_time", property="entryTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="check_flog", property="checkFlog", jdbcType=JdbcType.INTEGER),
        @Result(column="dismiss", property="dismiss", jdbcType=JdbcType.VARCHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.INTEGER),
        @Result(column="check_userid", property="checkUserid", jdbcType=JdbcType.INTEGER),
        @Result(column="checktime", property="checktime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<CarEntry> selectByExample(CarEntryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, member_id, park_id, company_id, car_plate, driver_card_img, car_card_img, ",
        "entry_time, check_flog, dismiss, level, check_userid, checktime",
        "from car_entry",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_card_img", property="driverCardImg", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_card_img", property="carCardImg", jdbcType=JdbcType.VARCHAR),
        @Result(column="entry_time", property="entryTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="check_flog", property="checkFlog", jdbcType=JdbcType.INTEGER),
        @Result(column="dismiss", property="dismiss", jdbcType=JdbcType.VARCHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.INTEGER),
        @Result(column="check_userid", property="checkUserid", jdbcType=JdbcType.INTEGER),
        @Result(column="checktime", property="checktime", jdbcType=JdbcType.TIMESTAMP)
    })
    CarEntry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CarEntrySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CarEntry record, @Param("example") CarEntryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CarEntrySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CarEntry record, @Param("example") CarEntryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CarEntrySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CarEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    @Update({
        "update car_entry",
        "set member_id = #{memberId,jdbcType=VARCHAR},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "company_id = #{companyId,jdbcType=INTEGER},",
          "car_plate = #{carPlate,jdbcType=VARCHAR},",
          "driver_card_img = #{driverCardImg,jdbcType=VARCHAR},",
          "car_card_img = #{carCardImg,jdbcType=VARCHAR},",
          "entry_time = #{entryTime,jdbcType=TIMESTAMP},",
          "check_flog = #{checkFlog,jdbcType=INTEGER},",
          "dismiss = #{dismiss,jdbcType=VARCHAR},",
          "level = #{level,jdbcType=INTEGER},",
          "check_userid = #{checkUserid,jdbcType=INTEGER},",
          "checktime = #{checktime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CarEntry record);
}