package com.api.dao;

import com.api.dao.sqlProvider.CityInformationSqlProvider;
import com.api.entity.CityInformation;
import com.api.entity.CityInformationCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface CityInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_information
     *
     * @mbg.generated
     */
    @SelectProvider(type= CityInformationSqlProvider.class, method="countByExample")
    long countByExample(CityInformationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_information
     *
     * @mbg.generated
     */
    @DeleteProvider(type= CityInformationSqlProvider.class, method="deleteByExample")
    int deleteByExample(CityInformationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_information
     *
     * @mbg.generated
     */
    @Delete({
        "delete from city_information",
        "where City_ID = #{cityId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_information
     *
     * @mbg.generated
     */
    @Insert({
        "insert into city_information (City_ID, City_Name, ",
        "CreateTime, Province_ID)",
        "values (#{cityId,jdbcType=INTEGER}, #{cityName,jdbcType=VARCHAR}, ",
        "#{createtime,jdbcType=TIMESTAMP}, #{provinceId,jdbcType=INTEGER})"
    })
    int insert(CityInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_information
     *
     * @mbg.generated
     */
    @InsertProvider(type= CityInformationSqlProvider.class, method="insertSelective")
    int insertSelective(CityInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_information
     *
     * @mbg.generated
     */
    @SelectProvider(type= CityInformationSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="City_ID", property="cityId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="City_Name", property="cityName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CreateTime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Province_ID", property="provinceId", jdbcType=JdbcType.INTEGER)
    })
    List<CityInformation> selectByExample(CityInformationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_information
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "City_ID, City_Name, CreateTime, Province_ID",
        "from city_information",
        "where City_ID = #{cityId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="City_ID", property="cityId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="City_Name", property="cityName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CreateTime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="Province_ID", property="provinceId", jdbcType=JdbcType.INTEGER)
    })
    CityInformation selectByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_information
     *
     * @mbg.generated
     */
    @UpdateProvider(type= CityInformationSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CityInformation record, @Param("example") CityInformationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_information
     *
     * @mbg.generated
     */
    @UpdateProvider(type= CityInformationSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CityInformation record, @Param("example") CityInformationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_information
     *
     * @mbg.generated
     */
    @UpdateProvider(type= CityInformationSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CityInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_information
     *
     * @mbg.generated
     */
    @Update({
        "update city_information",
        "set City_Name = #{cityName,jdbcType=VARCHAR},",
          "CreateTime = #{createtime,jdbcType=TIMESTAMP},",
          "Province_ID = #{provinceId,jdbcType=INTEGER}",
        "where City_ID = #{cityId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CityInformation record);
}