package com.api.dao;

import com.api.dao.sqlProvider.PwpMemberDetailTradeSqlProvider;
import com.api.entity.PwpMemberDetailTrade;
import com.api.entity.PwpMemberDetailTradeCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface PwpMemberDetailTradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail_trade
     *
     * @mbg.generated
     */
    @SelectProvider(type= PwpMemberDetailTradeSqlProvider.class, method="countByExample")
    long countByExample(PwpMemberDetailTradeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail_trade
     *
     * @mbg.generated
     */
    @DeleteProvider(type= PwpMemberDetailTradeSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpMemberDetailTradeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail_trade
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_member_detail_trade",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail_trade
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_member_detail_trade (id, trade_no, ",
        "member_detail_id, car_num, ",
        "p_card_code, p_card_id, ",
        "p_card_pwd, trade_amount, ",
        "balance, park_id, ",
        "trade_type, trade_result, ",
        "create_time, update_time)",
        "values (#{id,jdbcType=INTEGER}, #{tradeNo,jdbcType=VARCHAR}, ",
        "#{memberDetailId,jdbcType=INTEGER}, #{carNum,jdbcType=VARCHAR}, ",
        "#{pCardCode,jdbcType=VARCHAR}, #{pCardId,jdbcType=VARCHAR}, ",
        "#{pCardPwd,jdbcType=VARCHAR}, #{tradeAmount,jdbcType=DECIMAL}, ",
        "#{balance,jdbcType=DECIMAL}, #{parkId,jdbcType=INTEGER}, ",
        "#{tradeType,jdbcType=SMALLINT}, #{tradeResult,jdbcType=TINYINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(PwpMemberDetailTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail_trade
     *
     * @mbg.generated
     */
    @InsertProvider(type= PwpMemberDetailTradeSqlProvider.class, method="insertSelective")
    int insertSelective(PwpMemberDetailTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail_trade
     *
     * @mbg.generated
     */
    @SelectProvider(type= PwpMemberDetailTradeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="trade_no", property="tradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_detail_id", property="memberDetailId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_num", property="carNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_code", property="pCardCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_id", property="pCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_pwd", property="pCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="trade_amount", property="tradeAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="balance", property="balance", jdbcType=JdbcType.DECIMAL),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="trade_type", property="tradeType", jdbcType=JdbcType.SMALLINT),
        @Result(column="trade_result", property="tradeResult", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<PwpMemberDetailTrade> selectByExample(PwpMemberDetailTradeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail_trade
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, trade_no, member_detail_id, car_num, p_card_code, p_card_id, p_card_pwd, ",
        "trade_amount, balance, park_id, trade_type, trade_result, create_time, update_time",
        "from pwp_member_detail_trade",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="trade_no", property="tradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_detail_id", property="memberDetailId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_num", property="carNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_code", property="pCardCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_id", property="pCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_pwd", property="pCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="trade_amount", property="tradeAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="balance", property="balance", jdbcType=JdbcType.DECIMAL),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="trade_type", property="tradeType", jdbcType=JdbcType.SMALLINT),
        @Result(column="trade_result", property="tradeResult", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    PwpMemberDetailTrade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail_trade
     *
     * @mbg.generated
     */
    @UpdateProvider(type= PwpMemberDetailTradeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpMemberDetailTrade record, @Param("example") PwpMemberDetailTradeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail_trade
     *
     * @mbg.generated
     */
    @UpdateProvider(type= PwpMemberDetailTradeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpMemberDetailTrade record, @Param("example") PwpMemberDetailTradeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail_trade
     *
     * @mbg.generated
     */
    @UpdateProvider(type= PwpMemberDetailTradeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpMemberDetailTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail_trade
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_member_detail_trade",
        "set trade_no = #{tradeNo,jdbcType=VARCHAR},",
          "member_detail_id = #{memberDetailId,jdbcType=INTEGER},",
          "car_num = #{carNum,jdbcType=VARCHAR},",
          "p_card_code = #{pCardCode,jdbcType=VARCHAR},",
          "p_card_id = #{pCardId,jdbcType=VARCHAR},",
          "p_card_pwd = #{pCardPwd,jdbcType=VARCHAR},",
          "trade_amount = #{tradeAmount,jdbcType=DECIMAL},",
          "balance = #{balance,jdbcType=DECIMAL},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "trade_type = #{tradeType,jdbcType=SMALLINT},",
          "trade_result = #{tradeResult,jdbcType=TINYINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpMemberDetailTrade record);
}