package com.api.dao;

import com.api.dao.sqlProvider.PwpMerchantRechargeCashSqlProvider;
import com.api.entity.PwpMerchantRechargeCash;
import com.api.entity.PwpMerchantRechargeCashCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface PwpMerchantRechargeCashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @SelectProvider(type= PwpMerchantRechargeCashSqlProvider.class, method="countByExample")
    long countByExample(PwpMerchantRechargeCashCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @DeleteProvider(type= PwpMerchantRechargeCashSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpMerchantRechargeCashCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_merchant_recharge_cash",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_merchant_recharge_cash (id, park_id, ",
        "merchant_id, recharge_no, ",
        "recharge_amount, coupon_amount, ",
        "coupon_balance, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=INTEGER}, #{parkId,jdbcType=INTEGER}, ",
        "#{merchantId,jdbcType=INTEGER}, #{rechargeNo,jdbcType=VARCHAR}, ",
        "#{rechargeAmount,jdbcType=DECIMAL}, #{couponAmount,jdbcType=DECIMAL}, ",
        "#{couponBalance,jdbcType=DECIMAL}, #{createTime,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=VARCHAR})"
    })
    int insert(PwpMerchantRechargeCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @InsertProvider(type= PwpMerchantRechargeCashSqlProvider.class, method="insertSelective")
    int insertSelective(PwpMerchantRechargeCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @SelectProvider(type= PwpMerchantRechargeCashSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="merchant_id", property="merchantId", jdbcType=JdbcType.INTEGER),
        @Result(column="recharge_no", property="rechargeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="recharge_amount", property="rechargeAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="coupon_amount", property="couponAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="coupon_balance", property="couponBalance", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR)
    })
    List<PwpMerchantRechargeCash> selectByExample(PwpMerchantRechargeCashCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, park_id, merchant_id, recharge_no, recharge_amount, coupon_amount, coupon_balance, ",
        "create_time, update_time",
        "from pwp_merchant_recharge_cash",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="merchant_id", property="merchantId", jdbcType=JdbcType.INTEGER),
        @Result(column="recharge_no", property="rechargeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="recharge_amount", property="rechargeAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="coupon_amount", property="couponAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="coupon_balance", property="couponBalance", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR)
    })
    PwpMerchantRechargeCash selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @UpdateProvider(type= PwpMerchantRechargeCashSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpMerchantRechargeCash record, @Param("example") PwpMerchantRechargeCashCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @UpdateProvider(type= PwpMerchantRechargeCashSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpMerchantRechargeCash record, @Param("example") PwpMerchantRechargeCashCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @UpdateProvider(type= PwpMerchantRechargeCashSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpMerchantRechargeCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_merchant_recharge_cash
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_merchant_recharge_cash",
        "set park_id = #{parkId,jdbcType=INTEGER},",
          "merchant_id = #{merchantId,jdbcType=INTEGER},",
          "recharge_no = #{rechargeNo,jdbcType=VARCHAR},",
          "recharge_amount = #{rechargeAmount,jdbcType=DECIMAL},",
          "coupon_amount = #{couponAmount,jdbcType=DECIMAL},",
          "coupon_balance = #{couponBalance,jdbcType=DECIMAL},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpMerchantRechargeCash record);
}