package com.api.dao;

import com.api.dao.sqlProvider.PwpMemberPCardSqlProvider;
import com.api.entity.PwpMemberPCard;
import com.api.entity.PwpMemberPCardCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface PwpMemberPCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMemberPCardSqlProvider.class, method="countByExample")
    long countByExample(PwpMemberPCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PwpMemberPCardSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpMemberPCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_member_p_card",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_member_p_card (id, member_id, ",
        "add_sequence, nick_name, ",
        "account, password, ",
        "realname, sex, phone, ",
        "email, credentials_type, ",
        "credentials_code, area_id, ",
        "address, p_card_code, ",
        "p_card_id, p_card_pwd, ",
        "member_p_card_status, balance, ",
        "billing_account_id, create_time, ",
        "update_time, salt, ",
        "weixin_account)",
        "values (#{id,jdbcType=INTEGER}, #{memberId,jdbcType=INTEGER}, ",
        "#{addSequence,jdbcType=INTEGER}, #{nickName,jdbcType=VARCHAR}, ",
        "#{account,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{realname,jdbcType=VARCHAR}, #{sex,jdbcType=TINYINT}, #{phone,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{credentialsType,jdbcType=TINYINT}, ",
        "#{credentialsCode,jdbcType=VARCHAR}, #{areaId,jdbcType=INTEGER}, ",
        "#{address,jdbcType=VARCHAR}, #{pCardCode,jdbcType=VARCHAR}, ",
        "#{pCardId,jdbcType=VARCHAR}, #{pCardPwd,jdbcType=VARCHAR}, ",
        "#{memberPCardStatus,jdbcType=TINYINT}, #{balance,jdbcType=DECIMAL}, ",
        "#{billingAccountId,jdbcType=INTEGER}, #{createTime,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=VARCHAR}, #{salt,jdbcType=VARCHAR}, ",
        "#{weixinAccount,jdbcType=VARCHAR})"
    })
    int insert(PwpMemberPCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @InsertProvider(type=PwpMemberPCardSqlProvider.class, method="insertSelective")
    int insertSelective(PwpMemberPCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMemberPCardSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="add_sequence", property="addSequence", jdbcType=JdbcType.INTEGER),
        @Result(column="nick_name", property="nickName", jdbcType=JdbcType.VARCHAR),
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="realname", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.TINYINT),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="credentials_type", property="credentialsType", jdbcType=JdbcType.TINYINT),
        @Result(column="credentials_code", property="credentialsCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_code", property="pCardCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_id", property="pCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_pwd", property="pCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_p_card_status", property="memberPCardStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="balance", property="balance", jdbcType=JdbcType.DECIMAL),
        @Result(column="billing_account_id", property="billingAccountId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="salt", property="salt", jdbcType=JdbcType.VARCHAR),
        @Result(column="weixin_account", property="weixinAccount", jdbcType=JdbcType.VARCHAR)
    })
    List<PwpMemberPCard> selectByExample(PwpMemberPCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, member_id, add_sequence, nick_name, account, password, realname, sex, phone, ",
        "email, credentials_type, credentials_code, area_id, address, p_card_code, p_card_id, ",
        "p_card_pwd, member_p_card_status, balance, billing_account_id, create_time, ",
        "update_time, salt, weixin_account",
        "from pwp_member_p_card",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="add_sequence", property="addSequence", jdbcType=JdbcType.INTEGER),
        @Result(column="nick_name", property="nickName", jdbcType=JdbcType.VARCHAR),
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="realname", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.TINYINT),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="credentials_type", property="credentialsType", jdbcType=JdbcType.TINYINT),
        @Result(column="credentials_code", property="credentialsCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_code", property="pCardCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_id", property="pCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_pwd", property="pCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_p_card_status", property="memberPCardStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="balance", property="balance", jdbcType=JdbcType.DECIMAL),
        @Result(column="billing_account_id", property="billingAccountId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="salt", property="salt", jdbcType=JdbcType.VARCHAR),
        @Result(column="weixin_account", property="weixinAccount", jdbcType=JdbcType.VARCHAR)
    })
    PwpMemberPCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMemberPCardSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpMemberPCard record, @Param("example") PwpMemberPCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMemberPCardSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpMemberPCard record, @Param("example") PwpMemberPCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMemberPCardSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpMemberPCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_p_card
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_member_p_card",
        "set member_id = #{memberId,jdbcType=INTEGER},",
          "add_sequence = #{addSequence,jdbcType=INTEGER},",
          "nick_name = #{nickName,jdbcType=VARCHAR},",
          "account = #{account,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "realname = #{realname,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=TINYINT},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "credentials_type = #{credentialsType,jdbcType=TINYINT},",
          "credentials_code = #{credentialsCode,jdbcType=VARCHAR},",
          "area_id = #{areaId,jdbcType=INTEGER},",
          "address = #{address,jdbcType=VARCHAR},",
          "p_card_code = #{pCardCode,jdbcType=VARCHAR},",
          "p_card_id = #{pCardId,jdbcType=VARCHAR},",
          "p_card_pwd = #{pCardPwd,jdbcType=VARCHAR},",
          "member_p_card_status = #{memberPCardStatus,jdbcType=TINYINT},",
          "balance = #{balance,jdbcType=DECIMAL},",
          "billing_account_id = #{billingAccountId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR},",
          "salt = #{salt,jdbcType=VARCHAR},",
          "weixin_account = #{weixinAccount,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpMemberPCard record);
}