package com.api.dao;

import com.api.dao.sqlProvider.PwpMemberSqlProvider;
import com.api.entity.PwpMember;
import com.api.entity.PwpMemberCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface PwpMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @SelectProvider(type= PwpMemberSqlProvider.class, method="countByExample")
    long countByExample(PwpMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @DeleteProvider(type= PwpMemberSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_member",
        "where member_id = #{memberId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_member (member_id, phone, ",
        "password, pwd_safe_level, ",
        "realname, email, ",
        "credentials_type, credentials_code, ",
        "area_id, address, ",
        "first_p_card_id, first_p_card_pwd, ",
        "member_status, create_time, ",
        "update_time, salt, ",
        "paypwd, cert_pic_front, ",
        "cert_pic_back, picture, ",
        "safe_code)",
        "values (#{memberId,jdbcType=INTEGER}, #{phone,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{pwdSafeLevel,jdbcType=TINYINT}, ",
        "#{realname,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{credentialsType,jdbcType=TINYINT}, #{credentialsCode,jdbcType=VARCHAR}, ",
        "#{areaId,jdbcType=INTEGER}, #{address,jdbcType=VARCHAR}, ",
        "#{firstPCardId,jdbcType=VARCHAR}, #{firstPCardPwd,jdbcType=VARCHAR}, ",
        "#{memberStatus,jdbcType=TINYINT}, #{createTime,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=VARCHAR}, #{salt,jdbcType=VARCHAR}, ",
        "#{paypwd,jdbcType=VARCHAR}, #{certPicFront,jdbcType=VARCHAR}, ",
        "#{certPicBack,jdbcType=VARCHAR}, #{picture,jdbcType=VARCHAR}, ",
        "#{safeCode,jdbcType=VARCHAR})"
    })
    int insert(PwpMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @InsertProvider(type= PwpMemberSqlProvider.class, method="insertSelective")
    int insertSelective(PwpMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @SelectProvider(type= PwpMemberSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="pwd_safe_level", property="pwdSafeLevel", jdbcType=JdbcType.TINYINT),
        @Result(column="realname", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="credentials_type", property="credentialsType", jdbcType=JdbcType.TINYINT),
        @Result(column="credentials_code", property="credentialsCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="first_p_card_id", property="firstPCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="first_p_card_pwd", property="firstPCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_status", property="memberStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="salt", property="salt", jdbcType=JdbcType.VARCHAR),
        @Result(column="paypwd", property="paypwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="cert_pic_front", property="certPicFront", jdbcType=JdbcType.VARCHAR),
        @Result(column="cert_pic_back", property="certPicBack", jdbcType=JdbcType.VARCHAR),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR),
        @Result(column="safe_code", property="safeCode", jdbcType=JdbcType.VARCHAR)
    })
    List<PwpMember> selectByExample(PwpMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "member_id, phone, password, pwd_safe_level, realname, email, credentials_type, ",
        "credentials_code, area_id, address, first_p_card_id, first_p_card_pwd, member_status, ",
        "create_time, update_time, salt, paypwd, cert_pic_front, cert_pic_back, picture, ",
        "safe_code",
        "from pwp_member",
        "where member_id = #{memberId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="pwd_safe_level", property="pwdSafeLevel", jdbcType=JdbcType.TINYINT),
        @Result(column="realname", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="credentials_type", property="credentialsType", jdbcType=JdbcType.TINYINT),
        @Result(column="credentials_code", property="credentialsCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="first_p_card_id", property="firstPCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="first_p_card_pwd", property="firstPCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_status", property="memberStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="salt", property="salt", jdbcType=JdbcType.VARCHAR),
        @Result(column="paypwd", property="paypwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="cert_pic_front", property="certPicFront", jdbcType=JdbcType.VARCHAR),
        @Result(column="cert_pic_back", property="certPicBack", jdbcType=JdbcType.VARCHAR),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR),
        @Result(column="safe_code", property="safeCode", jdbcType=JdbcType.VARCHAR)
    })
    PwpMember selectByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @UpdateProvider(type= PwpMemberSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpMember record, @Param("example") PwpMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @UpdateProvider(type= PwpMemberSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpMember record, @Param("example") PwpMemberCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @UpdateProvider(type= PwpMemberSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_member",
        "set phone = #{phone,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "pwd_safe_level = #{pwdSafeLevel,jdbcType=TINYINT},",
          "realname = #{realname,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "credentials_type = #{credentialsType,jdbcType=TINYINT},",
          "credentials_code = #{credentialsCode,jdbcType=VARCHAR},",
          "area_id = #{areaId,jdbcType=INTEGER},",
          "address = #{address,jdbcType=VARCHAR},",
          "first_p_card_id = #{firstPCardId,jdbcType=VARCHAR},",
          "first_p_card_pwd = #{firstPCardPwd,jdbcType=VARCHAR},",
          "member_status = #{memberStatus,jdbcType=TINYINT},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR},",
          "salt = #{salt,jdbcType=VARCHAR},",
          "paypwd = #{paypwd,jdbcType=VARCHAR},",
          "cert_pic_front = #{certPicFront,jdbcType=VARCHAR},",
          "cert_pic_back = #{certPicBack,jdbcType=VARCHAR},",
          "picture = #{picture,jdbcType=VARCHAR},",
          "safe_code = #{safeCode,jdbcType=VARCHAR}",
        "where member_id = #{memberId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpMember record);
}