package com.api.dao;

import com.api.dao.sqlProvider.PwpMemberDetailSqlProvider;
import com.api.entity.PwpMemberDetail;
import com.api.entity.PwpMemberDetailCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface PwpMemberDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMemberDetailSqlProvider.class, method="countByExample")
    long countByExample(PwpMemberDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PwpMemberDetailSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpMemberDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_member_detail",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_member_detail (id, member_id, ",
        "add_sequence, car_num, ",
        "realname, password, ",
        "password_key, pwd_safe_level, ",
        "phone, email, sex, ",
        "source, balance, ",
        "league_id, league_admin, ",
        "status, id_status, ",
        "id_card_no, id_card_front, ",
        "id_card_back, billing_account_id, ",
        "p_card_id, p_card_code, ",
        "p_card_pwd, car_card_no, ",
        "c_card_id, c_card_pwd, ",
        "driver_card_no, card_issue, ",
        "credentials_type, credentials_code, ",
        "credentials_pic, car_pic, ",
        "car_drive_no, car_engine_code, ",
        "car_type, car_insurance_no, ",
        "address, area_id, ",
        "use, used_years, ",
        "create_time, create_date, ",
        "reviewtime, update_time, ",
        "verify_msg, picture, ",
        "bind_weixin_account)",
        "values (#{id,jdbcType=INTEGER}, #{memberId,jdbcType=INTEGER}, ",
        "#{addSequence,jdbcType=INTEGER}, #{carNum,jdbcType=VARCHAR}, ",
        "#{realname,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{passwordKey,jdbcType=VARCHAR}, #{pwdSafeLevel,jdbcType=TINYINT}, ",
        "#{phone,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, #{sex,jdbcType=CHAR}, ",
        "#{source,jdbcType=TINYINT}, #{balance,jdbcType=DECIMAL}, ",
        "#{leagueId,jdbcType=INTEGER}, #{leagueAdmin,jdbcType=INTEGER}, ",
        "#{status,jdbcType=TINYINT}, #{idStatus,jdbcType=TINYINT}, ",
        "#{idCardNo,jdbcType=VARCHAR}, #{idCardFront,jdbcType=VARCHAR}, ",
        "#{idCardBack,jdbcType=VARCHAR}, #{billingAccountId,jdbcType=VARCHAR}, ",
        "#{pCardId,jdbcType=VARCHAR}, #{pCardCode,jdbcType=VARCHAR}, ",
        "#{pCardPwd,jdbcType=VARCHAR}, #{carCardNo,jdbcType=VARCHAR}, ",
        "#{cCardId,jdbcType=VARCHAR}, #{cCardPwd,jdbcType=VARCHAR}, ",
        "#{driverCardNo,jdbcType=VARCHAR}, #{cardIssue,jdbcType=TINYINT}, ",
        "#{credentialsType,jdbcType=SMALLINT}, #{credentialsCode,jdbcType=VARCHAR}, ",
        "#{credentialsPic,jdbcType=VARCHAR}, #{carPic,jdbcType=VARCHAR}, ",
        "#{carDriveNo,jdbcType=VARCHAR}, #{carEngineCode,jdbcType=VARCHAR}, ",
        "#{carType,jdbcType=TINYINT}, #{carInsuranceNo,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{areaId,jdbcType=INTEGER}, ",
        "#{use,jdbcType=VARCHAR}, #{usedYears,jdbcType=TINYINT}, ",
        "#{createTime,jdbcType=VARCHAR}, #{createDate,jdbcType=VARCHAR}, ",
        "#{reviewtime,jdbcType=VARCHAR}, #{updateTime,jdbcType=VARCHAR}, ",
        "#{verifyMsg,jdbcType=VARCHAR}, #{picture,jdbcType=VARCHAR}, ",
        "#{bindWeixinAccount,jdbcType=VARCHAR})"
    })
    int insert(PwpMemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail
     *
     * @mbg.generated
     */
    @InsertProvider(type=PwpMemberDetailSqlProvider.class, method="insertSelective")
    int insertSelective(PwpMemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpMemberDetailSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="add_sequence", property="addSequence", jdbcType=JdbcType.INTEGER),
        @Result(column="car_num", property="carNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="realname", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="password_key", property="passwordKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="pwd_safe_level", property="pwdSafeLevel", jdbcType=JdbcType.TINYINT),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.CHAR),
        @Result(column="source", property="source", jdbcType=JdbcType.TINYINT),
        @Result(column="balance", property="balance", jdbcType=JdbcType.DECIMAL),
        @Result(column="league_id", property="leagueId", jdbcType=JdbcType.INTEGER),
        @Result(column="league_admin", property="leagueAdmin", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="id_status", property="idStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="id_card_no", property="idCardNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="id_card_front", property="idCardFront", jdbcType=JdbcType.VARCHAR),
        @Result(column="id_card_back", property="idCardBack", jdbcType=JdbcType.VARCHAR),
        @Result(column="billing_account_id", property="billingAccountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_id", property="pCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_code", property="pCardCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_pwd", property="pCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_card_no", property="carCardNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="c_card_id", property="cCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="c_card_pwd", property="cCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_card_no", property="driverCardNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="card_issue", property="cardIssue", jdbcType=JdbcType.TINYINT),
        @Result(column="credentials_type", property="credentialsType", jdbcType=JdbcType.SMALLINT),
        @Result(column="credentials_code", property="credentialsCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="credentials_pic", property="credentialsPic", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_pic", property="carPic", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_drive_no", property="carDriveNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_engine_code", property="carEngineCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_type", property="carType", jdbcType=JdbcType.TINYINT),
        @Result(column="car_insurance_no", property="carInsuranceNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.INTEGER),
        @Result(column="use", property="use", jdbcType=JdbcType.VARCHAR),
        @Result(column="used_years", property="usedYears", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="reviewtime", property="reviewtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="verify_msg", property="verifyMsg", jdbcType=JdbcType.VARCHAR),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR),
        @Result(column="bind_weixin_account", property="bindWeixinAccount", jdbcType=JdbcType.VARCHAR)
    })
    List<PwpMemberDetail> selectByExample(PwpMemberDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, member_id, add_sequence, car_num, realname, password, password_key, pwd_safe_level, ",
        "phone, email, sex, source, balance, league_id, league_admin, status, id_status, ",
        "id_card_no, id_card_front, id_card_back, billing_account_id, p_card_id, p_card_code, ",
        "p_card_pwd, car_card_no, c_card_id, c_card_pwd, driver_card_no, card_issue, ",
        "credentials_type, credentials_code, credentials_pic, car_pic, car_drive_no, ",
        "car_engine_code, car_type, car_insurance_no, address, area_id, use, used_years, ",
        "create_time, create_date, reviewtime, update_time, verify_msg, picture, bind_weixin_account",
        "from pwp_member_detail",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="add_sequence", property="addSequence", jdbcType=JdbcType.INTEGER),
        @Result(column="car_num", property="carNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="realname", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="password_key", property="passwordKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="pwd_safe_level", property="pwdSafeLevel", jdbcType=JdbcType.TINYINT),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.CHAR),
        @Result(column="source", property="source", jdbcType=JdbcType.TINYINT),
        @Result(column="balance", property="balance", jdbcType=JdbcType.DECIMAL),
        @Result(column="league_id", property="leagueId", jdbcType=JdbcType.INTEGER),
        @Result(column="league_admin", property="leagueAdmin", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="id_status", property="idStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="id_card_no", property="idCardNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="id_card_front", property="idCardFront", jdbcType=JdbcType.VARCHAR),
        @Result(column="id_card_back", property="idCardBack", jdbcType=JdbcType.VARCHAR),
        @Result(column="billing_account_id", property="billingAccountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_id", property="pCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_code", property="pCardCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="p_card_pwd", property="pCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_card_no", property="carCardNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="c_card_id", property="cCardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="c_card_pwd", property="cCardPwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_card_no", property="driverCardNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="card_issue", property="cardIssue", jdbcType=JdbcType.TINYINT),
        @Result(column="credentials_type", property="credentialsType", jdbcType=JdbcType.SMALLINT),
        @Result(column="credentials_code", property="credentialsCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="credentials_pic", property="credentialsPic", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_pic", property="carPic", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_drive_no", property="carDriveNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_engine_code", property="carEngineCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_type", property="carType", jdbcType=JdbcType.TINYINT),
        @Result(column="car_insurance_no", property="carInsuranceNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.INTEGER),
        @Result(column="use", property="use", jdbcType=JdbcType.VARCHAR),
        @Result(column="used_years", property="usedYears", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="reviewtime", property="reviewtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="verify_msg", property="verifyMsg", jdbcType=JdbcType.VARCHAR),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR),
        @Result(column="bind_weixin_account", property="bindWeixinAccount", jdbcType=JdbcType.VARCHAR)
    })
    PwpMemberDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMemberDetailSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpMemberDetail record, @Param("example") PwpMemberDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMemberDetailSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpMemberDetail record, @Param("example") PwpMemberDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpMemberDetailSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpMemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_member_detail
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_member_detail",
        "set member_id = #{memberId,jdbcType=INTEGER},",
          "add_sequence = #{addSequence,jdbcType=INTEGER},",
          "car_num = #{carNum,jdbcType=VARCHAR},",
          "realname = #{realname,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "password_key = #{passwordKey,jdbcType=VARCHAR},",
          "pwd_safe_level = #{pwdSafeLevel,jdbcType=TINYINT},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=CHAR},",
          "source = #{source,jdbcType=TINYINT},",
          "balance = #{balance,jdbcType=DECIMAL},",
          "league_id = #{leagueId,jdbcType=INTEGER},",
          "league_admin = #{leagueAdmin,jdbcType=INTEGER},",
          "status = #{status,jdbcType=TINYINT},",
          "id_status = #{idStatus,jdbcType=TINYINT},",
          "id_card_no = #{idCardNo,jdbcType=VARCHAR},",
          "id_card_front = #{idCardFront,jdbcType=VARCHAR},",
          "id_card_back = #{idCardBack,jdbcType=VARCHAR},",
          "billing_account_id = #{billingAccountId,jdbcType=VARCHAR},",
          "p_card_id = #{pCardId,jdbcType=VARCHAR},",
          "p_card_code = #{pCardCode,jdbcType=VARCHAR},",
          "p_card_pwd = #{pCardPwd,jdbcType=VARCHAR},",
          "car_card_no = #{carCardNo,jdbcType=VARCHAR},",
          "c_card_id = #{cCardId,jdbcType=VARCHAR},",
          "c_card_pwd = #{cCardPwd,jdbcType=VARCHAR},",
          "driver_card_no = #{driverCardNo,jdbcType=VARCHAR},",
          "card_issue = #{cardIssue,jdbcType=TINYINT},",
          "credentials_type = #{credentialsType,jdbcType=SMALLINT},",
          "credentials_code = #{credentialsCode,jdbcType=VARCHAR},",
          "credentials_pic = #{credentialsPic,jdbcType=VARCHAR},",
          "car_pic = #{carPic,jdbcType=VARCHAR},",
          "car_drive_no = #{carDriveNo,jdbcType=VARCHAR},",
          "car_engine_code = #{carEngineCode,jdbcType=VARCHAR},",
          "car_type = #{carType,jdbcType=TINYINT},",
          "car_insurance_no = #{carInsuranceNo,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "area_id = #{areaId,jdbcType=INTEGER},",
          "use = #{use,jdbcType=VARCHAR},",
          "used_years = #{usedYears,jdbcType=TINYINT},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=VARCHAR},",
          "reviewtime = #{reviewtime,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR},",
          "verify_msg = #{verifyMsg,jdbcType=VARCHAR},",
          "picture = #{picture,jdbcType=VARCHAR},",
          "bind_weixin_account = #{bindWeixinAccount,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpMemberDetail record);
}