package com.api.dao;

import com.api.dao.sqlProvider.PwpParkSqlProvider;
import com.api.entity.PwpPark;
import com.api.entity.PwpParkCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface PwpParkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpParkSqlProvider.class, method="countByExample")
    long countByExample(PwpParkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PwpParkSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpParkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_park",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_park (id, league_id, ",
        "name, domain, park_num, ",
        "total_num, park_type, ",
        "address, position_x, ",
        "position_y, photo, ",
        "park_plan, descript, ",
        "system_ratio, bank_name, ",
        "bank_account, bank_card, ",
        "month_rule, park_status, ",
        "external_account, local_request_key, ",
        "create_time, update_time)",
        "values (#{id,jdbcType=INTEGER}, #{leagueId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{domain,jdbcType=VARCHAR}, #{parkNum,jdbcType=INTEGER}, ",
        "#{totalNum,jdbcType=INTEGER}, #{parkType,jdbcType=TINYINT}, ",
        "#{address,jdbcType=VARCHAR}, #{positionX,jdbcType=VARCHAR}, ",
        "#{positionY,jdbcType=VARCHAR}, #{photo,jdbcType=VARCHAR}, ",
        "#{parkPlan,jdbcType=VARCHAR}, #{descript,jdbcType=VARCHAR}, ",
        "#{systemRatio,jdbcType=DECIMAL}, #{bankName,jdbcType=VARCHAR}, ",
        "#{bankAccount,jdbcType=VARCHAR}, #{bankCard,jdbcType=VARCHAR}, ",
        "#{monthRule,jdbcType=INTEGER}, #{parkStatus,jdbcType=TINYINT}, ",
        "#{externalAccount,jdbcType=VARCHAR}, #{localRequestKey,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=VARCHAR}, #{updateTime,jdbcType=VARCHAR})"
    })
    int insert(PwpPark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    @InsertProvider(type=PwpParkSqlProvider.class, method="insertSelective")
    int insertSelective(PwpPark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    @SelectProvider(type=PwpParkSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="league_id", property="leagueId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="domain", property="domain", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_num", property="parkNum", jdbcType=JdbcType.INTEGER),
        @Result(column="total_num", property="totalNum", jdbcType=JdbcType.INTEGER),
        @Result(column="park_type", property="parkType", jdbcType=JdbcType.TINYINT),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="position_x", property="positionX", jdbcType=JdbcType.VARCHAR),
        @Result(column="position_y", property="positionY", jdbcType=JdbcType.VARCHAR),
        @Result(column="photo", property="photo", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_plan", property="parkPlan", jdbcType=JdbcType.VARCHAR),
        @Result(column="descript", property="descript", jdbcType=JdbcType.VARCHAR),
        @Result(column="system_ratio", property="systemRatio", jdbcType=JdbcType.DECIMAL),
        @Result(column="bank_name", property="bankName", jdbcType=JdbcType.VARCHAR),
        @Result(column="bank_account", property="bankAccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="bank_card", property="bankCard", jdbcType=JdbcType.VARCHAR),
        @Result(column="month_rule", property="monthRule", jdbcType=JdbcType.INTEGER),
        @Result(column="park_status", property="parkStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="external_account", property="externalAccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="local_request_key", property="localRequestKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR)
    })
    List<PwpPark> selectByExample(PwpParkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, league_id, name, domain, park_num, total_num, park_type, address, position_x, ",
        "position_y, photo, park_plan, descript, system_ratio, bank_name, bank_account, ",
        "bank_card, month_rule, park_status, external_account, local_request_key, create_time, ",
        "update_time",
        "from pwp_park",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="league_id", property="leagueId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="domain", property="domain", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_num", property="parkNum", jdbcType=JdbcType.INTEGER),
        @Result(column="total_num", property="totalNum", jdbcType=JdbcType.INTEGER),
        @Result(column="park_type", property="parkType", jdbcType=JdbcType.TINYINT),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="position_x", property="positionX", jdbcType=JdbcType.VARCHAR),
        @Result(column="position_y", property="positionY", jdbcType=JdbcType.VARCHAR),
        @Result(column="photo", property="photo", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_plan", property="parkPlan", jdbcType=JdbcType.VARCHAR),
        @Result(column="descript", property="descript", jdbcType=JdbcType.VARCHAR),
        @Result(column="system_ratio", property="systemRatio", jdbcType=JdbcType.DECIMAL),
        @Result(column="bank_name", property="bankName", jdbcType=JdbcType.VARCHAR),
        @Result(column="bank_account", property="bankAccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="bank_card", property="bankCard", jdbcType=JdbcType.VARCHAR),
        @Result(column="month_rule", property="monthRule", jdbcType=JdbcType.INTEGER),
        @Result(column="park_status", property="parkStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="external_account", property="externalAccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="local_request_key", property="localRequestKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR)
    })
    PwpPark selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpParkSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpPark record, @Param("example") PwpParkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpParkSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpPark record, @Param("example") PwpParkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PwpParkSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpPark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_park",
        "set league_id = #{leagueId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "domain = #{domain,jdbcType=VARCHAR},",
          "park_num = #{parkNum,jdbcType=INTEGER},",
          "total_num = #{totalNum,jdbcType=INTEGER},",
          "park_type = #{parkType,jdbcType=TINYINT},",
          "address = #{address,jdbcType=VARCHAR},",
          "position_x = #{positionX,jdbcType=VARCHAR},",
          "position_y = #{positionY,jdbcType=VARCHAR},",
          "photo = #{photo,jdbcType=VARCHAR},",
          "park_plan = #{parkPlan,jdbcType=VARCHAR},",
          "descript = #{descript,jdbcType=VARCHAR},",
          "system_ratio = #{systemRatio,jdbcType=DECIMAL},",
          "bank_name = #{bankName,jdbcType=VARCHAR},",
          "bank_account = #{bankAccount,jdbcType=VARCHAR},",
          "bank_card = #{bankCard,jdbcType=VARCHAR},",
          "month_rule = #{monthRule,jdbcType=INTEGER},",
          "park_status = #{parkStatus,jdbcType=TINYINT},",
          "external_account = #{externalAccount,jdbcType=VARCHAR},",
          "local_request_key = #{localRequestKey,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpPark record);
}