package com.api.dao;

import com.api.dao.sqlProvider.PwpPowerRuleSqlProvider;
import com.api.entity.PwpPowerRule;
import com.api.entity.PwpPowerRuleCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface PwpPowerRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_power_rule
     *
     * @mbg.generated
     */
    @SelectProvider(type= PwpPowerRuleSqlProvider.class, method="countByExample")
    long countByExample(PwpPowerRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_power_rule
     *
     * @mbg.generated
     */
    @DeleteProvider(type= PwpPowerRuleSqlProvider.class, method="deleteByExample")
    int deleteByExample(PwpPowerRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_power_rule
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pwp_power_rule",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_power_rule
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pwp_power_rule (id, power_rule_group_id, ",
        "belong)",
        "values (#{id,jdbcType=INTEGER}, #{powerRuleGroupId,jdbcType=VARCHAR}, ",
        "#{belong,jdbcType=VARCHAR})"
    })
    int insert(PwpPowerRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_power_rule
     *
     * @mbg.generated
     */
    @InsertProvider(type= PwpPowerRuleSqlProvider.class, method="insertSelective")
    int insertSelective(PwpPowerRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_power_rule
     *
     * @mbg.generated
     */
    @SelectProvider(type= PwpPowerRuleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="power_rule_group_id", property="powerRuleGroupId", jdbcType=JdbcType.VARCHAR),
        @Result(column="belong", property="belong", jdbcType=JdbcType.VARCHAR)
    })
    List<PwpPowerRule> selectByExample(PwpPowerRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_power_rule
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, power_rule_group_id, belong",
        "from pwp_power_rule",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="power_rule_group_id", property="powerRuleGroupId", jdbcType=JdbcType.VARCHAR),
        @Result(column="belong", property="belong", jdbcType=JdbcType.VARCHAR)
    })
    PwpPowerRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_power_rule
     *
     * @mbg.generated
     */
    @UpdateProvider(type= PwpPowerRuleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PwpPowerRule record, @Param("example") PwpPowerRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_power_rule
     *
     * @mbg.generated
     */
    @UpdateProvider(type= PwpPowerRuleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PwpPowerRule record, @Param("example") PwpPowerRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_power_rule
     *
     * @mbg.generated
     */
    @UpdateProvider(type= PwpPowerRuleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PwpPowerRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_power_rule
     *
     * @mbg.generated
     */
    @Update({
        "update pwp_power_rule",
        "set power_rule_group_id = #{powerRuleGroupId,jdbcType=VARCHAR},",
          "belong = #{belong,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PwpPowerRule record);
}