package com.api.dao;

import com.api.dao.sqlProvider.TApikeySqlProvider;
import com.api.entity.TApikey;
import com.api.entity.TApikeyCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TApikeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apikey
     *
     * @mbg.generated
     */
    @SelectProvider(type=TApikeySqlProvider.class, method="countByExample")
    long countByExample(TApikeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apikey
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TApikeySqlProvider.class, method="deleteByExample")
    int deleteByExample(TApikeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apikey
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_apikey",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apikey
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_apikey (id, key, ",
        "name, api_id, parkIds)",
        "values (#{id,jdbcType=INTEGER}, #{key,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{apiId,jdbcType=VARCHAR}, #{parkids,jdbcType=VARCHAR})"
    })
    int insert(TApikey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apikey
     *
     * @mbg.generated
     */
    @InsertProvider(type=TApikeySqlProvider.class, method="insertSelective")
    int insertSelective(TApikey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apikey
     *
     * @mbg.generated
     */
    @SelectProvider(type=TApikeySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="key", property="key", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="api_id", property="apiId", jdbcType=JdbcType.VARCHAR),
        @Result(column="parkIds", property="parkids", jdbcType=JdbcType.VARCHAR)
    })
    List<TApikey> selectByExample(TApikeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apikey
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, key, name, api_id, parkIds",
        "from t_apikey",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="key", property="key", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="api_id", property="apiId", jdbcType=JdbcType.VARCHAR),
        @Result(column="parkIds", property="parkids", jdbcType=JdbcType.VARCHAR)
    })
    TApikey selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apikey
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TApikeySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TApikey record, @Param("example") TApikeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apikey
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TApikeySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TApikey record, @Param("example") TApikeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apikey
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TApikeySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TApikey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apikey
     *
     * @mbg.generated
     */
    @Update({
        "update t_apikey",
        "set key = #{key,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "api_id = #{apiId,jdbcType=VARCHAR},",
          "parkIds = #{parkids,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TApikey record);
}