package com.api.dao;

import com.api.dao.sqlProvider.TBusinesCouponSqlProvider;
import com.api.entity.TBusinesCoupon;
import com.api.entity.TBusinesCouponCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TBusinesCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busines_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type= TBusinesCouponSqlProvider.class, method="countByExample")
    long countByExample(TBusinesCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busines_coupon
     *
     * @mbg.generated
     */
    @DeleteProvider(type= TBusinesCouponSqlProvider.class, method="deleteByExample")
    int deleteByExample(TBusinesCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busines_coupon
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_busines_coupon",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busines_coupon
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_busines_coupon (id, company_id, ",
        "park_id, busine_id, ",
        "car_plate, coupon_code, ",
        "coupon_pay, create_date, ",
        "end_date, remark, ",
        "park_name, in_time, ",
        "out_time, derate_type, ",
        "disable)",
        "values (#{id,jdbcType=INTEGER}, #{companyId,jdbcType=INTEGER}, ",
        "#{parkId,jdbcType=INTEGER}, #{busineId,jdbcType=INTEGER}, ",
        "#{carPlate,jdbcType=VARCHAR}, #{couponCode,jdbcType=VARCHAR}, ",
        "#{couponPay,jdbcType=DOUBLE}, #{createDate,jdbcType=VARCHAR}, ",
        "#{endDate,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{parkName,jdbcType=VARCHAR}, #{inTime,jdbcType=VARCHAR}, ",
        "#{outTime,jdbcType=VARCHAR}, #{derateType,jdbcType=INTEGER}, ",
        "#{disable,jdbcType=INTEGER})"
    })
    int insert(TBusinesCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busines_coupon
     *
     * @mbg.generated
     */
    @InsertProvider(type= TBusinesCouponSqlProvider.class, method="insertSelective")
    int insertSelective(TBusinesCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busines_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type= TBusinesCouponSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="busine_id", property="busineId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="coupon_code", property="couponCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="coupon_pay", property="couponPay", jdbcType=JdbcType.DOUBLE),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_date", property="endDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_name", property="parkName", jdbcType=JdbcType.VARCHAR),
        @Result(column="in_time", property="inTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_time", property="outTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="derate_type", property="derateType", jdbcType=JdbcType.INTEGER),
        @Result(column="disable", property="disable", jdbcType=JdbcType.INTEGER)
    })
    List<TBusinesCoupon> selectByExample(TBusinesCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busines_coupon
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, company_id, park_id, busine_id, car_plate, coupon_code, coupon_pay, create_date, ",
        "end_date, remark, park_name, in_time, out_time, derate_type, disable",
        "from t_busines_coupon",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="busine_id", property="busineId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="coupon_code", property="couponCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="coupon_pay", property="couponPay", jdbcType=JdbcType.DOUBLE),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_date", property="endDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_name", property="parkName", jdbcType=JdbcType.VARCHAR),
        @Result(column="in_time", property="inTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_time", property="outTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="derate_type", property="derateType", jdbcType=JdbcType.INTEGER),
        @Result(column="disable", property="disable", jdbcType=JdbcType.INTEGER)
    })
    TBusinesCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busines_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TBusinesCouponSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TBusinesCoupon record, @Param("example") TBusinesCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busines_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TBusinesCouponSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TBusinesCoupon record, @Param("example") TBusinesCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busines_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TBusinesCouponSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TBusinesCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busines_coupon
     *
     * @mbg.generated
     */
    @Update({
        "update t_busines_coupon",
        "set company_id = #{companyId,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "busine_id = #{busineId,jdbcType=INTEGER},",
          "car_plate = #{carPlate,jdbcType=VARCHAR},",
          "coupon_code = #{couponCode,jdbcType=VARCHAR},",
          "coupon_pay = #{couponPay,jdbcType=DOUBLE},",
          "create_date = #{createDate,jdbcType=VARCHAR},",
          "end_date = #{endDate,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "park_name = #{parkName,jdbcType=VARCHAR},",
          "in_time = #{inTime,jdbcType=VARCHAR},",
          "out_time = #{outTime,jdbcType=VARCHAR},",
          "derate_type = #{derateType,jdbcType=INTEGER},",
          "disable = #{disable,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TBusinesCoupon record);
}