package com.api.dao;

import com.api.dao.sqlProvider.TCardSqlProvider;
import com.api.entity.TCard;
import com.api.entity.TCardCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    @SelectProvider(type=TCardSqlProvider.class, method="countByExample")
    long countByExample(TCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TCardSqlProvider.class, method="deleteByExample")
    int deleteByExample(TCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_card",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_card (id, park_id, ",
        "status, card_id, ",
        "card_code, card_cvv, ",
        "create_data, update_date, ",
        "issue_date)",
        "values (#{id,jdbcType=BIGINT}, #{parkId,jdbcType=INTEGER}, ",
        "#{status,jdbcType=INTEGER}, #{cardId,jdbcType=VARCHAR}, ",
        "#{cardCode,jdbcType=VARCHAR}, #{cardCvv,jdbcType=VARCHAR}, ",
        "#{createData,jdbcType=VARCHAR}, #{updateDate,jdbcType=VARCHAR}, ",
        "#{issueDate,jdbcType=VARCHAR})"
    })
    int insert(TCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    @InsertProvider(type=TCardSqlProvider.class, method="insertSelective")
    int insertSelective(TCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    @SelectProvider(type=TCardSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="card_id", property="cardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="card_code", property="cardCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="card_cvv", property="cardCvv", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_data", property="createData", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="issue_date", property="issueDate", jdbcType=JdbcType.VARCHAR)
    })
    List<TCard> selectByExample(TCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, park_id, status, card_id, card_code, card_cvv, create_data, update_date, ",
        "issue_date",
        "from t_card",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="card_id", property="cardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="card_code", property="cardCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="card_cvv", property="cardCvv", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_data", property="createData", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="issue_date", property="issueDate", jdbcType=JdbcType.VARCHAR)
    })
    TCard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCardSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TCard record, @Param("example") TCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCardSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TCard record, @Param("example") TCardCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCardSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated
     */
    @Update({
        "update t_card",
        "set park_id = #{parkId,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "card_id = #{cardId,jdbcType=VARCHAR},",
          "card_code = #{cardCode,jdbcType=VARCHAR},",
          "card_cvv = #{cardCvv,jdbcType=VARCHAR},",
          "create_data = #{createData,jdbcType=VARCHAR},",
          "update_date = #{updateDate,jdbcType=VARCHAR},",
          "issue_date = #{issueDate,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TCard record);
}