package com.api.dao;

import com.api.dao.sqlProvider.TDicPrepayTypeSqlProvider;
import com.api.entity.TDicPrepayType;
import com.api.entity.TDicPrepayTypeCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TDicPrepayTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_prepay_type
     *
     * @mbg.generated
     */
    @SelectProvider(type= TDicPrepayTypeSqlProvider.class, method="countByExample")
    long countByExample(TDicPrepayTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_prepay_type
     *
     * @mbg.generated
     */
    @DeleteProvider(type= TDicPrepayTypeSqlProvider.class, method="deleteByExample")
    int deleteByExample(TDicPrepayTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_prepay_type
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_dic_prepay_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_prepay_type
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_dic_prepay_type (id, paytype_id, ",
        "payname, remarks)",
        "values (#{id,jdbcType=INTEGER}, #{paytypeId,jdbcType=INTEGER}, ",
        "#{payname,jdbcType=VARCHAR}, #{remarks,jdbcType=VARCHAR})"
    })
    int insert(TDicPrepayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_prepay_type
     *
     * @mbg.generated
     */
    @InsertProvider(type= TDicPrepayTypeSqlProvider.class, method="insertSelective")
    int insertSelective(TDicPrepayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_prepay_type
     *
     * @mbg.generated
     */
    @SelectProvider(type= TDicPrepayTypeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="paytype_id", property="paytypeId", jdbcType=JdbcType.INTEGER),
        @Result(column="payname", property="payname", jdbcType=JdbcType.VARCHAR),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR)
    })
    List<TDicPrepayType> selectByExample(TDicPrepayTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_prepay_type
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, paytype_id, payname, remarks",
        "from t_dic_prepay_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="paytype_id", property="paytypeId", jdbcType=JdbcType.INTEGER),
        @Result(column="payname", property="payname", jdbcType=JdbcType.VARCHAR),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR)
    })
    TDicPrepayType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_prepay_type
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TDicPrepayTypeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TDicPrepayType record, @Param("example") TDicPrepayTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_prepay_type
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TDicPrepayTypeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TDicPrepayType record, @Param("example") TDicPrepayTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_prepay_type
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TDicPrepayTypeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TDicPrepayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_prepay_type
     *
     * @mbg.generated
     */
    @Update({
        "update t_dic_prepay_type",
        "set paytype_id = #{paytypeId,jdbcType=INTEGER},",
          "payname = #{payname,jdbcType=VARCHAR},",
          "remarks = #{remarks,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TDicPrepayType record);
}