package com.api.dao;

import com.api.dao.sqlProvider.TGlobalInfoSqlProvider;
import com.api.entity.TGlobalInfo;
import com.api.entity.TGlobalInfoCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TGlobalInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @SelectProvider(type= TGlobalInfoSqlProvider.class, method="countByExample")
    long countByExample(TGlobalInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @DeleteProvider(type= TGlobalInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(TGlobalInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_global_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_global_info (id, park_id, ",
        "param_context, param_value, ",
        "param_desc, group_name, ",
        "param_number, param_type, ",
        "param_define)",
        "values (#{id,jdbcType=INTEGER}, #{parkId,jdbcType=INTEGER}, ",
        "#{paramContext,jdbcType=VARCHAR}, #{paramValue,jdbcType=VARCHAR}, ",
        "#{paramDesc,jdbcType=VARCHAR}, #{groupName,jdbcType=VARCHAR}, ",
        "#{paramNumber,jdbcType=INTEGER}, #{paramType,jdbcType=VARCHAR}, ",
        "#{paramDefine,jdbcType=LONGVARCHAR})"
    })
    int insert(TGlobalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @InsertProvider(type= TGlobalInfoSqlProvider.class, method="insertSelective")
    int insertSelective(TGlobalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @SelectProvider(type= TGlobalInfoSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="param_context", property="paramContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_value", property="paramValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_desc", property="paramDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="group_name", property="groupName", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_number", property="paramNumber", jdbcType=JdbcType.INTEGER),
        @Result(column="param_type", property="paramType", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_define", property="paramDefine", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<TGlobalInfo> selectByExampleWithBLOBs(TGlobalInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @SelectProvider(type= TGlobalInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="param_context", property="paramContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_value", property="paramValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_desc", property="paramDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="group_name", property="groupName", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_number", property="paramNumber", jdbcType=JdbcType.INTEGER),
        @Result(column="param_type", property="paramType", jdbcType=JdbcType.VARCHAR)
    })
    List<TGlobalInfo> selectByExample(TGlobalInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, park_id, param_context, param_value, param_desc, group_name, param_number, ",
        "param_type, param_define",
        "from t_global_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="param_context", property="paramContext", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_value", property="paramValue", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_desc", property="paramDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="group_name", property="groupName", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_number", property="paramNumber", jdbcType=JdbcType.INTEGER),
        @Result(column="param_type", property="paramType", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_define", property="paramDefine", jdbcType=JdbcType.LONGVARCHAR)
    })
    TGlobalInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TGlobalInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TGlobalInfo record, @Param("example") TGlobalInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TGlobalInfoSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") TGlobalInfo record, @Param("example") TGlobalInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TGlobalInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TGlobalInfo record, @Param("example") TGlobalInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TGlobalInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TGlobalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @Update({
        "update t_global_info",
        "set park_id = #{parkId,jdbcType=INTEGER},",
          "param_context = #{paramContext,jdbcType=VARCHAR},",
          "param_value = #{paramValue,jdbcType=VARCHAR},",
          "param_desc = #{paramDesc,jdbcType=VARCHAR},",
          "group_name = #{groupName,jdbcType=VARCHAR},",
          "param_number = #{paramNumber,jdbcType=INTEGER},",
          "param_type = #{paramType,jdbcType=VARCHAR},",
          "param_define = #{paramDefine,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(TGlobalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_global_info
     *
     * @mbg.generated
     */
    @Update({
        "update t_global_info",
        "set park_id = #{parkId,jdbcType=INTEGER},",
          "param_context = #{paramContext,jdbcType=VARCHAR},",
          "param_value = #{paramValue,jdbcType=VARCHAR},",
          "param_desc = #{paramDesc,jdbcType=VARCHAR},",
          "group_name = #{groupName,jdbcType=VARCHAR},",
          "param_number = #{paramNumber,jdbcType=INTEGER},",
          "param_type = #{paramType,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TGlobalInfo record);
}