package com.api.dao;

import com.api.dao.sqlProvider.THolidaySqlProvider;
import com.api.entity.THoliday;
import com.api.entity.THolidayCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface THolidayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     *
     * @mbg.generated
     */
    @SelectProvider(type=THolidaySqlProvider.class, method="countByExample")
    long countByExample(THolidayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     *
     * @mbg.generated
     */
    @DeleteProvider(type=THolidaySqlProvider.class, method="deleteByExample")
    int deleteByExample(THolidayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_holiday",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_holiday (id, begin_day, ",
        "begin_month, begin_time, ",
        "cascade_flag, cascade_id, ",
        "comp_index, day_count, ",
        "holiday_name, locId, ",
        "park_id, sta_flag)",
        "values (#{id,jdbcType=INTEGER}, #{beginDay,jdbcType=INTEGER}, ",
        "#{beginMonth,jdbcType=INTEGER}, #{beginTime,jdbcType=VARCHAR}, ",
        "#{cascadeFlag,jdbcType=INTEGER}, #{cascadeId,jdbcType=INTEGER}, ",
        "#{compIndex,jdbcType=VARCHAR}, #{dayCount,jdbcType=INTEGER}, ",
        "#{holidayName,jdbcType=VARCHAR}, #{locid,jdbcType=INTEGER}, ",
        "#{parkId,jdbcType=INTEGER}, #{staFlag,jdbcType=INTEGER})"
    })
    int insert(THoliday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     *
     * @mbg.generated
     */
    @InsertProvider(type=THolidaySqlProvider.class, method="insertSelective")
    int insertSelective(THoliday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     *
     * @mbg.generated
     */
    @SelectProvider(type=THolidaySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="begin_day", property="beginDay", jdbcType=JdbcType.INTEGER),
        @Result(column="begin_month", property="beginMonth", jdbcType=JdbcType.INTEGER),
        @Result(column="begin_time", property="beginTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="cascade_flag", property="cascadeFlag", jdbcType=JdbcType.INTEGER),
        @Result(column="cascade_id", property="cascadeId", jdbcType=JdbcType.INTEGER),
        @Result(column="comp_index", property="compIndex", jdbcType=JdbcType.VARCHAR),
        @Result(column="day_count", property="dayCount", jdbcType=JdbcType.INTEGER),
        @Result(column="holiday_name", property="holidayName", jdbcType=JdbcType.VARCHAR),
        @Result(column="locId", property="locid", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="sta_flag", property="staFlag", jdbcType=JdbcType.INTEGER)
    })
    List<THoliday> selectByExample(THolidayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, begin_day, begin_month, begin_time, cascade_flag, cascade_id, comp_index, ",
        "day_count, holiday_name, locId, park_id, sta_flag",
        "from t_holiday",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="begin_day", property="beginDay", jdbcType=JdbcType.INTEGER),
        @Result(column="begin_month", property="beginMonth", jdbcType=JdbcType.INTEGER),
        @Result(column="begin_time", property="beginTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="cascade_flag", property="cascadeFlag", jdbcType=JdbcType.INTEGER),
        @Result(column="cascade_id", property="cascadeId", jdbcType=JdbcType.INTEGER),
        @Result(column="comp_index", property="compIndex", jdbcType=JdbcType.VARCHAR),
        @Result(column="day_count", property="dayCount", jdbcType=JdbcType.INTEGER),
        @Result(column="holiday_name", property="holidayName", jdbcType=JdbcType.VARCHAR),
        @Result(column="locId", property="locid", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="sta_flag", property="staFlag", jdbcType=JdbcType.INTEGER)
    })
    THoliday selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     *
     * @mbg.generated
     */
    @UpdateProvider(type=THolidaySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") THoliday record, @Param("example") THolidayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     *
     * @mbg.generated
     */
    @UpdateProvider(type=THolidaySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") THoliday record, @Param("example") THolidayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     *
     * @mbg.generated
     */
    @UpdateProvider(type=THolidaySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(THoliday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     *
     * @mbg.generated
     */
    @Update({
        "update t_holiday",
        "set begin_day = #{beginDay,jdbcType=INTEGER},",
          "begin_month = #{beginMonth,jdbcType=INTEGER},",
          "begin_time = #{beginTime,jdbcType=VARCHAR},",
          "cascade_flag = #{cascadeFlag,jdbcType=INTEGER},",
          "cascade_id = #{cascadeId,jdbcType=INTEGER},",
          "comp_index = #{compIndex,jdbcType=VARCHAR},",
          "day_count = #{dayCount,jdbcType=INTEGER},",
          "holiday_name = #{holidayName,jdbcType=VARCHAR},",
          "locId = #{locid,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "sta_flag = #{staFlag,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(THoliday record);
}