package com.api.dao;

import com.api.dao.sqlProvider.THouseholdFeedbackSqlProvider;
import com.api.entity.THouseholdFeedback;
import com.api.entity.THouseholdFeedbackCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface THouseholdFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_household_feedback
     *
     * @mbg.generated
     */
    @SelectProvider(type= THouseholdFeedbackSqlProvider.class, method="countByExample")
    long countByExample(THouseholdFeedbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_household_feedback
     *
     * @mbg.generated
     */
    @DeleteProvider(type=THouseholdFeedbackSqlProvider.class, method="deleteByExample")
    int deleteByExample(THouseholdFeedbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_household_feedback
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_household_feedback",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_household_feedback
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_household_feedback (id, company_id, ",
        "park_id, member_id, ",
        "name, sex, phone_number, ",
        "content, create_time, ",
        "reply_content, reply_time, ",
        "reply_user)",
        "values (#{id,jdbcType=INTEGER}, #{companyId,jdbcType=INTEGER}, ",
        "#{parkId,jdbcType=INTEGER}, #{memberId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{sex,jdbcType=INTEGER}, #{phoneNumber,jdbcType=VARCHAR}, ",
        "#{content,jdbcType=VARCHAR}, #{createTime,jdbcType=VARCHAR}, ",
        "#{replyContent,jdbcType=VARCHAR}, #{replyTime,jdbcType=VARCHAR}, ",
        "#{replyUser,jdbcType=INTEGER})"
    })
    int insert(THouseholdFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_household_feedback
     *
     * @mbg.generated
     */
    @InsertProvider(type=THouseholdFeedbackSqlProvider.class, method="insertSelective")
    int insertSelective(THouseholdFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_household_feedback
     *
     * @mbg.generated
     */
    @SelectProvider(type=THouseholdFeedbackSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.INTEGER),
        @Result(column="phone_number", property="phoneNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="reply_content", property="replyContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="reply_time", property="replyTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="reply_user", property="replyUser", jdbcType=JdbcType.INTEGER)
    })
    List<THouseholdFeedback> selectByExample(THouseholdFeedbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_household_feedback
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, company_id, park_id, member_id, name, sex, phone_number, content, create_time, ",
        "reply_content, reply_time, reply_user",
        "from t_household_feedback",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.INTEGER),
        @Result(column="phone_number", property="phoneNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="reply_content", property="replyContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="reply_time", property="replyTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="reply_user", property="replyUser", jdbcType=JdbcType.INTEGER)
    })
    THouseholdFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_household_feedback
     *
     * @mbg.generated
     */
    @UpdateProvider(type=THouseholdFeedbackSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") THouseholdFeedback record, @Param("example") THouseholdFeedbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_household_feedback
     *
     * @mbg.generated
     */
    @UpdateProvider(type=THouseholdFeedbackSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") THouseholdFeedback record, @Param("example") THouseholdFeedbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_household_feedback
     *
     * @mbg.generated
     */
    @UpdateProvider(type=THouseholdFeedbackSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(THouseholdFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_household_feedback
     *
     * @mbg.generated
     */
    @Update({
        "update t_household_feedback",
        "set company_id = #{companyId,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "member_id = #{memberId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=INTEGER},",
          "phone_number = #{phoneNumber,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "reply_content = #{replyContent,jdbcType=VARCHAR},",
          "reply_time = #{replyTime,jdbcType=VARCHAR},",
          "reply_user = #{replyUser,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(THouseholdFeedback record);
}