package com.api.dao;

import com.api.dao.sqlProvider.TJournalSqlProvider;
import com.api.entity.TJournal;
import com.api.entity.TJournalCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TJournalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal
     *
     * @mbg.generated
     */
    @SelectProvider(type=TJournalSqlProvider.class, method="countByExample")
    long countByExample(TJournalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TJournalSqlProvider.class, method="deleteByExample")
    int deleteByExample(TJournalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_journal",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_journal (id, company_user, ",
        "company_user_id, parkId, ",
        "date, ip, operating_type, ",
        "operation_content, status)",
        "values (#{id,jdbcType=INTEGER}, #{companyUser,jdbcType=VARCHAR}, ",
        "#{companyUserId,jdbcType=INTEGER}, #{parkid,jdbcType=INTEGER}, ",
        "#{date,jdbcType=VARCHAR}, #{ip,jdbcType=VARCHAR}, #{operatingType,jdbcType=INTEGER}, ",
        "#{operationContent,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER})"
    })
    int insert(TJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal
     *
     * @mbg.generated
     */
    @InsertProvider(type=TJournalSqlProvider.class, method="insertSelective")
    int insertSelective(TJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal
     *
     * @mbg.generated
     */
    @SelectProvider(type=TJournalSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_user", property="companyUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="company_user_id", property="companyUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="parkId", property="parkid", jdbcType=JdbcType.INTEGER),
        @Result(column="date", property="date", jdbcType=JdbcType.VARCHAR),
        @Result(column="ip", property="ip", jdbcType=JdbcType.VARCHAR),
        @Result(column="operating_type", property="operatingType", jdbcType=JdbcType.INTEGER),
        @Result(column="operation_content", property="operationContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER)
    })
    List<TJournal> selectByExample(TJournalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, company_user, company_user_id, parkId, date, ip, operating_type, operation_content, ",
        "status",
        "from t_journal",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_user", property="companyUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="company_user_id", property="companyUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="parkId", property="parkid", jdbcType=JdbcType.INTEGER),
        @Result(column="date", property="date", jdbcType=JdbcType.VARCHAR),
        @Result(column="ip", property="ip", jdbcType=JdbcType.VARCHAR),
        @Result(column="operating_type", property="operatingType", jdbcType=JdbcType.INTEGER),
        @Result(column="operation_content", property="operationContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER)
    })
    TJournal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TJournalSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TJournal record, @Param("example") TJournalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TJournalSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TJournal record, @Param("example") TJournalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TJournalSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TJournal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal
     *
     * @mbg.generated
     */
    @Update({
        "update t_journal",
        "set company_user = #{companyUser,jdbcType=VARCHAR},",
          "company_user_id = #{companyUserId,jdbcType=INTEGER},",
          "parkId = #{parkid,jdbcType=INTEGER},",
          "date = #{date,jdbcType=VARCHAR},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "operating_type = #{operatingType,jdbcType=INTEGER},",
          "operation_content = #{operationContent,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TJournal record);
}