package com.api.dao;

import com.api.dao.sqlProvider.TLowpeakbytimespanSqlProvider;
import com.api.entity.TLowpeakbytimespan;
import com.api.entity.TLowpeakbytimespanCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TLowpeakbytimespanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    @SelectProvider(type= TLowpeakbytimespanSqlProvider.class, method="countByExample")
    long countByExample(TLowpeakbytimespanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    @DeleteProvider(type= TLowpeakbytimespanSqlProvider.class, method="deleteByExample")
    int deleteByExample(TLowpeakbytimespanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_lowpeakbytimespan",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_lowpeakbytimespan (id, begin_time_hour, ",
        "begin_time_minute, cascade_flag, ",
        "cascade_id, comp_index, ",
        "end_time_hour, end_time_minute, ",
        "locId, park_id, sta_flag, ",
        "type)",
        "values (#{id,jdbcType=INTEGER}, #{beginTimeHour,jdbcType=INTEGER}, ",
        "#{beginTimeMinute,jdbcType=INTEGER}, #{cascadeFlag,jdbcType=INTEGER}, ",
        "#{cascadeId,jdbcType=INTEGER}, #{compIndex,jdbcType=VARCHAR}, ",
        "#{endTimeHour,jdbcType=INTEGER}, #{endTimeMinute,jdbcType=INTEGER}, ",
        "#{locid,jdbcType=INTEGER}, #{parkId,jdbcType=INTEGER}, #{staFlag,jdbcType=INTEGER}, ",
        "#{type,jdbcType=INTEGER})"
    })
    int insert(TLowpeakbytimespan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    @InsertProvider(type= TLowpeakbytimespanSqlProvider.class, method="insertSelective")
    int insertSelective(TLowpeakbytimespan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    @SelectProvider(type= TLowpeakbytimespanSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="begin_time_hour", property="beginTimeHour", jdbcType=JdbcType.INTEGER),
        @Result(column="begin_time_minute", property="beginTimeMinute", jdbcType=JdbcType.INTEGER),
        @Result(column="cascade_flag", property="cascadeFlag", jdbcType=JdbcType.INTEGER),
        @Result(column="cascade_id", property="cascadeId", jdbcType=JdbcType.INTEGER),
        @Result(column="comp_index", property="compIndex", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_time_hour", property="endTimeHour", jdbcType=JdbcType.INTEGER),
        @Result(column="end_time_minute", property="endTimeMinute", jdbcType=JdbcType.INTEGER),
        @Result(column="locId", property="locid", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="sta_flag", property="staFlag", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER)
    })
    List<TLowpeakbytimespan> selectByExample(TLowpeakbytimespanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, begin_time_hour, begin_time_minute, cascade_flag, cascade_id, comp_index, ",
        "end_time_hour, end_time_minute, locId, park_id, sta_flag, type",
        "from t_lowpeakbytimespan",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="begin_time_hour", property="beginTimeHour", jdbcType=JdbcType.INTEGER),
        @Result(column="begin_time_minute", property="beginTimeMinute", jdbcType=JdbcType.INTEGER),
        @Result(column="cascade_flag", property="cascadeFlag", jdbcType=JdbcType.INTEGER),
        @Result(column="cascade_id", property="cascadeId", jdbcType=JdbcType.INTEGER),
        @Result(column="comp_index", property="compIndex", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_time_hour", property="endTimeHour", jdbcType=JdbcType.INTEGER),
        @Result(column="end_time_minute", property="endTimeMinute", jdbcType=JdbcType.INTEGER),
        @Result(column="locId", property="locid", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="sta_flag", property="staFlag", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER)
    })
    TLowpeakbytimespan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TLowpeakbytimespanSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TLowpeakbytimespan record, @Param("example") TLowpeakbytimespanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TLowpeakbytimespanSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TLowpeakbytimespan record, @Param("example") TLowpeakbytimespanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TLowpeakbytimespanSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TLowpeakbytimespan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    @Update({
        "update t_lowpeakbytimespan",
        "set begin_time_hour = #{beginTimeHour,jdbcType=INTEGER},",
          "begin_time_minute = #{beginTimeMinute,jdbcType=INTEGER},",
          "cascade_flag = #{cascadeFlag,jdbcType=INTEGER},",
          "cascade_id = #{cascadeId,jdbcType=INTEGER},",
          "comp_index = #{compIndex,jdbcType=VARCHAR},",
          "end_time_hour = #{endTimeHour,jdbcType=INTEGER},",
          "end_time_minute = #{endTimeMinute,jdbcType=INTEGER},",
          "locId = #{locid,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "sta_flag = #{staFlag,jdbcType=INTEGER},",
          "type = #{type,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TLowpeakbytimespan record);
}