package com.api.dao;

import com.api.dao.sqlProvider.TPrepaySqlProvider;
import com.api.entity.TPrepay;
import com.api.entity.TPrepayCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TPrepayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    @SelectProvider(type= TPrepaySqlProvider.class, method="countByExample")
    long countByExample(TPrepayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    @DeleteProvider(type= TPrepaySqlProvider.class, method="deleteByExample")
    int deleteByExample(TPrepayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_prepay",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_prepay (id, park_id, ",
        "car_plate, order_id, ",
        "prepay_order_Id, prepay_type, ",
        "actual_prepay_type, actual_prepay, ",
        "coupon_prepay, out_time, ",
        "actual_paid, remarks)",
        "values (#{id,jdbcType=INTEGER}, #{parkId,jdbcType=INTEGER}, ",
        "#{carPlate,jdbcType=VARCHAR}, #{orderId,jdbcType=VARCHAR}, ",
        "#{prepayOrderId,jdbcType=VARCHAR}, #{prepayType,jdbcType=INTEGER}, ",
        "#{actualPrepayType,jdbcType=INTEGER}, #{actualPrepay,jdbcType=DOUBLE}, ",
        "#{couponPrepay,jdbcType=DOUBLE}, #{outTime,jdbcType=VARCHAR}, ",
        "#{actualPaid,jdbcType=DOUBLE}, #{remarks,jdbcType=VARCHAR})"
    })
    int insert(TPrepay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    @InsertProvider(type= TPrepaySqlProvider.class, method="insertSelective")
    int insertSelective(TPrepay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    @SelectProvider(type= TPrepaySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="prepay_order_Id", property="prepayOrderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="prepay_type", property="prepayType", jdbcType=JdbcType.INTEGER),
        @Result(column="actual_prepay_type", property="actualPrepayType", jdbcType=JdbcType.INTEGER),
        @Result(column="actual_prepay", property="actualPrepay", jdbcType=JdbcType.DOUBLE),
        @Result(column="coupon_prepay", property="couponPrepay", jdbcType=JdbcType.DOUBLE),
        @Result(column="out_time", property="outTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="actual_paid", property="actualPaid", jdbcType=JdbcType.DOUBLE),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR)
    })
    List<TPrepay> selectByExample(TPrepayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, park_id, car_plate, order_id, prepay_order_Id, prepay_type, actual_prepay_type, ",
        "actual_prepay, coupon_prepay, out_time, actual_paid, remarks",
        "from t_prepay",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="prepay_order_Id", property="prepayOrderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="prepay_type", property="prepayType", jdbcType=JdbcType.INTEGER),
        @Result(column="actual_prepay_type", property="actualPrepayType", jdbcType=JdbcType.INTEGER),
        @Result(column="actual_prepay", property="actualPrepay", jdbcType=JdbcType.DOUBLE),
        @Result(column="coupon_prepay", property="couponPrepay", jdbcType=JdbcType.DOUBLE),
        @Result(column="out_time", property="outTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="actual_paid", property="actualPaid", jdbcType=JdbcType.DOUBLE),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR)
    })
    TPrepay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TPrepaySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TPrepay record, @Param("example") TPrepayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TPrepaySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TPrepay record, @Param("example") TPrepayCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    @UpdateProvider(type= TPrepaySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TPrepay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    @Update({
        "update t_prepay",
        "set park_id = #{parkId,jdbcType=INTEGER},",
          "car_plate = #{carPlate,jdbcType=VARCHAR},",
          "order_id = #{orderId,jdbcType=VARCHAR},",
          "prepay_order_Id = #{prepayOrderId,jdbcType=VARCHAR},",
          "prepay_type = #{prepayType,jdbcType=INTEGER},",
          "actual_prepay_type = #{actualPrepayType,jdbcType=INTEGER},",
          "actual_prepay = #{actualPrepay,jdbcType=DOUBLE},",
          "coupon_prepay = #{couponPrepay,jdbcType=DOUBLE},",
          "out_time = #{outTime,jdbcType=VARCHAR},",
          "actual_paid = #{actualPaid,jdbcType=DOUBLE},",
          "remarks = #{remarks,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TPrepay record);
}