package com.api.dao;

import com.api.dao.sqlProvider.TPropertyHouseholdInfoSqlProvider;
import com.api.entity.TPropertyHouseholdInfo;
import com.api.entity.TPropertyHouseholdInfoCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TPropertyHouseholdInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_household_info
     *
     * @mbg.generated
     */
    @SelectProvider(type= TPropertyHouseholdInfoSqlProvider.class, method="countByExample")
    long countByExample(TPropertyHouseholdInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_household_info
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TPropertyHouseholdInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(TPropertyHouseholdInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_household_info
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_property_household_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_household_info
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_property_household_info (id, member_id, ",
        "company_id, park_id, ",
        "name, sex, phone_number, ",
        "village_name, address, ",
        "is_auditing, create_time, ",
        "auditing_time, auditing_user_id, ",
        "update_time)",
        "values (#{id,jdbcType=INTEGER}, #{memberId,jdbcType=INTEGER}, ",
        "#{companyId,jdbcType=INTEGER}, #{parkId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{sex,jdbcType=INTEGER}, #{phoneNumber,jdbcType=VARCHAR}, ",
        "#{villageName,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{isAuditing,jdbcType=INTEGER}, #{createTime,jdbcType=VARCHAR}, ",
        "#{auditingTime,jdbcType=VARCHAR}, #{auditingUserId,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=VARCHAR})"
    })
    int insert(TPropertyHouseholdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_household_info
     *
     * @mbg.generated
     */
    @InsertProvider(type=TPropertyHouseholdInfoSqlProvider.class, method="insertSelective")
    int insertSelective(TPropertyHouseholdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_household_info
     *
     * @mbg.generated
     */
    @SelectProvider(type=TPropertyHouseholdInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType= JdbcType.INTEGER),
        @Result(column="company_id", property="companyId", jdbcType= JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType= JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType= JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType= JdbcType.INTEGER),
        @Result(column="phone_number", property="phoneNumber", jdbcType= JdbcType.VARCHAR),
        @Result(column="village_name", property="villageName", jdbcType= JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType= JdbcType.VARCHAR),
        @Result(column="is_auditing", property="isAuditing", jdbcType= JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType= JdbcType.VARCHAR),
        @Result(column="auditing_time", property="auditingTime", jdbcType= JdbcType.VARCHAR),
        @Result(column="auditing_user_id", property="auditingUserId", jdbcType= JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType= JdbcType.VARCHAR)
    })
    List<TPropertyHouseholdInfo> selectByExample(TPropertyHouseholdInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_household_info
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, member_id, company_id, park_id, name, sex, phone_number, village_name, address, ",
        "is_auditing, create_time, auditing_time, auditing_user_id, update_time",
        "from t_property_household_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType= JdbcType.INTEGER),
        @Result(column="company_id", property="companyId", jdbcType= JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType= JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType= JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType= JdbcType.INTEGER),
        @Result(column="phone_number", property="phoneNumber", jdbcType= JdbcType.VARCHAR),
        @Result(column="village_name", property="villageName", jdbcType= JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType= JdbcType.VARCHAR),
        @Result(column="is_auditing", property="isAuditing", jdbcType= JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType= JdbcType.VARCHAR),
        @Result(column="auditing_time", property="auditingTime", jdbcType= JdbcType.VARCHAR),
        @Result(column="auditing_user_id", property="auditingUserId", jdbcType= JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType= JdbcType.VARCHAR)
    })
    TPropertyHouseholdInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_household_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPropertyHouseholdInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TPropertyHouseholdInfo record, @Param("example") TPropertyHouseholdInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_household_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPropertyHouseholdInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TPropertyHouseholdInfo record, @Param("example") TPropertyHouseholdInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_household_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPropertyHouseholdInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TPropertyHouseholdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_property_household_info
     *
     * @mbg.generated
     */
    @Update({
        "update t_property_household_info",
        "set member_id = #{memberId,jdbcType=INTEGER},",
          "company_id = #{companyId,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=INTEGER},",
          "phone_number = #{phoneNumber,jdbcType=VARCHAR},",
          "village_name = #{villageName,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "is_auditing = #{isAuditing,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "auditing_time = #{auditingTime,jdbcType=VARCHAR},",
          "auditing_user_id = #{auditingUserId,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TPropertyHouseholdInfo record);
}