package com.api.dao;

import com.api.dao.sqlProvider.TRolePowerNewSqlProvider;
import com.api.entity.TRolePowerNew;
import com.api.entity.TRolePowerNewCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TRolePowerNewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @SelectProvider(type=TRolePowerNewSqlProvider.class, method="countByExample")
    long countByExample(TRolePowerNewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TRolePowerNewSqlProvider.class, method="deleteByExample")
    int deleteByExample(TRolePowerNewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_role_power_new",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_role_power_new (id, company_id, ",
        "remark, role_name, ",
        "user_id, module_id)",
        "values (#{id,jdbcType=INTEGER}, #{companyId,jdbcType=INTEGER}, ",
        "#{remark,jdbcType=VARCHAR}, #{roleName,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=INTEGER}, #{moduleId,jdbcType=LONGVARCHAR})"
    })
    int insert(TRolePowerNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @InsertProvider(type=TRolePowerNewSqlProvider.class, method="insertSelective")
    int insertSelective(TRolePowerNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @SelectProvider(type=TRolePowerNewSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_name", property="roleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="module_id", property="moduleId", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<TRolePowerNew> selectByExampleWithBLOBs(TRolePowerNewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @SelectProvider(type=TRolePowerNewSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_name", property="roleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER)
    })
    List<TRolePowerNew> selectByExample(TRolePowerNewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, company_id, remark, role_name, user_id, module_id",
        "from t_role_power_new",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_name", property="roleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="module_id", property="moduleId", jdbcType=JdbcType.LONGVARCHAR)
    })
    TRolePowerNew selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TRolePowerNewSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TRolePowerNew record, @Param("example") TRolePowerNewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TRolePowerNewSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") TRolePowerNew record, @Param("example") TRolePowerNewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TRolePowerNewSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TRolePowerNew record, @Param("example") TRolePowerNewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TRolePowerNewSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TRolePowerNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @Update({
        "update t_role_power_new",
        "set company_id = #{companyId,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "role_name = #{roleName,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "module_id = #{moduleId,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(TRolePowerNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_power_new
     *
     * @mbg.generated
     */
    @Update({
        "update t_role_power_new",
        "set company_id = #{companyId,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "role_name = #{roleName,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TRolePowerNew record);
}