package com.api.dao;

import com.api.dao.sqlProvider.TTruckSpaceSqlProvider;
import com.api.entity.TTruckSpace;
import com.api.entity.TTruckSpaceCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TTruckSpaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_truck_space
     *
     * @mbg.generated
     */
    @SelectProvider(type=TTruckSpaceSqlProvider.class, method="countByExample")
    long countByExample(TTruckSpaceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_truck_space
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TTruckSpaceSqlProvider.class, method="deleteByExample")
    int deleteByExample(TTruckSpaceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_truck_space
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_truck_space",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_truck_space
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_truck_space (id, park_code, ",
        "parking_space, parking_state, ",
        "their_car_plate, use_car_plate, ",
        "company_id, park_id)",
        "values (#{id,jdbcType=INTEGER}, #{parkCode,jdbcType=VARCHAR}, ",
        "#{parkingSpace,jdbcType=INTEGER}, #{parkingState,jdbcType=INTEGER}, ",
        "#{theirCarPlate,jdbcType=VARCHAR}, #{useCarPlate,jdbcType=VARCHAR}, ",
        "#{companyId,jdbcType=INTEGER}, #{parkId,jdbcType=INTEGER})"
    })
    int insert(TTruckSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_truck_space
     *
     * @mbg.generated
     */
    @InsertProvider(type=TTruckSpaceSqlProvider.class, method="insertSelective")
    int insertSelective(TTruckSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_truck_space
     *
     * @mbg.generated
     */
    @SelectProvider(type=TTruckSpaceSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_code", property="parkCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="parking_space", property="parkingSpace", jdbcType=JdbcType.INTEGER),
        @Result(column="parking_state", property="parkingState", jdbcType=JdbcType.INTEGER),
        @Result(column="their_car_plate", property="theirCarPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="use_car_plate", property="useCarPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER)
    })
    List<TTruckSpace> selectByExample(TTruckSpaceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_truck_space
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, park_code, parking_space, parking_state, their_car_plate, use_car_plate, ",
        "company_id, park_id",
        "from t_truck_space",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_code", property="parkCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="parking_space", property="parkingSpace", jdbcType=JdbcType.INTEGER),
        @Result(column="parking_state", property="parkingState", jdbcType=JdbcType.INTEGER),
        @Result(column="their_car_plate", property="theirCarPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="use_car_plate", property="useCarPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER)
    })
    TTruckSpace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_truck_space
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TTruckSpaceSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TTruckSpace record, @Param("example") TTruckSpaceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_truck_space
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TTruckSpaceSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TTruckSpace record, @Param("example") TTruckSpaceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_truck_space
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TTruckSpaceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TTruckSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_truck_space
     *
     * @mbg.generated
     */
    @Update({
        "update t_truck_space",
        "set park_code = #{parkCode,jdbcType=VARCHAR},",
          "parking_space = #{parkingSpace,jdbcType=INTEGER},",
          "parking_state = #{parkingState,jdbcType=INTEGER},",
          "their_car_plate = #{theirCarPlate,jdbcType=VARCHAR},",
          "use_car_plate = #{useCarPlate,jdbcType=VARCHAR},",
          "company_id = #{companyId,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TTruckSpace record);
}