package com.api.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CarEntryCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    public CarEntryCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(String value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(String value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(String value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(String value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(String value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLike(String value) {
            addCriterion("member_id like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotLike(String value) {
            addCriterion("member_id not like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<String> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<String> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(String value1, String value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(String value1, String value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andParkIdIsNull() {
            addCriterion("park_id is null");
            return (Criteria) this;
        }

        public Criteria andParkIdIsNotNull() {
            addCriterion("park_id is not null");
            return (Criteria) this;
        }

        public Criteria andParkIdEqualTo(Integer value) {
            addCriterion("park_id =", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotEqualTo(Integer value) {
            addCriterion("park_id <>", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdGreaterThan(Integer value) {
            addCriterion("park_id >", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("park_id >=", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdLessThan(Integer value) {
            addCriterion("park_id <", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdLessThanOrEqualTo(Integer value) {
            addCriterion("park_id <=", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdIn(List<Integer> values) {
            addCriterion("park_id in", values, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotIn(List<Integer> values) {
            addCriterion("park_id not in", values, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdBetween(Integer value1, Integer value2) {
            addCriterion("park_id between", value1, value2, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("park_id not between", value1, value2, "parkId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCarPlateIsNull() {
            addCriterion("car_plate is null");
            return (Criteria) this;
        }

        public Criteria andCarPlateIsNotNull() {
            addCriterion("car_plate is not null");
            return (Criteria) this;
        }

        public Criteria andCarPlateEqualTo(String value) {
            addCriterion("car_plate =", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateNotEqualTo(String value) {
            addCriterion("car_plate <>", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateGreaterThan(String value) {
            addCriterion("car_plate >", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateGreaterThanOrEqualTo(String value) {
            addCriterion("car_plate >=", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateLessThan(String value) {
            addCriterion("car_plate <", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateLessThanOrEqualTo(String value) {
            addCriterion("car_plate <=", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateLike(String value) {
            addCriterion("car_plate like", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateNotLike(String value) {
            addCriterion("car_plate not like", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateIn(List<String> values) {
            addCriterion("car_plate in", values, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateNotIn(List<String> values) {
            addCriterion("car_plate not in", values, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateBetween(String value1, String value2) {
            addCriterion("car_plate between", value1, value2, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateNotBetween(String value1, String value2) {
            addCriterion("car_plate not between", value1, value2, "carPlate");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgIsNull() {
            addCriterion("driver_card_img is null");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgIsNotNull() {
            addCriterion("driver_card_img is not null");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgEqualTo(String value) {
            addCriterion("driver_card_img =", value, "driverCardImg");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgNotEqualTo(String value) {
            addCriterion("driver_card_img <>", value, "driverCardImg");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgGreaterThan(String value) {
            addCriterion("driver_card_img >", value, "driverCardImg");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgGreaterThanOrEqualTo(String value) {
            addCriterion("driver_card_img >=", value, "driverCardImg");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgLessThan(String value) {
            addCriterion("driver_card_img <", value, "driverCardImg");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgLessThanOrEqualTo(String value) {
            addCriterion("driver_card_img <=", value, "driverCardImg");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgLike(String value) {
            addCriterion("driver_card_img like", value, "driverCardImg");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgNotLike(String value) {
            addCriterion("driver_card_img not like", value, "driverCardImg");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgIn(List<String> values) {
            addCriterion("driver_card_img in", values, "driverCardImg");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgNotIn(List<String> values) {
            addCriterion("driver_card_img not in", values, "driverCardImg");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgBetween(String value1, String value2) {
            addCriterion("driver_card_img between", value1, value2, "driverCardImg");
            return (Criteria) this;
        }

        public Criteria andDriverCardImgNotBetween(String value1, String value2) {
            addCriterion("driver_card_img not between", value1, value2, "driverCardImg");
            return (Criteria) this;
        }

        public Criteria andCarCardImgIsNull() {
            addCriterion("car_card_img is null");
            return (Criteria) this;
        }

        public Criteria andCarCardImgIsNotNull() {
            addCriterion("car_card_img is not null");
            return (Criteria) this;
        }

        public Criteria andCarCardImgEqualTo(String value) {
            addCriterion("car_card_img =", value, "carCardImg");
            return (Criteria) this;
        }

        public Criteria andCarCardImgNotEqualTo(String value) {
            addCriterion("car_card_img <>", value, "carCardImg");
            return (Criteria) this;
        }

        public Criteria andCarCardImgGreaterThan(String value) {
            addCriterion("car_card_img >", value, "carCardImg");
            return (Criteria) this;
        }

        public Criteria andCarCardImgGreaterThanOrEqualTo(String value) {
            addCriterion("car_card_img >=", value, "carCardImg");
            return (Criteria) this;
        }

        public Criteria andCarCardImgLessThan(String value) {
            addCriterion("car_card_img <", value, "carCardImg");
            return (Criteria) this;
        }

        public Criteria andCarCardImgLessThanOrEqualTo(String value) {
            addCriterion("car_card_img <=", value, "carCardImg");
            return (Criteria) this;
        }

        public Criteria andCarCardImgLike(String value) {
            addCriterion("car_card_img like", value, "carCardImg");
            return (Criteria) this;
        }

        public Criteria andCarCardImgNotLike(String value) {
            addCriterion("car_card_img not like", value, "carCardImg");
            return (Criteria) this;
        }

        public Criteria andCarCardImgIn(List<String> values) {
            addCriterion("car_card_img in", values, "carCardImg");
            return (Criteria) this;
        }

        public Criteria andCarCardImgNotIn(List<String> values) {
            addCriterion("car_card_img not in", values, "carCardImg");
            return (Criteria) this;
        }

        public Criteria andCarCardImgBetween(String value1, String value2) {
            addCriterion("car_card_img between", value1, value2, "carCardImg");
            return (Criteria) this;
        }

        public Criteria andCarCardImgNotBetween(String value1, String value2) {
            addCriterion("car_card_img not between", value1, value2, "carCardImg");
            return (Criteria) this;
        }

        public Criteria andEntryTimeIsNull() {
            addCriterion("entry_time is null");
            return (Criteria) this;
        }

        public Criteria andEntryTimeIsNotNull() {
            addCriterion("entry_time is not null");
            return (Criteria) this;
        }

        public Criteria andEntryTimeEqualTo(Date value) {
            addCriterion("entry_time =", value, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeNotEqualTo(Date value) {
            addCriterion("entry_time <>", value, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeGreaterThan(Date value) {
            addCriterion("entry_time >", value, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("entry_time >=", value, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeLessThan(Date value) {
            addCriterion("entry_time <", value, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeLessThanOrEqualTo(Date value) {
            addCriterion("entry_time <=", value, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeIn(List<Date> values) {
            addCriterion("entry_time in", values, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeNotIn(List<Date> values) {
            addCriterion("entry_time not in", values, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeBetween(Date value1, Date value2) {
            addCriterion("entry_time between", value1, value2, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeNotBetween(Date value1, Date value2) {
            addCriterion("entry_time not between", value1, value2, "entryTime");
            return (Criteria) this;
        }

        public Criteria andCheckFlogIsNull() {
            addCriterion("check_flog is null");
            return (Criteria) this;
        }

        public Criteria andCheckFlogIsNotNull() {
            addCriterion("check_flog is not null");
            return (Criteria) this;
        }

        public Criteria andCheckFlogEqualTo(Integer value) {
            addCriterion("check_flog =", value, "checkFlog");
            return (Criteria) this;
        }

        public Criteria andCheckFlogNotEqualTo(Integer value) {
            addCriterion("check_flog <>", value, "checkFlog");
            return (Criteria) this;
        }

        public Criteria andCheckFlogGreaterThan(Integer value) {
            addCriterion("check_flog >", value, "checkFlog");
            return (Criteria) this;
        }

        public Criteria andCheckFlogGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_flog >=", value, "checkFlog");
            return (Criteria) this;
        }

        public Criteria andCheckFlogLessThan(Integer value) {
            addCriterion("check_flog <", value, "checkFlog");
            return (Criteria) this;
        }

        public Criteria andCheckFlogLessThanOrEqualTo(Integer value) {
            addCriterion("check_flog <=", value, "checkFlog");
            return (Criteria) this;
        }

        public Criteria andCheckFlogIn(List<Integer> values) {
            addCriterion("check_flog in", values, "checkFlog");
            return (Criteria) this;
        }

        public Criteria andCheckFlogNotIn(List<Integer> values) {
            addCriterion("check_flog not in", values, "checkFlog");
            return (Criteria) this;
        }

        public Criteria andCheckFlogBetween(Integer value1, Integer value2) {
            addCriterion("check_flog between", value1, value2, "checkFlog");
            return (Criteria) this;
        }

        public Criteria andCheckFlogNotBetween(Integer value1, Integer value2) {
            addCriterion("check_flog not between", value1, value2, "checkFlog");
            return (Criteria) this;
        }

        public Criteria andDismissIsNull() {
            addCriterion("dismiss is null");
            return (Criteria) this;
        }

        public Criteria andDismissIsNotNull() {
            addCriterion("dismiss is not null");
            return (Criteria) this;
        }

        public Criteria andDismissEqualTo(String value) {
            addCriterion("dismiss =", value, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissNotEqualTo(String value) {
            addCriterion("dismiss <>", value, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissGreaterThan(String value) {
            addCriterion("dismiss >", value, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissGreaterThanOrEqualTo(String value) {
            addCriterion("dismiss >=", value, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissLessThan(String value) {
            addCriterion("dismiss <", value, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissLessThanOrEqualTo(String value) {
            addCriterion("dismiss <=", value, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissLike(String value) {
            addCriterion("dismiss like", value, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissNotLike(String value) {
            addCriterion("dismiss not like", value, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissIn(List<String> values) {
            addCriterion("dismiss in", values, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissNotIn(List<String> values) {
            addCriterion("dismiss not in", values, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissBetween(String value1, String value2) {
            addCriterion("dismiss between", value1, value2, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissNotBetween(String value1, String value2) {
            addCriterion("dismiss not between", value1, value2, "dismiss");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andCheckUseridIsNull() {
            addCriterion("check_userid is null");
            return (Criteria) this;
        }

        public Criteria andCheckUseridIsNotNull() {
            addCriterion("check_userid is not null");
            return (Criteria) this;
        }

        public Criteria andCheckUseridEqualTo(Integer value) {
            addCriterion("check_userid =", value, "checkUserid");
            return (Criteria) this;
        }

        public Criteria andCheckUseridNotEqualTo(Integer value) {
            addCriterion("check_userid <>", value, "checkUserid");
            return (Criteria) this;
        }

        public Criteria andCheckUseridGreaterThan(Integer value) {
            addCriterion("check_userid >", value, "checkUserid");
            return (Criteria) this;
        }

        public Criteria andCheckUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("check_userid >=", value, "checkUserid");
            return (Criteria) this;
        }

        public Criteria andCheckUseridLessThan(Integer value) {
            addCriterion("check_userid <", value, "checkUserid");
            return (Criteria) this;
        }

        public Criteria andCheckUseridLessThanOrEqualTo(Integer value) {
            addCriterion("check_userid <=", value, "checkUserid");
            return (Criteria) this;
        }

        public Criteria andCheckUseridIn(List<Integer> values) {
            addCriterion("check_userid in", values, "checkUserid");
            return (Criteria) this;
        }

        public Criteria andCheckUseridNotIn(List<Integer> values) {
            addCriterion("check_userid not in", values, "checkUserid");
            return (Criteria) this;
        }

        public Criteria andCheckUseridBetween(Integer value1, Integer value2) {
            addCriterion("check_userid between", value1, value2, "checkUserid");
            return (Criteria) this;
        }

        public Criteria andCheckUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("check_userid not between", value1, value2, "checkUserid");
            return (Criteria) this;
        }

        public Criteria andChecktimeIsNull() {
            addCriterion("checktime is null");
            return (Criteria) this;
        }

        public Criteria andChecktimeIsNotNull() {
            addCriterion("checktime is not null");
            return (Criteria) this;
        }

        public Criteria andChecktimeEqualTo(Date value) {
            addCriterion("checktime =", value, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeNotEqualTo(Date value) {
            addCriterion("checktime <>", value, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeGreaterThan(Date value) {
            addCriterion("checktime >", value, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeGreaterThanOrEqualTo(Date value) {
            addCriterion("checktime >=", value, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeLessThan(Date value) {
            addCriterion("checktime <", value, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeLessThanOrEqualTo(Date value) {
            addCriterion("checktime <=", value, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeIn(List<Date> values) {
            addCriterion("checktime in", values, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeNotIn(List<Date> values) {
            addCriterion("checktime not in", values, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeBetween(Date value1, Date value2) {
            addCriterion("checktime between", value1, value2, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeNotBetween(Date value1, Date value2) {
            addCriterion("checktime not between", value1, value2, "checktime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_entry
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_entry
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}