package com.api.entity;

public class PwpLeague {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.league_name
     *
     * @mbg.generated
     */
    private String leagueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.domain
     *
     * @mbg.generated
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.website
     *
     * @mbg.generated
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.contact
     *
     * @mbg.generated
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.contact_phone
     *
     * @mbg.generated
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.league_type
     *
     * @mbg.generated
     */
    private Byte leagueType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.league_status
     *
     * @mbg.generated
     */
    private Byte leagueStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_league.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.id
     *
     * @return the value of pwp_league.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.id
     *
     * @param id the value for pwp_league.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.league_name
     *
     * @return the value of pwp_league.league_name
     *
     * @mbg.generated
     */
    public String getLeagueName() {
        return leagueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.league_name
     *
     * @param leagueName the value for pwp_league.league_name
     *
     * @mbg.generated
     */
    public void setLeagueName(String leagueName) {
        this.leagueName = leagueName == null ? null : leagueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.domain
     *
     * @return the value of pwp_league.domain
     *
     * @mbg.generated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.domain
     *
     * @param domain the value for pwp_league.domain
     *
     * @mbg.generated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.account
     *
     * @return the value of pwp_league.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.account
     *
     * @param account the value for pwp_league.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.password
     *
     * @return the value of pwp_league.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.password
     *
     * @param password the value for pwp_league.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.website
     *
     * @return the value of pwp_league.website
     *
     * @mbg.generated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.website
     *
     * @param website the value for pwp_league.website
     *
     * @mbg.generated
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.contact
     *
     * @return the value of pwp_league.contact
     *
     * @mbg.generated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.contact
     *
     * @param contact the value for pwp_league.contact
     *
     * @mbg.generated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.contact_phone
     *
     * @return the value of pwp_league.contact_phone
     *
     * @mbg.generated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.contact_phone
     *
     * @param contactPhone the value for pwp_league.contact_phone
     *
     * @mbg.generated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.league_type
     *
     * @return the value of pwp_league.league_type
     *
     * @mbg.generated
     */
    public Byte getLeagueType() {
        return leagueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.league_type
     *
     * @param leagueType the value for pwp_league.league_type
     *
     * @mbg.generated
     */
    public void setLeagueType(Byte leagueType) {
        this.leagueType = leagueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.address
     *
     * @return the value of pwp_league.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.address
     *
     * @param address the value for pwp_league.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.logo
     *
     * @return the value of pwp_league.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.logo
     *
     * @param logo the value for pwp_league.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.league_status
     *
     * @return the value of pwp_league.league_status
     *
     * @mbg.generated
     */
    public Byte getLeagueStatus() {
        return leagueStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.league_status
     *
     * @param leagueStatus the value for pwp_league.league_status
     *
     * @mbg.generated
     */
    public void setLeagueStatus(Byte leagueStatus) {
        this.leagueStatus = leagueStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.create_time
     *
     * @return the value of pwp_league.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.create_time
     *
     * @param createTime the value for pwp_league.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_league.update_time
     *
     * @return the value of pwp_league.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_league.update_time
     *
     * @param updateTime the value for pwp_league.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}