package com.api.entity;

import java.math.BigDecimal;

public class PwpMemberTrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.trade_no
     *
     * @mbg.generated
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.member_id
     *
     * @mbg.generated
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.member_detail_id
     *
     * @mbg.generated
     */
    private Integer memberDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.member_p_card_id
     *
     * @mbg.generated
     */
    private Integer memberPCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.car_num
     *
     * @mbg.generated
     */
    private String carNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.member_external_account
     *
     * @mbg.generated
     */
    private String memberExternalAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.trade_amount
     *
     * @mbg.generated
     */
    private BigDecimal tradeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.balance
     *
     * @mbg.generated
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.trade_type
     *
     * @mbg.generated
     */
    private Byte tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.trade_result
     *
     * @mbg.generated
     */
    private Byte tradeResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.create_date
     *
     * @mbg.generated
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.sync_time
     *
     * @mbg.generated
     */
    private String syncTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.sync_result
     *
     * @mbg.generated
     */
    private Byte syncResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.park_id_java
     *
     * @mbg.generated
     */
    private Integer parkIdJava;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pwp_member_trade.billing_account_id
     *
     * @mbg.generated
     */
    private Integer billingAccountId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.id
     *
     * @return the value of pwp_member_trade.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.id
     *
     * @param id the value for pwp_member_trade.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.trade_no
     *
     * @return the value of pwp_member_trade.trade_no
     *
     * @mbg.generated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.trade_no
     *
     * @param tradeNo the value for pwp_member_trade.trade_no
     *
     * @mbg.generated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.member_id
     *
     * @return the value of pwp_member_trade.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.member_id
     *
     * @param memberId the value for pwp_member_trade.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.member_detail_id
     *
     * @return the value of pwp_member_trade.member_detail_id
     *
     * @mbg.generated
     */
    public Integer getMemberDetailId() {
        return memberDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.member_detail_id
     *
     * @param memberDetailId the value for pwp_member_trade.member_detail_id
     *
     * @mbg.generated
     */
    public void setMemberDetailId(Integer memberDetailId) {
        this.memberDetailId = memberDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.member_p_card_id
     *
     * @return the value of pwp_member_trade.member_p_card_id
     *
     * @mbg.generated
     */
    public Integer getMemberPCardId() {
        return memberPCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.member_p_card_id
     *
     * @param memberPCardId the value for pwp_member_trade.member_p_card_id
     *
     * @mbg.generated
     */
    public void setMemberPCardId(Integer memberPCardId) {
        this.memberPCardId = memberPCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.car_num
     *
     * @return the value of pwp_member_trade.car_num
     *
     * @mbg.generated
     */
    public String getCarNum() {
        return carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.car_num
     *
     * @param carNum the value for pwp_member_trade.car_num
     *
     * @mbg.generated
     */
    public void setCarNum(String carNum) {
        this.carNum = carNum == null ? null : carNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.member_external_account
     *
     * @return the value of pwp_member_trade.member_external_account
     *
     * @mbg.generated
     */
    public String getMemberExternalAccount() {
        return memberExternalAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.member_external_account
     *
     * @param memberExternalAccount the value for pwp_member_trade.member_external_account
     *
     * @mbg.generated
     */
    public void setMemberExternalAccount(String memberExternalAccount) {
        this.memberExternalAccount = memberExternalAccount == null ? null : memberExternalAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.park_id
     *
     * @return the value of pwp_member_trade.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.park_id
     *
     * @param parkId the value for pwp_member_trade.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.trade_amount
     *
     * @return the value of pwp_member_trade.trade_amount
     *
     * @mbg.generated
     */
    public BigDecimal getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.trade_amount
     *
     * @param tradeAmount the value for pwp_member_trade.trade_amount
     *
     * @mbg.generated
     */
    public void setTradeAmount(BigDecimal tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.balance
     *
     * @return the value of pwp_member_trade.balance
     *
     * @mbg.generated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.balance
     *
     * @param balance the value for pwp_member_trade.balance
     *
     * @mbg.generated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.trade_type
     *
     * @return the value of pwp_member_trade.trade_type
     *
     * @mbg.generated
     */
    public Byte getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.trade_type
     *
     * @param tradeType the value for pwp_member_trade.trade_type
     *
     * @mbg.generated
     */
    public void setTradeType(Byte tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.trade_result
     *
     * @return the value of pwp_member_trade.trade_result
     *
     * @mbg.generated
     */
    public Byte getTradeResult() {
        return tradeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.trade_result
     *
     * @param tradeResult the value for pwp_member_trade.trade_result
     *
     * @mbg.generated
     */
    public void setTradeResult(Byte tradeResult) {
        this.tradeResult = tradeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.create_time
     *
     * @return the value of pwp_member_trade.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.create_time
     *
     * @param createTime the value for pwp_member_trade.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.create_date
     *
     * @return the value of pwp_member_trade.create_date
     *
     * @mbg.generated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.create_date
     *
     * @param createDate the value for pwp_member_trade.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.update_time
     *
     * @return the value of pwp_member_trade.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.update_time
     *
     * @param updateTime the value for pwp_member_trade.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.sync_time
     *
     * @return the value of pwp_member_trade.sync_time
     *
     * @mbg.generated
     */
    public String getSyncTime() {
        return syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.sync_time
     *
     * @param syncTime the value for pwp_member_trade.sync_time
     *
     * @mbg.generated
     */
    public void setSyncTime(String syncTime) {
        this.syncTime = syncTime == null ? null : syncTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.sync_result
     *
     * @return the value of pwp_member_trade.sync_result
     *
     * @mbg.generated
     */
    public Byte getSyncResult() {
        return syncResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.sync_result
     *
     * @param syncResult the value for pwp_member_trade.sync_result
     *
     * @mbg.generated
     */
    public void setSyncResult(Byte syncResult) {
        this.syncResult = syncResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.park_id_java
     *
     * @return the value of pwp_member_trade.park_id_java
     *
     * @mbg.generated
     */
    public Integer getParkIdJava() {
        return parkIdJava;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.park_id_java
     *
     * @param parkIdJava the value for pwp_member_trade.park_id_java
     *
     * @mbg.generated
     */
    public void setParkIdJava(Integer parkIdJava) {
        this.parkIdJava = parkIdJava;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pwp_member_trade.billing_account_id
     *
     * @return the value of pwp_member_trade.billing_account_id
     *
     * @mbg.generated
     */
    public Integer getBillingAccountId() {
        return billingAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pwp_member_trade.billing_account_id
     *
     * @param billingAccountId the value for pwp_member_trade.billing_account_id
     *
     * @mbg.generated
     */
    public void setBillingAccountId(Integer billingAccountId) {
        this.billingAccountId = billingAccountId;
    }
}