package com.api.entity;

public class TBindingParking {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.parking_no
     *
     * @mbg.generated
     */
    private Integer parkingNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.car_type
     *
     * @mbg.generated
     */
    private Integer carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.is_sync
     *
     * @mbg.generated
     */
    private Integer isSync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.park_car_name
     *
     * @mbg.generated
     */
    private String parkCarName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.begin_date
     *
     * @mbg.generated
     */
    private String beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.binding_name
     *
     * @mbg.generated
     */
    private String bindingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.end_date
     *
     * @mbg.generated
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.pay_rule
     *
     * @mbg.generated
     */
    private Integer payRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.is_use
     *
     * @mbg.generated
     */
    private Integer isUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.car_plate
     *
     * @mbg.generated
     */
    private String carPlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.park_code
     *
     * @mbg.generated
     */
    private String parkCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_binding_parking.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.id
     *
     * @return the value of t_binding_parking.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.id
     *
     * @param id the value for t_binding_parking.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.park_id
     *
     * @return the value of t_binding_parking.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.park_id
     *
     * @param parkId the value for t_binding_parking.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.parking_no
     *
     * @return the value of t_binding_parking.parking_no
     *
     * @mbg.generated
     */
    public Integer getParkingNo() {
        return parkingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.parking_no
     *
     * @param parkingNo the value for t_binding_parking.parking_no
     *
     * @mbg.generated
     */
    public void setParkingNo(Integer parkingNo) {
        this.parkingNo = parkingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.car_type
     *
     * @return the value of t_binding_parking.car_type
     *
     * @mbg.generated
     */
    public Integer getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.car_type
     *
     * @param carType the value for t_binding_parking.car_type
     *
     * @mbg.generated
     */
    public void setCarType(Integer carType) {
        this.carType = carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.is_sync
     *
     * @return the value of t_binding_parking.is_sync
     *
     * @mbg.generated
     */
    public Integer getIsSync() {
        return isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.is_sync
     *
     * @param isSync the value for t_binding_parking.is_sync
     *
     * @mbg.generated
     */
    public void setIsSync(Integer isSync) {
        this.isSync = isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.park_car_name
     *
     * @return the value of t_binding_parking.park_car_name
     *
     * @mbg.generated
     */
    public String getParkCarName() {
        return parkCarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.park_car_name
     *
     * @param parkCarName the value for t_binding_parking.park_car_name
     *
     * @mbg.generated
     */
    public void setParkCarName(String parkCarName) {
        this.parkCarName = parkCarName == null ? null : parkCarName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.company_id
     *
     * @return the value of t_binding_parking.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.company_id
     *
     * @param companyId the value for t_binding_parking.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.status
     *
     * @return the value of t_binding_parking.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.status
     *
     * @param status the value for t_binding_parking.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.begin_date
     *
     * @return the value of t_binding_parking.begin_date
     *
     * @mbg.generated
     */
    public String getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.begin_date
     *
     * @param beginDate the value for t_binding_parking.begin_date
     *
     * @mbg.generated
     */
    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate == null ? null : beginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.binding_name
     *
     * @return the value of t_binding_parking.binding_name
     *
     * @mbg.generated
     */
    public String getBindingName() {
        return bindingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.binding_name
     *
     * @param bindingName the value for t_binding_parking.binding_name
     *
     * @mbg.generated
     */
    public void setBindingName(String bindingName) {
        this.bindingName = bindingName == null ? null : bindingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.end_date
     *
     * @return the value of t_binding_parking.end_date
     *
     * @mbg.generated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.end_date
     *
     * @param endDate the value for t_binding_parking.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.pay_rule
     *
     * @return the value of t_binding_parking.pay_rule
     *
     * @mbg.generated
     */
    public Integer getPayRule() {
        return payRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.pay_rule
     *
     * @param payRule the value for t_binding_parking.pay_rule
     *
     * @mbg.generated
     */
    public void setPayRule(Integer payRule) {
        this.payRule = payRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.is_use
     *
     * @return the value of t_binding_parking.is_use
     *
     * @mbg.generated
     */
    public Integer getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.is_use
     *
     * @param isUse the value for t_binding_parking.is_use
     *
     * @mbg.generated
     */
    public void setIsUse(Integer isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.car_plate
     *
     * @return the value of t_binding_parking.car_plate
     *
     * @mbg.generated
     */
    public String getCarPlate() {
        return carPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.car_plate
     *
     * @param carPlate the value for t_binding_parking.car_plate
     *
     * @mbg.generated
     */
    public void setCarPlate(String carPlate) {
        this.carPlate = carPlate == null ? null : carPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.park_code
     *
     * @return the value of t_binding_parking.park_code
     *
     * @mbg.generated
     */
    public String getParkCode() {
        return parkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.park_code
     *
     * @param parkCode the value for t_binding_parking.park_code
     *
     * @mbg.generated
     */
    public void setParkCode(String parkCode) {
        this.parkCode = parkCode == null ? null : parkCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_binding_parking.remark
     *
     * @return the value of t_binding_parking.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_binding_parking.remark
     *
     * @param remark the value for t_binding_parking.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}