package com.api.entity;

public class TCarPayRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_pay_rule.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_pay_rule.day_fee
     *
     * @mbg.generated
     */
    private Double dayFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_pay_rule.month_fee
     *
     * @mbg.generated
     */
    private Double monthFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_pay_rule.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_pay_rule.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_pay_rule.rule_name
     *
     * @mbg.generated
     */
    private String ruleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_pay_rule.season_fee
     *
     * @mbg.generated
     */
    private Long seasonFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_pay_rule.year_fee
     *
     * @mbg.generated
     */
    private Double yearFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_pay_rule.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_pay_rule.daily_start_time
     *
     * @mbg.generated
     */
    private String dailyStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_pay_rule.daily_end_time
     *
     * @mbg.generated
     */
    private String dailyEndTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_pay_rule.id
     *
     * @return the value of t_car_pay_rule.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_pay_rule.id
     *
     * @param id the value for t_car_pay_rule.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_pay_rule.day_fee
     *
     * @return the value of t_car_pay_rule.day_fee
     *
     * @mbg.generated
     */
    public Double getDayFee() {
        return dayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_pay_rule.day_fee
     *
     * @param dayFee the value for t_car_pay_rule.day_fee
     *
     * @mbg.generated
     */
    public void setDayFee(Double dayFee) {
        this.dayFee = dayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_pay_rule.month_fee
     *
     * @return the value of t_car_pay_rule.month_fee
     *
     * @mbg.generated
     */
    public Double getMonthFee() {
        return monthFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_pay_rule.month_fee
     *
     * @param monthFee the value for t_car_pay_rule.month_fee
     *
     * @mbg.generated
     */
    public void setMonthFee(Double monthFee) {
        this.monthFee = monthFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_pay_rule.park_id
     *
     * @return the value of t_car_pay_rule.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_pay_rule.park_id
     *
     * @param parkId the value for t_car_pay_rule.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_pay_rule.remark
     *
     * @return the value of t_car_pay_rule.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_pay_rule.remark
     *
     * @param remark the value for t_car_pay_rule.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_pay_rule.rule_name
     *
     * @return the value of t_car_pay_rule.rule_name
     *
     * @mbg.generated
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_pay_rule.rule_name
     *
     * @param ruleName the value for t_car_pay_rule.rule_name
     *
     * @mbg.generated
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_pay_rule.season_fee
     *
     * @return the value of t_car_pay_rule.season_fee
     *
     * @mbg.generated
     */
    public Long getSeasonFee() {
        return seasonFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_pay_rule.season_fee
     *
     * @param seasonFee the value for t_car_pay_rule.season_fee
     *
     * @mbg.generated
     */
    public void setSeasonFee(Long seasonFee) {
        this.seasonFee = seasonFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_pay_rule.year_fee
     *
     * @return the value of t_car_pay_rule.year_fee
     *
     * @mbg.generated
     */
    public Double getYearFee() {
        return yearFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_pay_rule.year_fee
     *
     * @param yearFee the value for t_car_pay_rule.year_fee
     *
     * @mbg.generated
     */
    public void setYearFee(Double yearFee) {
        this.yearFee = yearFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_pay_rule.company_id
     *
     * @return the value of t_car_pay_rule.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_pay_rule.company_id
     *
     * @param companyId the value for t_car_pay_rule.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_pay_rule.daily_start_time
     *
     * @return the value of t_car_pay_rule.daily_start_time
     *
     * @mbg.generated
     */
    public String getDailyStartTime() {
        return dailyStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_pay_rule.daily_start_time
     *
     * @param dailyStartTime the value for t_car_pay_rule.daily_start_time
     *
     * @mbg.generated
     */
    public void setDailyStartTime(String dailyStartTime) {
        this.dailyStartTime = dailyStartTime == null ? null : dailyStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_pay_rule.daily_end_time
     *
     * @return the value of t_car_pay_rule.daily_end_time
     *
     * @mbg.generated
     */
    public String getDailyEndTime() {
        return dailyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_pay_rule.daily_end_time
     *
     * @param dailyEndTime the value for t_car_pay_rule.daily_end_time
     *
     * @mbg.generated
     */
    public void setDailyEndTime(String dailyEndTime) {
        this.dailyEndTime = dailyEndTime == null ? null : dailyEndTime.trim();
    }
}