package com.api.entity;

import java.util.ArrayList;
import java.util.List;

public class TChargeRuleCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    public TChargeRuleCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBaseTime1IsNull() {
            addCriterion("base_time1 is null");
            return (Criteria) this;
        }

        public Criteria andBaseTime1IsNotNull() {
            addCriterion("base_time1 is not null");
            return (Criteria) this;
        }

        public Criteria andBaseTime1EqualTo(Integer value) {
            addCriterion("base_time1 =", value, "baseTime1");
            return (Criteria) this;
        }

        public Criteria andBaseTime1NotEqualTo(Integer value) {
            addCriterion("base_time1 <>", value, "baseTime1");
            return (Criteria) this;
        }

        public Criteria andBaseTime1GreaterThan(Integer value) {
            addCriterion("base_time1 >", value, "baseTime1");
            return (Criteria) this;
        }

        public Criteria andBaseTime1GreaterThanOrEqualTo(Integer value) {
            addCriterion("base_time1 >=", value, "baseTime1");
            return (Criteria) this;
        }

        public Criteria andBaseTime1LessThan(Integer value) {
            addCriterion("base_time1 <", value, "baseTime1");
            return (Criteria) this;
        }

        public Criteria andBaseTime1LessThanOrEqualTo(Integer value) {
            addCriterion("base_time1 <=", value, "baseTime1");
            return (Criteria) this;
        }

        public Criteria andBaseTime1In(List<Integer> values) {
            addCriterion("base_time1 in", values, "baseTime1");
            return (Criteria) this;
        }

        public Criteria andBaseTime1NotIn(List<Integer> values) {
            addCriterion("base_time1 not in", values, "baseTime1");
            return (Criteria) this;
        }

        public Criteria andBaseTime1Between(Integer value1, Integer value2) {
            addCriterion("base_time1 between", value1, value2, "baseTime1");
            return (Criteria) this;
        }

        public Criteria andBaseTime1NotBetween(Integer value1, Integer value2) {
            addCriterion("base_time1 not between", value1, value2, "baseTime1");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeIsNull() {
            addCriterion("base_time1_fee is null");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeIsNotNull() {
            addCriterion("base_time1_fee is not null");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeEqualTo(String value) {
            addCriterion("base_time1_fee =", value, "baseTime1Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeNotEqualTo(String value) {
            addCriterion("base_time1_fee <>", value, "baseTime1Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeGreaterThan(String value) {
            addCriterion("base_time1_fee >", value, "baseTime1Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeGreaterThanOrEqualTo(String value) {
            addCriterion("base_time1_fee >=", value, "baseTime1Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeLessThan(String value) {
            addCriterion("base_time1_fee <", value, "baseTime1Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeLessThanOrEqualTo(String value) {
            addCriterion("base_time1_fee <=", value, "baseTime1Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeLike(String value) {
            addCriterion("base_time1_fee like", value, "baseTime1Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeNotLike(String value) {
            addCriterion("base_time1_fee not like", value, "baseTime1Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeIn(List<String> values) {
            addCriterion("base_time1_fee in", values, "baseTime1Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeNotIn(List<String> values) {
            addCriterion("base_time1_fee not in", values, "baseTime1Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeBetween(String value1, String value2) {
            addCriterion("base_time1_fee between", value1, value2, "baseTime1Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime1FeeNotBetween(String value1, String value2) {
            addCriterion("base_time1_fee not between", value1, value2, "baseTime1Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime2IsNull() {
            addCriterion("base_time2 is null");
            return (Criteria) this;
        }

        public Criteria andBaseTime2IsNotNull() {
            addCriterion("base_time2 is not null");
            return (Criteria) this;
        }

        public Criteria andBaseTime2EqualTo(Integer value) {
            addCriterion("base_time2 =", value, "baseTime2");
            return (Criteria) this;
        }

        public Criteria andBaseTime2NotEqualTo(Integer value) {
            addCriterion("base_time2 <>", value, "baseTime2");
            return (Criteria) this;
        }

        public Criteria andBaseTime2GreaterThan(Integer value) {
            addCriterion("base_time2 >", value, "baseTime2");
            return (Criteria) this;
        }

        public Criteria andBaseTime2GreaterThanOrEqualTo(Integer value) {
            addCriterion("base_time2 >=", value, "baseTime2");
            return (Criteria) this;
        }

        public Criteria andBaseTime2LessThan(Integer value) {
            addCriterion("base_time2 <", value, "baseTime2");
            return (Criteria) this;
        }

        public Criteria andBaseTime2LessThanOrEqualTo(Integer value) {
            addCriterion("base_time2 <=", value, "baseTime2");
            return (Criteria) this;
        }

        public Criteria andBaseTime2In(List<Integer> values) {
            addCriterion("base_time2 in", values, "baseTime2");
            return (Criteria) this;
        }

        public Criteria andBaseTime2NotIn(List<Integer> values) {
            addCriterion("base_time2 not in", values, "baseTime2");
            return (Criteria) this;
        }

        public Criteria andBaseTime2Between(Integer value1, Integer value2) {
            addCriterion("base_time2 between", value1, value2, "baseTime2");
            return (Criteria) this;
        }

        public Criteria andBaseTime2NotBetween(Integer value1, Integer value2) {
            addCriterion("base_time2 not between", value1, value2, "baseTime2");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeIsNull() {
            addCriterion("base_time2_fee is null");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeIsNotNull() {
            addCriterion("base_time2_fee is not null");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeEqualTo(String value) {
            addCriterion("base_time2_fee =", value, "baseTime2Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeNotEqualTo(String value) {
            addCriterion("base_time2_fee <>", value, "baseTime2Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeGreaterThan(String value) {
            addCriterion("base_time2_fee >", value, "baseTime2Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeGreaterThanOrEqualTo(String value) {
            addCriterion("base_time2_fee >=", value, "baseTime2Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeLessThan(String value) {
            addCriterion("base_time2_fee <", value, "baseTime2Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeLessThanOrEqualTo(String value) {
            addCriterion("base_time2_fee <=", value, "baseTime2Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeLike(String value) {
            addCriterion("base_time2_fee like", value, "baseTime2Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeNotLike(String value) {
            addCriterion("base_time2_fee not like", value, "baseTime2Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeIn(List<String> values) {
            addCriterion("base_time2_fee in", values, "baseTime2Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeNotIn(List<String> values) {
            addCriterion("base_time2_fee not in", values, "baseTime2Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeBetween(String value1, String value2) {
            addCriterion("base_time2_fee between", value1, value2, "baseTime2Fee");
            return (Criteria) this;
        }

        public Criteria andBaseTime2FeeNotBetween(String value1, String value2) {
            addCriterion("base_time2_fee not between", value1, value2, "baseTime2Fee");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdIsNull() {
            addCriterion("car_type_id is null");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdIsNotNull() {
            addCriterion("car_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdEqualTo(Integer value) {
            addCriterion("car_type_id =", value, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdNotEqualTo(Integer value) {
            addCriterion("car_type_id <>", value, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdGreaterThan(Integer value) {
            addCriterion("car_type_id >", value, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("car_type_id >=", value, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdLessThan(Integer value) {
            addCriterion("car_type_id <", value, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("car_type_id <=", value, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdIn(List<Integer> values) {
            addCriterion("car_type_id in", values, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdNotIn(List<Integer> values) {
            addCriterion("car_type_id not in", values, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("car_type_id between", value1, value2, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andCarTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("car_type_id not between", value1, value2, "carTypeId");
            return (Criteria) this;
        }

        public Criteria andFreeTimeIsNull() {
            addCriterion("free_time is null");
            return (Criteria) this;
        }

        public Criteria andFreeTimeIsNotNull() {
            addCriterion("free_time is not null");
            return (Criteria) this;
        }

        public Criteria andFreeTimeEqualTo(Integer value) {
            addCriterion("free_time =", value, "freeTime");
            return (Criteria) this;
        }

        public Criteria andFreeTimeNotEqualTo(Integer value) {
            addCriterion("free_time <>", value, "freeTime");
            return (Criteria) this;
        }

        public Criteria andFreeTimeGreaterThan(Integer value) {
            addCriterion("free_time >", value, "freeTime");
            return (Criteria) this;
        }

        public Criteria andFreeTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("free_time >=", value, "freeTime");
            return (Criteria) this;
        }

        public Criteria andFreeTimeLessThan(Integer value) {
            addCriterion("free_time <", value, "freeTime");
            return (Criteria) this;
        }

        public Criteria andFreeTimeLessThanOrEqualTo(Integer value) {
            addCriterion("free_time <=", value, "freeTime");
            return (Criteria) this;
        }

        public Criteria andFreeTimeIn(List<Integer> values) {
            addCriterion("free_time in", values, "freeTime");
            return (Criteria) this;
        }

        public Criteria andFreeTimeNotIn(List<Integer> values) {
            addCriterion("free_time not in", values, "freeTime");
            return (Criteria) this;
        }

        public Criteria andFreeTimeBetween(Integer value1, Integer value2) {
            addCriterion("free_time between", value1, value2, "freeTime");
            return (Criteria) this;
        }

        public Criteria andFreeTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("free_time not between", value1, value2, "freeTime");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeIsNull() {
            addCriterion("free_time_fee is null");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeIsNotNull() {
            addCriterion("free_time_fee is not null");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeEqualTo(String value) {
            addCriterion("free_time_fee =", value, "freeTimeFee");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeNotEqualTo(String value) {
            addCriterion("free_time_fee <>", value, "freeTimeFee");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeGreaterThan(String value) {
            addCriterion("free_time_fee >", value, "freeTimeFee");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeGreaterThanOrEqualTo(String value) {
            addCriterion("free_time_fee >=", value, "freeTimeFee");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeLessThan(String value) {
            addCriterion("free_time_fee <", value, "freeTimeFee");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeLessThanOrEqualTo(String value) {
            addCriterion("free_time_fee <=", value, "freeTimeFee");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeLike(String value) {
            addCriterion("free_time_fee like", value, "freeTimeFee");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeNotLike(String value) {
            addCriterion("free_time_fee not like", value, "freeTimeFee");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeIn(List<String> values) {
            addCriterion("free_time_fee in", values, "freeTimeFee");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeNotIn(List<String> values) {
            addCriterion("free_time_fee not in", values, "freeTimeFee");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeBetween(String value1, String value2) {
            addCriterion("free_time_fee between", value1, value2, "freeTimeFee");
            return (Criteria) this;
        }

        public Criteria andFreeTimeFeeNotBetween(String value1, String value2) {
            addCriterion("free_time_fee not between", value1, value2, "freeTimeFee");
            return (Criteria) this;
        }

        public Criteria andH24RuleIsNull() {
            addCriterion("h24_rule is null");
            return (Criteria) this;
        }

        public Criteria andH24RuleIsNotNull() {
            addCriterion("h24_rule is not null");
            return (Criteria) this;
        }

        public Criteria andH24RuleEqualTo(Integer value) {
            addCriterion("h24_rule =", value, "h24Rule");
            return (Criteria) this;
        }

        public Criteria andH24RuleNotEqualTo(Integer value) {
            addCriterion("h24_rule <>", value, "h24Rule");
            return (Criteria) this;
        }

        public Criteria andH24RuleGreaterThan(Integer value) {
            addCriterion("h24_rule >", value, "h24Rule");
            return (Criteria) this;
        }

        public Criteria andH24RuleGreaterThanOrEqualTo(Integer value) {
            addCriterion("h24_rule >=", value, "h24Rule");
            return (Criteria) this;
        }

        public Criteria andH24RuleLessThan(Integer value) {
            addCriterion("h24_rule <", value, "h24Rule");
            return (Criteria) this;
        }

        public Criteria andH24RuleLessThanOrEqualTo(Integer value) {
            addCriterion("h24_rule <=", value, "h24Rule");
            return (Criteria) this;
        }

        public Criteria andH24RuleIn(List<Integer> values) {
            addCriterion("h24_rule in", values, "h24Rule");
            return (Criteria) this;
        }

        public Criteria andH24RuleNotIn(List<Integer> values) {
            addCriterion("h24_rule not in", values, "h24Rule");
            return (Criteria) this;
        }

        public Criteria andH24RuleBetween(Integer value1, Integer value2) {
            addCriterion("h24_rule between", value1, value2, "h24Rule");
            return (Criteria) this;
        }

        public Criteria andH24RuleNotBetween(Integer value1, Integer value2) {
            addCriterion("h24_rule not between", value1, value2, "h24Rule");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeIsNull() {
            addCriterion("h24_unit_time is null");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeIsNotNull() {
            addCriterion("h24_unit_time is not null");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeEqualTo(Integer value) {
            addCriterion("h24_unit_time =", value, "h24UnitTime");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeNotEqualTo(Integer value) {
            addCriterion("h24_unit_time <>", value, "h24UnitTime");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeGreaterThan(Integer value) {
            addCriterion("h24_unit_time >", value, "h24UnitTime");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("h24_unit_time >=", value, "h24UnitTime");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeLessThan(Integer value) {
            addCriterion("h24_unit_time <", value, "h24UnitTime");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeLessThanOrEqualTo(Integer value) {
            addCriterion("h24_unit_time <=", value, "h24UnitTime");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeIn(List<Integer> values) {
            addCriterion("h24_unit_time in", values, "h24UnitTime");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeNotIn(List<Integer> values) {
            addCriterion("h24_unit_time not in", values, "h24UnitTime");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeBetween(Integer value1, Integer value2) {
            addCriterion("h24_unit_time between", value1, value2, "h24UnitTime");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("h24_unit_time not between", value1, value2, "h24UnitTime");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeIsNull() {
            addCriterion("h24_unit_time_fee is null");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeIsNotNull() {
            addCriterion("h24_unit_time_fee is not null");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeEqualTo(String value) {
            addCriterion("h24_unit_time_fee =", value, "h24UnitTimeFee");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeNotEqualTo(String value) {
            addCriterion("h24_unit_time_fee <>", value, "h24UnitTimeFee");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeGreaterThan(String value) {
            addCriterion("h24_unit_time_fee >", value, "h24UnitTimeFee");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeGreaterThanOrEqualTo(String value) {
            addCriterion("h24_unit_time_fee >=", value, "h24UnitTimeFee");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeLessThan(String value) {
            addCriterion("h24_unit_time_fee <", value, "h24UnitTimeFee");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeLessThanOrEqualTo(String value) {
            addCriterion("h24_unit_time_fee <=", value, "h24UnitTimeFee");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeLike(String value) {
            addCriterion("h24_unit_time_fee like", value, "h24UnitTimeFee");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeNotLike(String value) {
            addCriterion("h24_unit_time_fee not like", value, "h24UnitTimeFee");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeIn(List<String> values) {
            addCriterion("h24_unit_time_fee in", values, "h24UnitTimeFee");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeNotIn(List<String> values) {
            addCriterion("h24_unit_time_fee not in", values, "h24UnitTimeFee");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeBetween(String value1, String value2) {
            addCriterion("h24_unit_time_fee between", value1, value2, "h24UnitTimeFee");
            return (Criteria) this;
        }

        public Criteria andH24UnitTimeFeeNotBetween(String value1, String value2) {
            addCriterion("h24_unit_time_fee not between", value1, value2, "h24UnitTimeFee");
            return (Criteria) this;
        }

        public Criteria andIsHolidayUseIsNull() {
            addCriterion("is_Holiday_Use is null");
            return (Criteria) this;
        }

        public Criteria andIsHolidayUseIsNotNull() {
            addCriterion("is_Holiday_Use is not null");
            return (Criteria) this;
        }

        public Criteria andIsHolidayUseEqualTo(Integer value) {
            addCriterion("is_Holiday_Use =", value, "isHolidayUse");
            return (Criteria) this;
        }

        public Criteria andIsHolidayUseNotEqualTo(Integer value) {
            addCriterion("is_Holiday_Use <>", value, "isHolidayUse");
            return (Criteria) this;
        }

        public Criteria andIsHolidayUseGreaterThan(Integer value) {
            addCriterion("is_Holiday_Use >", value, "isHolidayUse");
            return (Criteria) this;
        }

        public Criteria andIsHolidayUseGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_Holiday_Use >=", value, "isHolidayUse");
            return (Criteria) this;
        }

        public Criteria andIsHolidayUseLessThan(Integer value) {
            addCriterion("is_Holiday_Use <", value, "isHolidayUse");
            return (Criteria) this;
        }

        public Criteria andIsHolidayUseLessThanOrEqualTo(Integer value) {
            addCriterion("is_Holiday_Use <=", value, "isHolidayUse");
            return (Criteria) this;
        }

        public Criteria andIsHolidayUseIn(List<Integer> values) {
            addCriterion("is_Holiday_Use in", values, "isHolidayUse");
            return (Criteria) this;
        }

        public Criteria andIsHolidayUseNotIn(List<Integer> values) {
            addCriterion("is_Holiday_Use not in", values, "isHolidayUse");
            return (Criteria) this;
        }

        public Criteria andIsHolidayUseBetween(Integer value1, Integer value2) {
            addCriterion("is_Holiday_Use between", value1, value2, "isHolidayUse");
            return (Criteria) this;
        }

        public Criteria andIsHolidayUseNotBetween(Integer value1, Integer value2) {
            addCriterion("is_Holiday_Use not between", value1, value2, "isHolidayUse");
            return (Criteria) this;
        }

        public Criteria andIsMaxSectimeFeeByAddIsNull() {
            addCriterion("is_max_sectime_fee_by_add is null");
            return (Criteria) this;
        }

        public Criteria andIsMaxSectimeFeeByAddIsNotNull() {
            addCriterion("is_max_sectime_fee_by_add is not null");
            return (Criteria) this;
        }

        public Criteria andIsMaxSectimeFeeByAddEqualTo(Integer value) {
            addCriterion("is_max_sectime_fee_by_add =", value, "isMaxSectimeFeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMaxSectimeFeeByAddNotEqualTo(Integer value) {
            addCriterion("is_max_sectime_fee_by_add <>", value, "isMaxSectimeFeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMaxSectimeFeeByAddGreaterThan(Integer value) {
            addCriterion("is_max_sectime_fee_by_add >", value, "isMaxSectimeFeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMaxSectimeFeeByAddGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_max_sectime_fee_by_add >=", value, "isMaxSectimeFeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMaxSectimeFeeByAddLessThan(Integer value) {
            addCriterion("is_max_sectime_fee_by_add <", value, "isMaxSectimeFeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMaxSectimeFeeByAddLessThanOrEqualTo(Integer value) {
            addCriterion("is_max_sectime_fee_by_add <=", value, "isMaxSectimeFeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMaxSectimeFeeByAddIn(List<Integer> values) {
            addCriterion("is_max_sectime_fee_by_add in", values, "isMaxSectimeFeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMaxSectimeFeeByAddNotIn(List<Integer> values) {
            addCriterion("is_max_sectime_fee_by_add not in", values, "isMaxSectimeFeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMaxSectimeFeeByAddBetween(Integer value1, Integer value2) {
            addCriterion("is_max_sectime_fee_by_add between", value1, value2, "isMaxSectimeFeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMaxSectimeFeeByAddNotBetween(Integer value1, Integer value2) {
            addCriterion("is_max_sectime_fee_by_add not between", value1, value2, "isMaxSectimeFeeByAdd");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeIsNull() {
            addCriterion("max_day1_fee is null");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeIsNotNull() {
            addCriterion("max_day1_fee is not null");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeEqualTo(String value) {
            addCriterion("max_day1_fee =", value, "maxDay1Fee");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeNotEqualTo(String value) {
            addCriterion("max_day1_fee <>", value, "maxDay1Fee");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeGreaterThan(String value) {
            addCriterion("max_day1_fee >", value, "maxDay1Fee");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeGreaterThanOrEqualTo(String value) {
            addCriterion("max_day1_fee >=", value, "maxDay1Fee");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeLessThan(String value) {
            addCriterion("max_day1_fee <", value, "maxDay1Fee");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeLessThanOrEqualTo(String value) {
            addCriterion("max_day1_fee <=", value, "maxDay1Fee");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeLike(String value) {
            addCriterion("max_day1_fee like", value, "maxDay1Fee");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeNotLike(String value) {
            addCriterion("max_day1_fee not like", value, "maxDay1Fee");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeIn(List<String> values) {
            addCriterion("max_day1_fee in", values, "maxDay1Fee");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeNotIn(List<String> values) {
            addCriterion("max_day1_fee not in", values, "maxDay1Fee");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeBetween(String value1, String value2) {
            addCriterion("max_day1_fee between", value1, value2, "maxDay1Fee");
            return (Criteria) this;
        }

        public Criteria andMaxDay1FeeNotBetween(String value1, String value2) {
            addCriterion("max_day1_fee not between", value1, value2, "maxDay1Fee");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeIsNull() {
            addCriterion("max_dayn_fee is null");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeIsNotNull() {
            addCriterion("max_dayn_fee is not null");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeEqualTo(String value) {
            addCriterion("max_dayn_fee =", value, "maxDaynFee");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeNotEqualTo(String value) {
            addCriterion("max_dayn_fee <>", value, "maxDaynFee");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeGreaterThan(String value) {
            addCriterion("max_dayn_fee >", value, "maxDaynFee");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeGreaterThanOrEqualTo(String value) {
            addCriterion("max_dayn_fee >=", value, "maxDaynFee");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeLessThan(String value) {
            addCriterion("max_dayn_fee <", value, "maxDaynFee");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeLessThanOrEqualTo(String value) {
            addCriterion("max_dayn_fee <=", value, "maxDaynFee");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeLike(String value) {
            addCriterion("max_dayn_fee like", value, "maxDaynFee");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeNotLike(String value) {
            addCriterion("max_dayn_fee not like", value, "maxDaynFee");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeIn(List<String> values) {
            addCriterion("max_dayn_fee in", values, "maxDaynFee");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeNotIn(List<String> values) {
            addCriterion("max_dayn_fee not in", values, "maxDaynFee");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeBetween(String value1, String value2) {
            addCriterion("max_dayn_fee between", value1, value2, "maxDaynFee");
            return (Criteria) this;
        }

        public Criteria andMaxDaynFeeNotBetween(String value1, String value2) {
            addCriterion("max_dayn_fee not between", value1, value2, "maxDaynFee");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeIsNull() {
            addCriterion("max_sectime_fee is null");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeIsNotNull() {
            addCriterion("max_sectime_fee is not null");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeEqualTo(String value) {
            addCriterion("max_sectime_fee =", value, "maxSectimeFee");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeNotEqualTo(String value) {
            addCriterion("max_sectime_fee <>", value, "maxSectimeFee");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeGreaterThan(String value) {
            addCriterion("max_sectime_fee >", value, "maxSectimeFee");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeGreaterThanOrEqualTo(String value) {
            addCriterion("max_sectime_fee >=", value, "maxSectimeFee");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeLessThan(String value) {
            addCriterion("max_sectime_fee <", value, "maxSectimeFee");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeLessThanOrEqualTo(String value) {
            addCriterion("max_sectime_fee <=", value, "maxSectimeFee");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeLike(String value) {
            addCriterion("max_sectime_fee like", value, "maxSectimeFee");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeNotLike(String value) {
            addCriterion("max_sectime_fee not like", value, "maxSectimeFee");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeIn(List<String> values) {
            addCriterion("max_sectime_fee in", values, "maxSectimeFee");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeNotIn(List<String> values) {
            addCriterion("max_sectime_fee not in", values, "maxSectimeFee");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeBetween(String value1, String value2) {
            addCriterion("max_sectime_fee between", value1, value2, "maxSectimeFee");
            return (Criteria) this;
        }

        public Criteria andMaxSectimeFeeNotBetween(String value1, String value2) {
            addCriterion("max_sectime_fee not between", value1, value2, "maxSectimeFee");
            return (Criteria) this;
        }

        public Criteria andParkIdIsNull() {
            addCriterion("park_id is null");
            return (Criteria) this;
        }

        public Criteria andParkIdIsNotNull() {
            addCriterion("park_id is not null");
            return (Criteria) this;
        }

        public Criteria andParkIdEqualTo(Integer value) {
            addCriterion("park_id =", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotEqualTo(Integer value) {
            addCriterion("park_id <>", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdGreaterThan(Integer value) {
            addCriterion("park_id >", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("park_id >=", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdLessThan(Integer value) {
            addCriterion("park_id <", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdLessThanOrEqualTo(Integer value) {
            addCriterion("park_id <=", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdIn(List<Integer> values) {
            addCriterion("park_id in", values, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotIn(List<Integer> values) {
            addCriterion("park_id not in", values, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdBetween(Integer value1, Integer value2) {
            addCriterion("park_id between", value1, value2, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("park_id not between", value1, value2, "parkId");
            return (Criteria) this;
        }

        public Criteria andSurpassTimeIsNull() {
            addCriterion("surpass_time is null");
            return (Criteria) this;
        }

        public Criteria andSurpassTimeIsNotNull() {
            addCriterion("surpass_time is not null");
            return (Criteria) this;
        }

        public Criteria andSurpassTimeEqualTo(Integer value) {
            addCriterion("surpass_time =", value, "surpassTime");
            return (Criteria) this;
        }

        public Criteria andSurpassTimeNotEqualTo(Integer value) {
            addCriterion("surpass_time <>", value, "surpassTime");
            return (Criteria) this;
        }

        public Criteria andSurpassTimeGreaterThan(Integer value) {
            addCriterion("surpass_time >", value, "surpassTime");
            return (Criteria) this;
        }

        public Criteria andSurpassTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("surpass_time >=", value, "surpassTime");
            return (Criteria) this;
        }

        public Criteria andSurpassTimeLessThan(Integer value) {
            addCriterion("surpass_time <", value, "surpassTime");
            return (Criteria) this;
        }

        public Criteria andSurpassTimeLessThanOrEqualTo(Integer value) {
            addCriterion("surpass_time <=", value, "surpassTime");
            return (Criteria) this;
        }

        public Criteria andSurpassTimeIn(List<Integer> values) {
            addCriterion("surpass_time in", values, "surpassTime");
            return (Criteria) this;
        }

        public Criteria andSurpassTimeNotIn(List<Integer> values) {
            addCriterion("surpass_time not in", values, "surpassTime");
            return (Criteria) this;
        }

        public Criteria andSurpassTimeBetween(Integer value1, Integer value2) {
            addCriterion("surpass_time between", value1, value2, "surpassTime");
            return (Criteria) this;
        }

        public Criteria andSurpassTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("surpass_time not between", value1, value2, "surpassTime");
            return (Criteria) this;
        }

        public Criteria andTimesecEndIsNull() {
            addCriterion("timesec_end is null");
            return (Criteria) this;
        }

        public Criteria andTimesecEndIsNotNull() {
            addCriterion("timesec_end is not null");
            return (Criteria) this;
        }

        public Criteria andTimesecEndEqualTo(String value) {
            addCriterion("timesec_end =", value, "timesecEnd");
            return (Criteria) this;
        }

        public Criteria andTimesecEndNotEqualTo(String value) {
            addCriterion("timesec_end <>", value, "timesecEnd");
            return (Criteria) this;
        }

        public Criteria andTimesecEndGreaterThan(String value) {
            addCriterion("timesec_end >", value, "timesecEnd");
            return (Criteria) this;
        }

        public Criteria andTimesecEndGreaterThanOrEqualTo(String value) {
            addCriterion("timesec_end >=", value, "timesecEnd");
            return (Criteria) this;
        }

        public Criteria andTimesecEndLessThan(String value) {
            addCriterion("timesec_end <", value, "timesecEnd");
            return (Criteria) this;
        }

        public Criteria andTimesecEndLessThanOrEqualTo(String value) {
            addCriterion("timesec_end <=", value, "timesecEnd");
            return (Criteria) this;
        }

        public Criteria andTimesecEndLike(String value) {
            addCriterion("timesec_end like", value, "timesecEnd");
            return (Criteria) this;
        }

        public Criteria andTimesecEndNotLike(String value) {
            addCriterion("timesec_end not like", value, "timesecEnd");
            return (Criteria) this;
        }

        public Criteria andTimesecEndIn(List<String> values) {
            addCriterion("timesec_end in", values, "timesecEnd");
            return (Criteria) this;
        }

        public Criteria andTimesecEndNotIn(List<String> values) {
            addCriterion("timesec_end not in", values, "timesecEnd");
            return (Criteria) this;
        }

        public Criteria andTimesecEndBetween(String value1, String value2) {
            addCriterion("timesec_end between", value1, value2, "timesecEnd");
            return (Criteria) this;
        }

        public Criteria andTimesecEndNotBetween(String value1, String value2) {
            addCriterion("timesec_end not between", value1, value2, "timesecEnd");
            return (Criteria) this;
        }

        public Criteria andTimesecStartIsNull() {
            addCriterion("timesec_start is null");
            return (Criteria) this;
        }

        public Criteria andTimesecStartIsNotNull() {
            addCriterion("timesec_start is not null");
            return (Criteria) this;
        }

        public Criteria andTimesecStartEqualTo(String value) {
            addCriterion("timesec_start =", value, "timesecStart");
            return (Criteria) this;
        }

        public Criteria andTimesecStartNotEqualTo(String value) {
            addCriterion("timesec_start <>", value, "timesecStart");
            return (Criteria) this;
        }

        public Criteria andTimesecStartGreaterThan(String value) {
            addCriterion("timesec_start >", value, "timesecStart");
            return (Criteria) this;
        }

        public Criteria andTimesecStartGreaterThanOrEqualTo(String value) {
            addCriterion("timesec_start >=", value, "timesecStart");
            return (Criteria) this;
        }

        public Criteria andTimesecStartLessThan(String value) {
            addCriterion("timesec_start <", value, "timesecStart");
            return (Criteria) this;
        }

        public Criteria andTimesecStartLessThanOrEqualTo(String value) {
            addCriterion("timesec_start <=", value, "timesecStart");
            return (Criteria) this;
        }

        public Criteria andTimesecStartLike(String value) {
            addCriterion("timesec_start like", value, "timesecStart");
            return (Criteria) this;
        }

        public Criteria andTimesecStartNotLike(String value) {
            addCriterion("timesec_start not like", value, "timesecStart");
            return (Criteria) this;
        }

        public Criteria andTimesecStartIn(List<String> values) {
            addCriterion("timesec_start in", values, "timesecStart");
            return (Criteria) this;
        }

        public Criteria andTimesecStartNotIn(List<String> values) {
            addCriterion("timesec_start not in", values, "timesecStart");
            return (Criteria) this;
        }

        public Criteria andTimesecStartBetween(String value1, String value2) {
            addCriterion("timesec_start between", value1, value2, "timesecStart");
            return (Criteria) this;
        }

        public Criteria andTimesecStartNotBetween(String value1, String value2) {
            addCriterion("timesec_start not between", value1, value2, "timesecStart");
            return (Criteria) this;
        }

        public Criteria andUnitTimeIsNull() {
            addCriterion("unit_time is null");
            return (Criteria) this;
        }

        public Criteria andUnitTimeIsNotNull() {
            addCriterion("unit_time is not null");
            return (Criteria) this;
        }

        public Criteria andUnitTimeEqualTo(Integer value) {
            addCriterion("unit_time =", value, "unitTime");
            return (Criteria) this;
        }

        public Criteria andUnitTimeNotEqualTo(Integer value) {
            addCriterion("unit_time <>", value, "unitTime");
            return (Criteria) this;
        }

        public Criteria andUnitTimeGreaterThan(Integer value) {
            addCriterion("unit_time >", value, "unitTime");
            return (Criteria) this;
        }

        public Criteria andUnitTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("unit_time >=", value, "unitTime");
            return (Criteria) this;
        }

        public Criteria andUnitTimeLessThan(Integer value) {
            addCriterion("unit_time <", value, "unitTime");
            return (Criteria) this;
        }

        public Criteria andUnitTimeLessThanOrEqualTo(Integer value) {
            addCriterion("unit_time <=", value, "unitTime");
            return (Criteria) this;
        }

        public Criteria andUnitTimeIn(List<Integer> values) {
            addCriterion("unit_time in", values, "unitTime");
            return (Criteria) this;
        }

        public Criteria andUnitTimeNotIn(List<Integer> values) {
            addCriterion("unit_time not in", values, "unitTime");
            return (Criteria) this;
        }

        public Criteria andUnitTimeBetween(Integer value1, Integer value2) {
            addCriterion("unit_time between", value1, value2, "unitTime");
            return (Criteria) this;
        }

        public Criteria andUnitTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("unit_time not between", value1, value2, "unitTime");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeIsNull() {
            addCriterion("unit_time_fee is null");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeIsNotNull() {
            addCriterion("unit_time_fee is not null");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeEqualTo(String value) {
            addCriterion("unit_time_fee =", value, "unitTimeFee");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeNotEqualTo(String value) {
            addCriterion("unit_time_fee <>", value, "unitTimeFee");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeGreaterThan(String value) {
            addCriterion("unit_time_fee >", value, "unitTimeFee");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeGreaterThanOrEqualTo(String value) {
            addCriterion("unit_time_fee >=", value, "unitTimeFee");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeLessThan(String value) {
            addCriterion("unit_time_fee <", value, "unitTimeFee");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeLessThanOrEqualTo(String value) {
            addCriterion("unit_time_fee <=", value, "unitTimeFee");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeLike(String value) {
            addCriterion("unit_time_fee like", value, "unitTimeFee");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeNotLike(String value) {
            addCriterion("unit_time_fee not like", value, "unitTimeFee");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeIn(List<String> values) {
            addCriterion("unit_time_fee in", values, "unitTimeFee");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeNotIn(List<String> values) {
            addCriterion("unit_time_fee not in", values, "unitTimeFee");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeBetween(String value1, String value2) {
            addCriterion("unit_time_fee between", value1, value2, "unitTimeFee");
            return (Criteria) this;
        }

        public Criteria andUnitTimeFeeNotBetween(String value1, String value2) {
            addCriterion("unit_time_fee not between", value1, value2, "unitTimeFee");
            return (Criteria) this;
        }

        public Criteria andIsMax24FeeByAddIsNull() {
            addCriterion("is_max_24_fee_by_add is null");
            return (Criteria) this;
        }

        public Criteria andIsMax24FeeByAddIsNotNull() {
            addCriterion("is_max_24_fee_by_add is not null");
            return (Criteria) this;
        }

        public Criteria andIsMax24FeeByAddEqualTo(Integer value) {
            addCriterion("is_max_24_fee_by_add =", value, "isMax24FeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMax24FeeByAddNotEqualTo(Integer value) {
            addCriterion("is_max_24_fee_by_add <>", value, "isMax24FeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMax24FeeByAddGreaterThan(Integer value) {
            addCriterion("is_max_24_fee_by_add >", value, "isMax24FeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMax24FeeByAddGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_max_24_fee_by_add >=", value, "isMax24FeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMax24FeeByAddLessThan(Integer value) {
            addCriterion("is_max_24_fee_by_add <", value, "isMax24FeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMax24FeeByAddLessThanOrEqualTo(Integer value) {
            addCriterion("is_max_24_fee_by_add <=", value, "isMax24FeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMax24FeeByAddIn(List<Integer> values) {
            addCriterion("is_max_24_fee_by_add in", values, "isMax24FeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMax24FeeByAddNotIn(List<Integer> values) {
            addCriterion("is_max_24_fee_by_add not in", values, "isMax24FeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMax24FeeByAddBetween(Integer value1, Integer value2) {
            addCriterion("is_max_24_fee_by_add between", value1, value2, "isMax24FeeByAdd");
            return (Criteria) this;
        }

        public Criteria andIsMax24FeeByAddNotBetween(Integer value1, Integer value2) {
            addCriterion("is_max_24_fee_by_add not between", value1, value2, "isMax24FeeByAdd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_charge_rule
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}