package com.api.entity;

public class TConponQrcode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conpon_qrcode.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conpon_qrcode.qrcode_name
     *
     * @mbg.generated
     */
    private String qrcodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conpon_qrcode.qrcode_url
     *
     * @mbg.generated
     */
    private String qrcodeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conpon_qrcode.tries_limit
     *
     * @mbg.generated
     */
    private Integer triesLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conpon_qrcode.use_limit
     *
     * @mbg.generated
     */
    private Integer useLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conpon_qrcode.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conpon_qrcode.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conpon_qrcode.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conpon_qrcode.id
     *
     * @return the value of t_conpon_qrcode.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conpon_qrcode.id
     *
     * @param id the value for t_conpon_qrcode.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conpon_qrcode.qrcode_name
     *
     * @return the value of t_conpon_qrcode.qrcode_name
     *
     * @mbg.generated
     */
    public String getQrcodeName() {
        return qrcodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conpon_qrcode.qrcode_name
     *
     * @param qrcodeName the value for t_conpon_qrcode.qrcode_name
     *
     * @mbg.generated
     */
    public void setQrcodeName(String qrcodeName) {
        this.qrcodeName = qrcodeName == null ? null : qrcodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conpon_qrcode.qrcode_url
     *
     * @return the value of t_conpon_qrcode.qrcode_url
     *
     * @mbg.generated
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conpon_qrcode.qrcode_url
     *
     * @param qrcodeUrl the value for t_conpon_qrcode.qrcode_url
     *
     * @mbg.generated
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl == null ? null : qrcodeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conpon_qrcode.tries_limit
     *
     * @return the value of t_conpon_qrcode.tries_limit
     *
     * @mbg.generated
     */
    public Integer getTriesLimit() {
        return triesLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conpon_qrcode.tries_limit
     *
     * @param triesLimit the value for t_conpon_qrcode.tries_limit
     *
     * @mbg.generated
     */
    public void setTriesLimit(Integer triesLimit) {
        this.triesLimit = triesLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conpon_qrcode.use_limit
     *
     * @return the value of t_conpon_qrcode.use_limit
     *
     * @mbg.generated
     */
    public Integer getUseLimit() {
        return useLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conpon_qrcode.use_limit
     *
     * @param useLimit the value for t_conpon_qrcode.use_limit
     *
     * @mbg.generated
     */
    public void setUseLimit(Integer useLimit) {
        this.useLimit = useLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conpon_qrcode.create_time
     *
     * @return the value of t_conpon_qrcode.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conpon_qrcode.create_time
     *
     * @param createTime the value for t_conpon_qrcode.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conpon_qrcode.company_id
     *
     * @return the value of t_conpon_qrcode.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conpon_qrcode.company_id
     *
     * @param companyId the value for t_conpon_qrcode.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conpon_qrcode.park_id
     *
     * @return the value of t_conpon_qrcode.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conpon_qrcode.park_id
     *
     * @param parkId the value for t_conpon_qrcode.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }
}