package com.api.entity;

public class TElectronicTicket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electronic_ticket.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electronic_ticket.ticket_name
     *
     * @mbg.generated
     */
    private String ticketName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electronic_ticket.ticket_type
     *
     * @mbg.generated
     */
    private Integer ticketType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electronic_ticket.ticket_value
     *
     * @mbg.generated
     */
    private Double ticketValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electronic_ticket.ticket_pay
     *
     * @mbg.generated
     */
    private Double ticketPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electronic_ticket.permission_day
     *
     * @mbg.generated
     */
    private String permissionDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electronic_ticket.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electronic_ticket.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electronic_ticket.id
     *
     * @return the value of t_electronic_ticket.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electronic_ticket.id
     *
     * @param id the value for t_electronic_ticket.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electronic_ticket.ticket_name
     *
     * @return the value of t_electronic_ticket.ticket_name
     *
     * @mbg.generated
     */
    public String getTicketName() {
        return ticketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electronic_ticket.ticket_name
     *
     * @param ticketName the value for t_electronic_ticket.ticket_name
     *
     * @mbg.generated
     */
    public void setTicketName(String ticketName) {
        this.ticketName = ticketName == null ? null : ticketName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electronic_ticket.ticket_type
     *
     * @return the value of t_electronic_ticket.ticket_type
     *
     * @mbg.generated
     */
    public Integer getTicketType() {
        return ticketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electronic_ticket.ticket_type
     *
     * @param ticketType the value for t_electronic_ticket.ticket_type
     *
     * @mbg.generated
     */
    public void setTicketType(Integer ticketType) {
        this.ticketType = ticketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electronic_ticket.ticket_value
     *
     * @return the value of t_electronic_ticket.ticket_value
     *
     * @mbg.generated
     */
    public Double getTicketValue() {
        return ticketValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electronic_ticket.ticket_value
     *
     * @param ticketValue the value for t_electronic_ticket.ticket_value
     *
     * @mbg.generated
     */
    public void setTicketValue(Double ticketValue) {
        this.ticketValue = ticketValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electronic_ticket.ticket_pay
     *
     * @return the value of t_electronic_ticket.ticket_pay
     *
     * @mbg.generated
     */
    public Double getTicketPay() {
        return ticketPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electronic_ticket.ticket_pay
     *
     * @param ticketPay the value for t_electronic_ticket.ticket_pay
     *
     * @mbg.generated
     */
    public void setTicketPay(Double ticketPay) {
        this.ticketPay = ticketPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electronic_ticket.permission_day
     *
     * @return the value of t_electronic_ticket.permission_day
     *
     * @mbg.generated
     */
    public String getPermissionDay() {
        return permissionDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electronic_ticket.permission_day
     *
     * @param permissionDay the value for t_electronic_ticket.permission_day
     *
     * @mbg.generated
     */
    public void setPermissionDay(String permissionDay) {
        this.permissionDay = permissionDay == null ? null : permissionDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electronic_ticket.company_id
     *
     * @return the value of t_electronic_ticket.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electronic_ticket.company_id
     *
     * @param companyId the value for t_electronic_ticket.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electronic_ticket.update_time
     *
     * @return the value of t_electronic_ticket.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electronic_ticket.update_time
     *
     * @param updateTime the value for t_electronic_ticket.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}