package com.api.entity;

import java.util.ArrayList;
import java.util.List;

public class TLowpeakbytimespanCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    public TLowpeakbytimespanCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBeginTimeHourIsNull() {
            addCriterion("begin_time_hour is null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeHourIsNotNull() {
            addCriterion("begin_time_hour is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeHourEqualTo(Integer value) {
            addCriterion("begin_time_hour =", value, "beginTimeHour");
            return (Criteria) this;
        }

        public Criteria andBeginTimeHourNotEqualTo(Integer value) {
            addCriterion("begin_time_hour <>", value, "beginTimeHour");
            return (Criteria) this;
        }

        public Criteria andBeginTimeHourGreaterThan(Integer value) {
            addCriterion("begin_time_hour >", value, "beginTimeHour");
            return (Criteria) this;
        }

        public Criteria andBeginTimeHourGreaterThanOrEqualTo(Integer value) {
            addCriterion("begin_time_hour >=", value, "beginTimeHour");
            return (Criteria) this;
        }

        public Criteria andBeginTimeHourLessThan(Integer value) {
            addCriterion("begin_time_hour <", value, "beginTimeHour");
            return (Criteria) this;
        }

        public Criteria andBeginTimeHourLessThanOrEqualTo(Integer value) {
            addCriterion("begin_time_hour <=", value, "beginTimeHour");
            return (Criteria) this;
        }

        public Criteria andBeginTimeHourIn(List<Integer> values) {
            addCriterion("begin_time_hour in", values, "beginTimeHour");
            return (Criteria) this;
        }

        public Criteria andBeginTimeHourNotIn(List<Integer> values) {
            addCriterion("begin_time_hour not in", values, "beginTimeHour");
            return (Criteria) this;
        }

        public Criteria andBeginTimeHourBetween(Integer value1, Integer value2) {
            addCriterion("begin_time_hour between", value1, value2, "beginTimeHour");
            return (Criteria) this;
        }

        public Criteria andBeginTimeHourNotBetween(Integer value1, Integer value2) {
            addCriterion("begin_time_hour not between", value1, value2, "beginTimeHour");
            return (Criteria) this;
        }

        public Criteria andBeginTimeMinuteIsNull() {
            addCriterion("begin_time_minute is null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeMinuteIsNotNull() {
            addCriterion("begin_time_minute is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeMinuteEqualTo(Integer value) {
            addCriterion("begin_time_minute =", value, "beginTimeMinute");
            return (Criteria) this;
        }

        public Criteria andBeginTimeMinuteNotEqualTo(Integer value) {
            addCriterion("begin_time_minute <>", value, "beginTimeMinute");
            return (Criteria) this;
        }

        public Criteria andBeginTimeMinuteGreaterThan(Integer value) {
            addCriterion("begin_time_minute >", value, "beginTimeMinute");
            return (Criteria) this;
        }

        public Criteria andBeginTimeMinuteGreaterThanOrEqualTo(Integer value) {
            addCriterion("begin_time_minute >=", value, "beginTimeMinute");
            return (Criteria) this;
        }

        public Criteria andBeginTimeMinuteLessThan(Integer value) {
            addCriterion("begin_time_minute <", value, "beginTimeMinute");
            return (Criteria) this;
        }

        public Criteria andBeginTimeMinuteLessThanOrEqualTo(Integer value) {
            addCriterion("begin_time_minute <=", value, "beginTimeMinute");
            return (Criteria) this;
        }

        public Criteria andBeginTimeMinuteIn(List<Integer> values) {
            addCriterion("begin_time_minute in", values, "beginTimeMinute");
            return (Criteria) this;
        }

        public Criteria andBeginTimeMinuteNotIn(List<Integer> values) {
            addCriterion("begin_time_minute not in", values, "beginTimeMinute");
            return (Criteria) this;
        }

        public Criteria andBeginTimeMinuteBetween(Integer value1, Integer value2) {
            addCriterion("begin_time_minute between", value1, value2, "beginTimeMinute");
            return (Criteria) this;
        }

        public Criteria andBeginTimeMinuteNotBetween(Integer value1, Integer value2) {
            addCriterion("begin_time_minute not between", value1, value2, "beginTimeMinute");
            return (Criteria) this;
        }

        public Criteria andCascadeFlagIsNull() {
            addCriterion("cascade_flag is null");
            return (Criteria) this;
        }

        public Criteria andCascadeFlagIsNotNull() {
            addCriterion("cascade_flag is not null");
            return (Criteria) this;
        }

        public Criteria andCascadeFlagEqualTo(Integer value) {
            addCriterion("cascade_flag =", value, "cascadeFlag");
            return (Criteria) this;
        }

        public Criteria andCascadeFlagNotEqualTo(Integer value) {
            addCriterion("cascade_flag <>", value, "cascadeFlag");
            return (Criteria) this;
        }

        public Criteria andCascadeFlagGreaterThan(Integer value) {
            addCriterion("cascade_flag >", value, "cascadeFlag");
            return (Criteria) this;
        }

        public Criteria andCascadeFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("cascade_flag >=", value, "cascadeFlag");
            return (Criteria) this;
        }

        public Criteria andCascadeFlagLessThan(Integer value) {
            addCriterion("cascade_flag <", value, "cascadeFlag");
            return (Criteria) this;
        }

        public Criteria andCascadeFlagLessThanOrEqualTo(Integer value) {
            addCriterion("cascade_flag <=", value, "cascadeFlag");
            return (Criteria) this;
        }

        public Criteria andCascadeFlagIn(List<Integer> values) {
            addCriterion("cascade_flag in", values, "cascadeFlag");
            return (Criteria) this;
        }

        public Criteria andCascadeFlagNotIn(List<Integer> values) {
            addCriterion("cascade_flag not in", values, "cascadeFlag");
            return (Criteria) this;
        }

        public Criteria andCascadeFlagBetween(Integer value1, Integer value2) {
            addCriterion("cascade_flag between", value1, value2, "cascadeFlag");
            return (Criteria) this;
        }

        public Criteria andCascadeFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("cascade_flag not between", value1, value2, "cascadeFlag");
            return (Criteria) this;
        }

        public Criteria andCascadeIdIsNull() {
            addCriterion("cascade_id is null");
            return (Criteria) this;
        }

        public Criteria andCascadeIdIsNotNull() {
            addCriterion("cascade_id is not null");
            return (Criteria) this;
        }

        public Criteria andCascadeIdEqualTo(Integer value) {
            addCriterion("cascade_id =", value, "cascadeId");
            return (Criteria) this;
        }

        public Criteria andCascadeIdNotEqualTo(Integer value) {
            addCriterion("cascade_id <>", value, "cascadeId");
            return (Criteria) this;
        }

        public Criteria andCascadeIdGreaterThan(Integer value) {
            addCriterion("cascade_id >", value, "cascadeId");
            return (Criteria) this;
        }

        public Criteria andCascadeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cascade_id >=", value, "cascadeId");
            return (Criteria) this;
        }

        public Criteria andCascadeIdLessThan(Integer value) {
            addCriterion("cascade_id <", value, "cascadeId");
            return (Criteria) this;
        }

        public Criteria andCascadeIdLessThanOrEqualTo(Integer value) {
            addCriterion("cascade_id <=", value, "cascadeId");
            return (Criteria) this;
        }

        public Criteria andCascadeIdIn(List<Integer> values) {
            addCriterion("cascade_id in", values, "cascadeId");
            return (Criteria) this;
        }

        public Criteria andCascadeIdNotIn(List<Integer> values) {
            addCriterion("cascade_id not in", values, "cascadeId");
            return (Criteria) this;
        }

        public Criteria andCascadeIdBetween(Integer value1, Integer value2) {
            addCriterion("cascade_id between", value1, value2, "cascadeId");
            return (Criteria) this;
        }

        public Criteria andCascadeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cascade_id not between", value1, value2, "cascadeId");
            return (Criteria) this;
        }

        public Criteria andCompIndexIsNull() {
            addCriterion("comp_index is null");
            return (Criteria) this;
        }

        public Criteria andCompIndexIsNotNull() {
            addCriterion("comp_index is not null");
            return (Criteria) this;
        }

        public Criteria andCompIndexEqualTo(String value) {
            addCriterion("comp_index =", value, "compIndex");
            return (Criteria) this;
        }

        public Criteria andCompIndexNotEqualTo(String value) {
            addCriterion("comp_index <>", value, "compIndex");
            return (Criteria) this;
        }

        public Criteria andCompIndexGreaterThan(String value) {
            addCriterion("comp_index >", value, "compIndex");
            return (Criteria) this;
        }

        public Criteria andCompIndexGreaterThanOrEqualTo(String value) {
            addCriterion("comp_index >=", value, "compIndex");
            return (Criteria) this;
        }

        public Criteria andCompIndexLessThan(String value) {
            addCriterion("comp_index <", value, "compIndex");
            return (Criteria) this;
        }

        public Criteria andCompIndexLessThanOrEqualTo(String value) {
            addCriterion("comp_index <=", value, "compIndex");
            return (Criteria) this;
        }

        public Criteria andCompIndexLike(String value) {
            addCriterion("comp_index like", value, "compIndex");
            return (Criteria) this;
        }

        public Criteria andCompIndexNotLike(String value) {
            addCriterion("comp_index not like", value, "compIndex");
            return (Criteria) this;
        }

        public Criteria andCompIndexIn(List<String> values) {
            addCriterion("comp_index in", values, "compIndex");
            return (Criteria) this;
        }

        public Criteria andCompIndexNotIn(List<String> values) {
            addCriterion("comp_index not in", values, "compIndex");
            return (Criteria) this;
        }

        public Criteria andCompIndexBetween(String value1, String value2) {
            addCriterion("comp_index between", value1, value2, "compIndex");
            return (Criteria) this;
        }

        public Criteria andCompIndexNotBetween(String value1, String value2) {
            addCriterion("comp_index not between", value1, value2, "compIndex");
            return (Criteria) this;
        }

        public Criteria andEndTimeHourIsNull() {
            addCriterion("end_time_hour is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeHourIsNotNull() {
            addCriterion("end_time_hour is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeHourEqualTo(Integer value) {
            addCriterion("end_time_hour =", value, "endTimeHour");
            return (Criteria) this;
        }

        public Criteria andEndTimeHourNotEqualTo(Integer value) {
            addCriterion("end_time_hour <>", value, "endTimeHour");
            return (Criteria) this;
        }

        public Criteria andEndTimeHourGreaterThan(Integer value) {
            addCriterion("end_time_hour >", value, "endTimeHour");
            return (Criteria) this;
        }

        public Criteria andEndTimeHourGreaterThanOrEqualTo(Integer value) {
            addCriterion("end_time_hour >=", value, "endTimeHour");
            return (Criteria) this;
        }

        public Criteria andEndTimeHourLessThan(Integer value) {
            addCriterion("end_time_hour <", value, "endTimeHour");
            return (Criteria) this;
        }

        public Criteria andEndTimeHourLessThanOrEqualTo(Integer value) {
            addCriterion("end_time_hour <=", value, "endTimeHour");
            return (Criteria) this;
        }

        public Criteria andEndTimeHourIn(List<Integer> values) {
            addCriterion("end_time_hour in", values, "endTimeHour");
            return (Criteria) this;
        }

        public Criteria andEndTimeHourNotIn(List<Integer> values) {
            addCriterion("end_time_hour not in", values, "endTimeHour");
            return (Criteria) this;
        }

        public Criteria andEndTimeHourBetween(Integer value1, Integer value2) {
            addCriterion("end_time_hour between", value1, value2, "endTimeHour");
            return (Criteria) this;
        }

        public Criteria andEndTimeHourNotBetween(Integer value1, Integer value2) {
            addCriterion("end_time_hour not between", value1, value2, "endTimeHour");
            return (Criteria) this;
        }

        public Criteria andEndTimeMinuteIsNull() {
            addCriterion("end_time_minute is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeMinuteIsNotNull() {
            addCriterion("end_time_minute is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeMinuteEqualTo(Integer value) {
            addCriterion("end_time_minute =", value, "endTimeMinute");
            return (Criteria) this;
        }

        public Criteria andEndTimeMinuteNotEqualTo(Integer value) {
            addCriterion("end_time_minute <>", value, "endTimeMinute");
            return (Criteria) this;
        }

        public Criteria andEndTimeMinuteGreaterThan(Integer value) {
            addCriterion("end_time_minute >", value, "endTimeMinute");
            return (Criteria) this;
        }

        public Criteria andEndTimeMinuteGreaterThanOrEqualTo(Integer value) {
            addCriterion("end_time_minute >=", value, "endTimeMinute");
            return (Criteria) this;
        }

        public Criteria andEndTimeMinuteLessThan(Integer value) {
            addCriterion("end_time_minute <", value, "endTimeMinute");
            return (Criteria) this;
        }

        public Criteria andEndTimeMinuteLessThanOrEqualTo(Integer value) {
            addCriterion("end_time_minute <=", value, "endTimeMinute");
            return (Criteria) this;
        }

        public Criteria andEndTimeMinuteIn(List<Integer> values) {
            addCriterion("end_time_minute in", values, "endTimeMinute");
            return (Criteria) this;
        }

        public Criteria andEndTimeMinuteNotIn(List<Integer> values) {
            addCriterion("end_time_minute not in", values, "endTimeMinute");
            return (Criteria) this;
        }

        public Criteria andEndTimeMinuteBetween(Integer value1, Integer value2) {
            addCriterion("end_time_minute between", value1, value2, "endTimeMinute");
            return (Criteria) this;
        }

        public Criteria andEndTimeMinuteNotBetween(Integer value1, Integer value2) {
            addCriterion("end_time_minute not between", value1, value2, "endTimeMinute");
            return (Criteria) this;
        }

        public Criteria andLocidIsNull() {
            addCriterion("locId is null");
            return (Criteria) this;
        }

        public Criteria andLocidIsNotNull() {
            addCriterion("locId is not null");
            return (Criteria) this;
        }

        public Criteria andLocidEqualTo(Integer value) {
            addCriterion("locId =", value, "locid");
            return (Criteria) this;
        }

        public Criteria andLocidNotEqualTo(Integer value) {
            addCriterion("locId <>", value, "locid");
            return (Criteria) this;
        }

        public Criteria andLocidGreaterThan(Integer value) {
            addCriterion("locId >", value, "locid");
            return (Criteria) this;
        }

        public Criteria andLocidGreaterThanOrEqualTo(Integer value) {
            addCriterion("locId >=", value, "locid");
            return (Criteria) this;
        }

        public Criteria andLocidLessThan(Integer value) {
            addCriterion("locId <", value, "locid");
            return (Criteria) this;
        }

        public Criteria andLocidLessThanOrEqualTo(Integer value) {
            addCriterion("locId <=", value, "locid");
            return (Criteria) this;
        }

        public Criteria andLocidIn(List<Integer> values) {
            addCriterion("locId in", values, "locid");
            return (Criteria) this;
        }

        public Criteria andLocidNotIn(List<Integer> values) {
            addCriterion("locId not in", values, "locid");
            return (Criteria) this;
        }

        public Criteria andLocidBetween(Integer value1, Integer value2) {
            addCriterion("locId between", value1, value2, "locid");
            return (Criteria) this;
        }

        public Criteria andLocidNotBetween(Integer value1, Integer value2) {
            addCriterion("locId not between", value1, value2, "locid");
            return (Criteria) this;
        }

        public Criteria andParkIdIsNull() {
            addCriterion("park_id is null");
            return (Criteria) this;
        }

        public Criteria andParkIdIsNotNull() {
            addCriterion("park_id is not null");
            return (Criteria) this;
        }

        public Criteria andParkIdEqualTo(Integer value) {
            addCriterion("park_id =", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotEqualTo(Integer value) {
            addCriterion("park_id <>", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdGreaterThan(Integer value) {
            addCriterion("park_id >", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("park_id >=", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdLessThan(Integer value) {
            addCriterion("park_id <", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdLessThanOrEqualTo(Integer value) {
            addCriterion("park_id <=", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdIn(List<Integer> values) {
            addCriterion("park_id in", values, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotIn(List<Integer> values) {
            addCriterion("park_id not in", values, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdBetween(Integer value1, Integer value2) {
            addCriterion("park_id between", value1, value2, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("park_id not between", value1, value2, "parkId");
            return (Criteria) this;
        }

        public Criteria andStaFlagIsNull() {
            addCriterion("sta_flag is null");
            return (Criteria) this;
        }

        public Criteria andStaFlagIsNotNull() {
            addCriterion("sta_flag is not null");
            return (Criteria) this;
        }

        public Criteria andStaFlagEqualTo(Integer value) {
            addCriterion("sta_flag =", value, "staFlag");
            return (Criteria) this;
        }

        public Criteria andStaFlagNotEqualTo(Integer value) {
            addCriterion("sta_flag <>", value, "staFlag");
            return (Criteria) this;
        }

        public Criteria andStaFlagGreaterThan(Integer value) {
            addCriterion("sta_flag >", value, "staFlag");
            return (Criteria) this;
        }

        public Criteria andStaFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("sta_flag >=", value, "staFlag");
            return (Criteria) this;
        }

        public Criteria andStaFlagLessThan(Integer value) {
            addCriterion("sta_flag <", value, "staFlag");
            return (Criteria) this;
        }

        public Criteria andStaFlagLessThanOrEqualTo(Integer value) {
            addCriterion("sta_flag <=", value, "staFlag");
            return (Criteria) this;
        }

        public Criteria andStaFlagIn(List<Integer> values) {
            addCriterion("sta_flag in", values, "staFlag");
            return (Criteria) this;
        }

        public Criteria andStaFlagNotIn(List<Integer> values) {
            addCriterion("sta_flag not in", values, "staFlag");
            return (Criteria) this;
        }

        public Criteria andStaFlagBetween(Integer value1, Integer value2) {
            addCriterion("sta_flag between", value1, value2, "staFlag");
            return (Criteria) this;
        }

        public Criteria andStaFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("sta_flag not between", value1, value2, "staFlag");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_lowpeakbytimespan
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}