package com.api.entity;

import java.util.ArrayList;
import java.util.List;

public class TMemberCardChangeCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    public TMemberCardChangeCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMemberDetailIdIsNull() {
            addCriterion("member_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberDetailIdIsNotNull() {
            addCriterion("member_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberDetailIdEqualTo(Integer value) {
            addCriterion("member_detail_id =", value, "memberDetailId");
            return (Criteria) this;
        }

        public Criteria andMemberDetailIdNotEqualTo(Integer value) {
            addCriterion("member_detail_id <>", value, "memberDetailId");
            return (Criteria) this;
        }

        public Criteria andMemberDetailIdGreaterThan(Integer value) {
            addCriterion("member_detail_id >", value, "memberDetailId");
            return (Criteria) this;
        }

        public Criteria andMemberDetailIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("member_detail_id >=", value, "memberDetailId");
            return (Criteria) this;
        }

        public Criteria andMemberDetailIdLessThan(Integer value) {
            addCriterion("member_detail_id <", value, "memberDetailId");
            return (Criteria) this;
        }

        public Criteria andMemberDetailIdLessThanOrEqualTo(Integer value) {
            addCriterion("member_detail_id <=", value, "memberDetailId");
            return (Criteria) this;
        }

        public Criteria andMemberDetailIdIn(List<Integer> values) {
            addCriterion("member_detail_id in", values, "memberDetailId");
            return (Criteria) this;
        }

        public Criteria andMemberDetailIdNotIn(List<Integer> values) {
            addCriterion("member_detail_id not in", values, "memberDetailId");
            return (Criteria) this;
        }

        public Criteria andMemberDetailIdBetween(Integer value1, Integer value2) {
            addCriterion("member_detail_id between", value1, value2, "memberDetailId");
            return (Criteria) this;
        }

        public Criteria andMemberDetailIdNotBetween(Integer value1, Integer value2) {
            addCriterion("member_detail_id not between", value1, value2, "memberDetailId");
            return (Criteria) this;
        }

        public Criteria andCarNumIsNull() {
            addCriterion("car_num is null");
            return (Criteria) this;
        }

        public Criteria andCarNumIsNotNull() {
            addCriterion("car_num is not null");
            return (Criteria) this;
        }

        public Criteria andCarNumEqualTo(String value) {
            addCriterion("car_num =", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumNotEqualTo(String value) {
            addCriterion("car_num <>", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumGreaterThan(String value) {
            addCriterion("car_num >", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumGreaterThanOrEqualTo(String value) {
            addCriterion("car_num >=", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumLessThan(String value) {
            addCriterion("car_num <", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumLessThanOrEqualTo(String value) {
            addCriterion("car_num <=", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumLike(String value) {
            addCriterion("car_num like", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumNotLike(String value) {
            addCriterion("car_num not like", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumIn(List<String> values) {
            addCriterion("car_num in", values, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumNotIn(List<String> values) {
            addCriterion("car_num not in", values, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumBetween(String value1, String value2) {
            addCriterion("car_num between", value1, value2, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumNotBetween(String value1, String value2) {
            addCriterion("car_num not between", value1, value2, "carNum");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdIsNull() {
            addCriterion("ori_p_card_id is null");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdIsNotNull() {
            addCriterion("ori_p_card_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdEqualTo(String value) {
            addCriterion("ori_p_card_id =", value, "oriPCardId");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdNotEqualTo(String value) {
            addCriterion("ori_p_card_id <>", value, "oriPCardId");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdGreaterThan(String value) {
            addCriterion("ori_p_card_id >", value, "oriPCardId");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdGreaterThanOrEqualTo(String value) {
            addCriterion("ori_p_card_id >=", value, "oriPCardId");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdLessThan(String value) {
            addCriterion("ori_p_card_id <", value, "oriPCardId");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdLessThanOrEqualTo(String value) {
            addCriterion("ori_p_card_id <=", value, "oriPCardId");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdLike(String value) {
            addCriterion("ori_p_card_id like", value, "oriPCardId");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdNotLike(String value) {
            addCriterion("ori_p_card_id not like", value, "oriPCardId");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdIn(List<String> values) {
            addCriterion("ori_p_card_id in", values, "oriPCardId");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdNotIn(List<String> values) {
            addCriterion("ori_p_card_id not in", values, "oriPCardId");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdBetween(String value1, String value2) {
            addCriterion("ori_p_card_id between", value1, value2, "oriPCardId");
            return (Criteria) this;
        }

        public Criteria andOriPCardIdNotBetween(String value1, String value2) {
            addCriterion("ori_p_card_id not between", value1, value2, "oriPCardId");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeIsNull() {
            addCriterion("ori_p_card_code is null");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeIsNotNull() {
            addCriterion("ori_p_card_code is not null");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeEqualTo(String value) {
            addCriterion("ori_p_card_code =", value, "oriPCardCode");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeNotEqualTo(String value) {
            addCriterion("ori_p_card_code <>", value, "oriPCardCode");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeGreaterThan(String value) {
            addCriterion("ori_p_card_code >", value, "oriPCardCode");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ori_p_card_code >=", value, "oriPCardCode");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeLessThan(String value) {
            addCriterion("ori_p_card_code <", value, "oriPCardCode");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeLessThanOrEqualTo(String value) {
            addCriterion("ori_p_card_code <=", value, "oriPCardCode");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeLike(String value) {
            addCriterion("ori_p_card_code like", value, "oriPCardCode");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeNotLike(String value) {
            addCriterion("ori_p_card_code not like", value, "oriPCardCode");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeIn(List<String> values) {
            addCriterion("ori_p_card_code in", values, "oriPCardCode");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeNotIn(List<String> values) {
            addCriterion("ori_p_card_code not in", values, "oriPCardCode");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeBetween(String value1, String value2) {
            addCriterion("ori_p_card_code between", value1, value2, "oriPCardCode");
            return (Criteria) this;
        }

        public Criteria andOriPCardCodeNotBetween(String value1, String value2) {
            addCriterion("ori_p_card_code not between", value1, value2, "oriPCardCode");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdIsNull() {
            addCriterion("ori_p_card_pwd is null");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdIsNotNull() {
            addCriterion("ori_p_card_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdEqualTo(String value) {
            addCriterion("ori_p_card_pwd =", value, "oriPCardPwd");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdNotEqualTo(String value) {
            addCriterion("ori_p_card_pwd <>", value, "oriPCardPwd");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdGreaterThan(String value) {
            addCriterion("ori_p_card_pwd >", value, "oriPCardPwd");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdGreaterThanOrEqualTo(String value) {
            addCriterion("ori_p_card_pwd >=", value, "oriPCardPwd");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdLessThan(String value) {
            addCriterion("ori_p_card_pwd <", value, "oriPCardPwd");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdLessThanOrEqualTo(String value) {
            addCriterion("ori_p_card_pwd <=", value, "oriPCardPwd");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdLike(String value) {
            addCriterion("ori_p_card_pwd like", value, "oriPCardPwd");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdNotLike(String value) {
            addCriterion("ori_p_card_pwd not like", value, "oriPCardPwd");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdIn(List<String> values) {
            addCriterion("ori_p_card_pwd in", values, "oriPCardPwd");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdNotIn(List<String> values) {
            addCriterion("ori_p_card_pwd not in", values, "oriPCardPwd");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdBetween(String value1, String value2) {
            addCriterion("ori_p_card_pwd between", value1, value2, "oriPCardPwd");
            return (Criteria) this;
        }

        public Criteria andOriPCardPwdNotBetween(String value1, String value2) {
            addCriterion("ori_p_card_pwd not between", value1, value2, "oriPCardPwd");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdIsNull() {
            addCriterion("new_p_card_id is null");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdIsNotNull() {
            addCriterion("new_p_card_id is not null");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdEqualTo(String value) {
            addCriterion("new_p_card_id =", value, "newPCardId");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdNotEqualTo(String value) {
            addCriterion("new_p_card_id <>", value, "newPCardId");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdGreaterThan(String value) {
            addCriterion("new_p_card_id >", value, "newPCardId");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdGreaterThanOrEqualTo(String value) {
            addCriterion("new_p_card_id >=", value, "newPCardId");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdLessThan(String value) {
            addCriterion("new_p_card_id <", value, "newPCardId");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdLessThanOrEqualTo(String value) {
            addCriterion("new_p_card_id <=", value, "newPCardId");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdLike(String value) {
            addCriterion("new_p_card_id like", value, "newPCardId");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdNotLike(String value) {
            addCriterion("new_p_card_id not like", value, "newPCardId");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdIn(List<String> values) {
            addCriterion("new_p_card_id in", values, "newPCardId");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdNotIn(List<String> values) {
            addCriterion("new_p_card_id not in", values, "newPCardId");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdBetween(String value1, String value2) {
            addCriterion("new_p_card_id between", value1, value2, "newPCardId");
            return (Criteria) this;
        }

        public Criteria andNewPCardIdNotBetween(String value1, String value2) {
            addCriterion("new_p_card_id not between", value1, value2, "newPCardId");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeIsNull() {
            addCriterion("new_p_card_code is null");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeIsNotNull() {
            addCriterion("new_p_card_code is not null");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeEqualTo(String value) {
            addCriterion("new_p_card_code =", value, "newPCardCode");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeNotEqualTo(String value) {
            addCriterion("new_p_card_code <>", value, "newPCardCode");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeGreaterThan(String value) {
            addCriterion("new_p_card_code >", value, "newPCardCode");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeGreaterThanOrEqualTo(String value) {
            addCriterion("new_p_card_code >=", value, "newPCardCode");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeLessThan(String value) {
            addCriterion("new_p_card_code <", value, "newPCardCode");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeLessThanOrEqualTo(String value) {
            addCriterion("new_p_card_code <=", value, "newPCardCode");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeLike(String value) {
            addCriterion("new_p_card_code like", value, "newPCardCode");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeNotLike(String value) {
            addCriterion("new_p_card_code not like", value, "newPCardCode");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeIn(List<String> values) {
            addCriterion("new_p_card_code in", values, "newPCardCode");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeNotIn(List<String> values) {
            addCriterion("new_p_card_code not in", values, "newPCardCode");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeBetween(String value1, String value2) {
            addCriterion("new_p_card_code between", value1, value2, "newPCardCode");
            return (Criteria) this;
        }

        public Criteria andNewPCardCodeNotBetween(String value1, String value2) {
            addCriterion("new_p_card_code not between", value1, value2, "newPCardCode");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdIsNull() {
            addCriterion("new_p_card_pwd is null");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdIsNotNull() {
            addCriterion("new_p_card_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdEqualTo(String value) {
            addCriterion("new_p_card_pwd =", value, "newPCardPwd");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdNotEqualTo(String value) {
            addCriterion("new_p_card_pwd <>", value, "newPCardPwd");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdGreaterThan(String value) {
            addCriterion("new_p_card_pwd >", value, "newPCardPwd");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdGreaterThanOrEqualTo(String value) {
            addCriterion("new_p_card_pwd >=", value, "newPCardPwd");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdLessThan(String value) {
            addCriterion("new_p_card_pwd <", value, "newPCardPwd");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdLessThanOrEqualTo(String value) {
            addCriterion("new_p_card_pwd <=", value, "newPCardPwd");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdLike(String value) {
            addCriterion("new_p_card_pwd like", value, "newPCardPwd");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdNotLike(String value) {
            addCriterion("new_p_card_pwd not like", value, "newPCardPwd");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdIn(List<String> values) {
            addCriterion("new_p_card_pwd in", values, "newPCardPwd");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdNotIn(List<String> values) {
            addCriterion("new_p_card_pwd not in", values, "newPCardPwd");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdBetween(String value1, String value2) {
            addCriterion("new_p_card_pwd between", value1, value2, "newPCardPwd");
            return (Criteria) this;
        }

        public Criteria andNewPCardPwdNotBetween(String value1, String value2) {
            addCriterion("new_p_card_pwd not between", value1, value2, "newPCardPwd");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_member_card_change
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_member_card_change
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}