package com.api.entity;

import java.util.ArrayList;
import java.util.List;

public class TPrepayCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    public TPrepayCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParkIdIsNull() {
            addCriterion("park_id is null");
            return (Criteria) this;
        }

        public Criteria andParkIdIsNotNull() {
            addCriterion("park_id is not null");
            return (Criteria) this;
        }

        public Criteria andParkIdEqualTo(Integer value) {
            addCriterion("park_id =", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotEqualTo(Integer value) {
            addCriterion("park_id <>", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdGreaterThan(Integer value) {
            addCriterion("park_id >", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("park_id >=", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdLessThan(Integer value) {
            addCriterion("park_id <", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdLessThanOrEqualTo(Integer value) {
            addCriterion("park_id <=", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdIn(List<Integer> values) {
            addCriterion("park_id in", values, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotIn(List<Integer> values) {
            addCriterion("park_id not in", values, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdBetween(Integer value1, Integer value2) {
            addCriterion("park_id between", value1, value2, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("park_id not between", value1, value2, "parkId");
            return (Criteria) this;
        }

        public Criteria andCarPlateIsNull() {
            addCriterion("car_plate is null");
            return (Criteria) this;
        }

        public Criteria andCarPlateIsNotNull() {
            addCriterion("car_plate is not null");
            return (Criteria) this;
        }

        public Criteria andCarPlateEqualTo(String value) {
            addCriterion("car_plate =", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateNotEqualTo(String value) {
            addCriterion("car_plate <>", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateGreaterThan(String value) {
            addCriterion("car_plate >", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateGreaterThanOrEqualTo(String value) {
            addCriterion("car_plate >=", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateLessThan(String value) {
            addCriterion("car_plate <", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateLessThanOrEqualTo(String value) {
            addCriterion("car_plate <=", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateLike(String value) {
            addCriterion("car_plate like", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateNotLike(String value) {
            addCriterion("car_plate not like", value, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateIn(List<String> values) {
            addCriterion("car_plate in", values, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateNotIn(List<String> values) {
            addCriterion("car_plate not in", values, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateBetween(String value1, String value2) {
            addCriterion("car_plate between", value1, value2, "carPlate");
            return (Criteria) this;
        }

        public Criteria andCarPlateNotBetween(String value1, String value2) {
            addCriterion("car_plate not between", value1, value2, "carPlate");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdIsNull() {
            addCriterion("prepay_order_Id is null");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdIsNotNull() {
            addCriterion("prepay_order_Id is not null");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdEqualTo(String value) {
            addCriterion("prepay_order_Id =", value, "prepayOrderId");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdNotEqualTo(String value) {
            addCriterion("prepay_order_Id <>", value, "prepayOrderId");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdGreaterThan(String value) {
            addCriterion("prepay_order_Id >", value, "prepayOrderId");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("prepay_order_Id >=", value, "prepayOrderId");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdLessThan(String value) {
            addCriterion("prepay_order_Id <", value, "prepayOrderId");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdLessThanOrEqualTo(String value) {
            addCriterion("prepay_order_Id <=", value, "prepayOrderId");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdLike(String value) {
            addCriterion("prepay_order_Id like", value, "prepayOrderId");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdNotLike(String value) {
            addCriterion("prepay_order_Id not like", value, "prepayOrderId");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdIn(List<String> values) {
            addCriterion("prepay_order_Id in", values, "prepayOrderId");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdNotIn(List<String> values) {
            addCriterion("prepay_order_Id not in", values, "prepayOrderId");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdBetween(String value1, String value2) {
            addCriterion("prepay_order_Id between", value1, value2, "prepayOrderId");
            return (Criteria) this;
        }

        public Criteria andPrepayOrderIdNotBetween(String value1, String value2) {
            addCriterion("prepay_order_Id not between", value1, value2, "prepayOrderId");
            return (Criteria) this;
        }

        public Criteria andPrepayTypeIsNull() {
            addCriterion("prepay_type is null");
            return (Criteria) this;
        }

        public Criteria andPrepayTypeIsNotNull() {
            addCriterion("prepay_type is not null");
            return (Criteria) this;
        }

        public Criteria andPrepayTypeEqualTo(Integer value) {
            addCriterion("prepay_type =", value, "prepayType");
            return (Criteria) this;
        }

        public Criteria andPrepayTypeNotEqualTo(Integer value) {
            addCriterion("prepay_type <>", value, "prepayType");
            return (Criteria) this;
        }

        public Criteria andPrepayTypeGreaterThan(Integer value) {
            addCriterion("prepay_type >", value, "prepayType");
            return (Criteria) this;
        }

        public Criteria andPrepayTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("prepay_type >=", value, "prepayType");
            return (Criteria) this;
        }

        public Criteria andPrepayTypeLessThan(Integer value) {
            addCriterion("prepay_type <", value, "prepayType");
            return (Criteria) this;
        }

        public Criteria andPrepayTypeLessThanOrEqualTo(Integer value) {
            addCriterion("prepay_type <=", value, "prepayType");
            return (Criteria) this;
        }

        public Criteria andPrepayTypeIn(List<Integer> values) {
            addCriterion("prepay_type in", values, "prepayType");
            return (Criteria) this;
        }

        public Criteria andPrepayTypeNotIn(List<Integer> values) {
            addCriterion("prepay_type not in", values, "prepayType");
            return (Criteria) this;
        }

        public Criteria andPrepayTypeBetween(Integer value1, Integer value2) {
            addCriterion("prepay_type between", value1, value2, "prepayType");
            return (Criteria) this;
        }

        public Criteria andPrepayTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("prepay_type not between", value1, value2, "prepayType");
            return (Criteria) this;
        }

        public Criteria andActualPrepayTypeIsNull() {
            addCriterion("actual_prepay_type is null");
            return (Criteria) this;
        }

        public Criteria andActualPrepayTypeIsNotNull() {
            addCriterion("actual_prepay_type is not null");
            return (Criteria) this;
        }

        public Criteria andActualPrepayTypeEqualTo(Integer value) {
            addCriterion("actual_prepay_type =", value, "actualPrepayType");
            return (Criteria) this;
        }

        public Criteria andActualPrepayTypeNotEqualTo(Integer value) {
            addCriterion("actual_prepay_type <>", value, "actualPrepayType");
            return (Criteria) this;
        }

        public Criteria andActualPrepayTypeGreaterThan(Integer value) {
            addCriterion("actual_prepay_type >", value, "actualPrepayType");
            return (Criteria) this;
        }

        public Criteria andActualPrepayTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("actual_prepay_type >=", value, "actualPrepayType");
            return (Criteria) this;
        }

        public Criteria andActualPrepayTypeLessThan(Integer value) {
            addCriterion("actual_prepay_type <", value, "actualPrepayType");
            return (Criteria) this;
        }

        public Criteria andActualPrepayTypeLessThanOrEqualTo(Integer value) {
            addCriterion("actual_prepay_type <=", value, "actualPrepayType");
            return (Criteria) this;
        }

        public Criteria andActualPrepayTypeIn(List<Integer> values) {
            addCriterion("actual_prepay_type in", values, "actualPrepayType");
            return (Criteria) this;
        }

        public Criteria andActualPrepayTypeNotIn(List<Integer> values) {
            addCriterion("actual_prepay_type not in", values, "actualPrepayType");
            return (Criteria) this;
        }

        public Criteria andActualPrepayTypeBetween(Integer value1, Integer value2) {
            addCriterion("actual_prepay_type between", value1, value2, "actualPrepayType");
            return (Criteria) this;
        }

        public Criteria andActualPrepayTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("actual_prepay_type not between", value1, value2, "actualPrepayType");
            return (Criteria) this;
        }

        public Criteria andActualPrepayIsNull() {
            addCriterion("actual_prepay is null");
            return (Criteria) this;
        }

        public Criteria andActualPrepayIsNotNull() {
            addCriterion("actual_prepay is not null");
            return (Criteria) this;
        }

        public Criteria andActualPrepayEqualTo(Double value) {
            addCriterion("actual_prepay =", value, "actualPrepay");
            return (Criteria) this;
        }

        public Criteria andActualPrepayNotEqualTo(Double value) {
            addCriterion("actual_prepay <>", value, "actualPrepay");
            return (Criteria) this;
        }

        public Criteria andActualPrepayGreaterThan(Double value) {
            addCriterion("actual_prepay >", value, "actualPrepay");
            return (Criteria) this;
        }

        public Criteria andActualPrepayGreaterThanOrEqualTo(Double value) {
            addCriterion("actual_prepay >=", value, "actualPrepay");
            return (Criteria) this;
        }

        public Criteria andActualPrepayLessThan(Double value) {
            addCriterion("actual_prepay <", value, "actualPrepay");
            return (Criteria) this;
        }

        public Criteria andActualPrepayLessThanOrEqualTo(Double value) {
            addCriterion("actual_prepay <=", value, "actualPrepay");
            return (Criteria) this;
        }

        public Criteria andActualPrepayIn(List<Double> values) {
            addCriterion("actual_prepay in", values, "actualPrepay");
            return (Criteria) this;
        }

        public Criteria andActualPrepayNotIn(List<Double> values) {
            addCriterion("actual_prepay not in", values, "actualPrepay");
            return (Criteria) this;
        }

        public Criteria andActualPrepayBetween(Double value1, Double value2) {
            addCriterion("actual_prepay between", value1, value2, "actualPrepay");
            return (Criteria) this;
        }

        public Criteria andActualPrepayNotBetween(Double value1, Double value2) {
            addCriterion("actual_prepay not between", value1, value2, "actualPrepay");
            return (Criteria) this;
        }

        public Criteria andCouponPrepayIsNull() {
            addCriterion("coupon_prepay is null");
            return (Criteria) this;
        }

        public Criteria andCouponPrepayIsNotNull() {
            addCriterion("coupon_prepay is not null");
            return (Criteria) this;
        }

        public Criteria andCouponPrepayEqualTo(Double value) {
            addCriterion("coupon_prepay =", value, "couponPrepay");
            return (Criteria) this;
        }

        public Criteria andCouponPrepayNotEqualTo(Double value) {
            addCriterion("coupon_prepay <>", value, "couponPrepay");
            return (Criteria) this;
        }

        public Criteria andCouponPrepayGreaterThan(Double value) {
            addCriterion("coupon_prepay >", value, "couponPrepay");
            return (Criteria) this;
        }

        public Criteria andCouponPrepayGreaterThanOrEqualTo(Double value) {
            addCriterion("coupon_prepay >=", value, "couponPrepay");
            return (Criteria) this;
        }

        public Criteria andCouponPrepayLessThan(Double value) {
            addCriterion("coupon_prepay <", value, "couponPrepay");
            return (Criteria) this;
        }

        public Criteria andCouponPrepayLessThanOrEqualTo(Double value) {
            addCriterion("coupon_prepay <=", value, "couponPrepay");
            return (Criteria) this;
        }

        public Criteria andCouponPrepayIn(List<Double> values) {
            addCriterion("coupon_prepay in", values, "couponPrepay");
            return (Criteria) this;
        }

        public Criteria andCouponPrepayNotIn(List<Double> values) {
            addCriterion("coupon_prepay not in", values, "couponPrepay");
            return (Criteria) this;
        }

        public Criteria andCouponPrepayBetween(Double value1, Double value2) {
            addCriterion("coupon_prepay between", value1, value2, "couponPrepay");
            return (Criteria) this;
        }

        public Criteria andCouponPrepayNotBetween(Double value1, Double value2) {
            addCriterion("coupon_prepay not between", value1, value2, "couponPrepay");
            return (Criteria) this;
        }

        public Criteria andOutTimeIsNull() {
            addCriterion("out_time is null");
            return (Criteria) this;
        }

        public Criteria andOutTimeIsNotNull() {
            addCriterion("out_time is not null");
            return (Criteria) this;
        }

        public Criteria andOutTimeEqualTo(String value) {
            addCriterion("out_time =", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeNotEqualTo(String value) {
            addCriterion("out_time <>", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeGreaterThan(String value) {
            addCriterion("out_time >", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeGreaterThanOrEqualTo(String value) {
            addCriterion("out_time >=", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeLessThan(String value) {
            addCriterion("out_time <", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeLessThanOrEqualTo(String value) {
            addCriterion("out_time <=", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeLike(String value) {
            addCriterion("out_time like", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeNotLike(String value) {
            addCriterion("out_time not like", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeIn(List<String> values) {
            addCriterion("out_time in", values, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeNotIn(List<String> values) {
            addCriterion("out_time not in", values, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeBetween(String value1, String value2) {
            addCriterion("out_time between", value1, value2, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeNotBetween(String value1, String value2) {
            addCriterion("out_time not between", value1, value2, "outTime");
            return (Criteria) this;
        }

        public Criteria andActualPaidIsNull() {
            addCriterion("actual_paid is null");
            return (Criteria) this;
        }

        public Criteria andActualPaidIsNotNull() {
            addCriterion("actual_paid is not null");
            return (Criteria) this;
        }

        public Criteria andActualPaidEqualTo(Double value) {
            addCriterion("actual_paid =", value, "actualPaid");
            return (Criteria) this;
        }

        public Criteria andActualPaidNotEqualTo(Double value) {
            addCriterion("actual_paid <>", value, "actualPaid");
            return (Criteria) this;
        }

        public Criteria andActualPaidGreaterThan(Double value) {
            addCriterion("actual_paid >", value, "actualPaid");
            return (Criteria) this;
        }

        public Criteria andActualPaidGreaterThanOrEqualTo(Double value) {
            addCriterion("actual_paid >=", value, "actualPaid");
            return (Criteria) this;
        }

        public Criteria andActualPaidLessThan(Double value) {
            addCriterion("actual_paid <", value, "actualPaid");
            return (Criteria) this;
        }

        public Criteria andActualPaidLessThanOrEqualTo(Double value) {
            addCriterion("actual_paid <=", value, "actualPaid");
            return (Criteria) this;
        }

        public Criteria andActualPaidIn(List<Double> values) {
            addCriterion("actual_paid in", values, "actualPaid");
            return (Criteria) this;
        }

        public Criteria andActualPaidNotIn(List<Double> values) {
            addCriterion("actual_paid not in", values, "actualPaid");
            return (Criteria) this;
        }

        public Criteria andActualPaidBetween(Double value1, Double value2) {
            addCriterion("actual_paid between", value1, value2, "actualPaid");
            return (Criteria) this;
        }

        public Criteria andActualPaidNotBetween(Double value1, Double value2) {
            addCriterion("actual_paid not between", value1, value2, "actualPaid");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_prepay
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_prepay
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}