package com.api.dao.sqlProvider;

import com.api.entity.AreaInformation;
import com.api.entity.AreaInformationCriteria;
import com.api.entity.AreaInformationCriteria.Criteria;
import com.api.entity.AreaInformationCriteria.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class AreaInformationSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_information
     *
     * @mbg.generated
     */
    public String countByExample(AreaInformationCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("area_information");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_information
     *
     * @mbg.generated
     */
    public String deleteByExample(AreaInformationCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("area_information");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_information
     *
     * @mbg.generated
     */
    public String insertSelective(AreaInformation record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("area_information");
        
        if (record.getAreaId() != null) {
            sql.VALUES("Area_ID", "#{areaId,jdbcType=INTEGER}");
        }
        
        if (record.getAreaName() != null) {
            sql.VALUES("Area_Name", "#{areaName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.VALUES("CreateTime", "#{createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCityId() != null) {
            sql.VALUES("City_ID", "#{cityId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_information
     *
     * @mbg.generated
     */
    public String selectByExample(AreaInformationCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("Area_ID");
        } else {
            sql.SELECT("Area_ID");
        }
        sql.SELECT("Area_Name");
        sql.SELECT("CreateTime");
        sql.SELECT("City_ID");
        sql.FROM("area_information");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_information
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        AreaInformation record = (AreaInformation) parameter.get("record");
        AreaInformationCriteria example = (AreaInformationCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("area_information");
        
        if (record.getAreaId() != null) {
            sql.SET("Area_ID = #{record.areaId,jdbcType=INTEGER}");
        }
        
        if (record.getAreaName() != null) {
            sql.SET("Area_Name = #{record.areaName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.SET("CreateTime = #{record.createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCityId() != null) {
            sql.SET("City_ID = #{record.cityId,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_information
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("area_information");
        
        sql.SET("Area_ID = #{record.areaId,jdbcType=INTEGER}");
        sql.SET("Area_Name = #{record.areaName,jdbcType=VARCHAR}");
        sql.SET("CreateTime = #{record.createtime,jdbcType=TIMESTAMP}");
        sql.SET("City_ID = #{record.cityId,jdbcType=INTEGER}");
        
        AreaInformationCriteria example = (AreaInformationCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_information
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(AreaInformation record) {
        SQL sql = new SQL();
        sql.UPDATE("area_information");
        
        if (record.getAreaName() != null) {
            sql.SET("Area_Name = #{areaName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.SET("CreateTime = #{createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCityId() != null) {
            sql.SET("City_ID = #{cityId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("Area_ID = #{areaId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_information
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, AreaInformationCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}