package com.api.dao.sqlProvider;

import com.api.entity.TMemberCar;
import com.api.entity.TMemberCarCriteria;
import com.api.entity.TMemberCarCriteria.Criteria;
import com.api.entity.TMemberCarCriteria.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class TMemberCarSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_car
     *
     * @mbg.generated
     */
    public String countByExample(TMemberCarCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_member_car");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_car
     *
     * @mbg.generated
     */
    public String deleteByExample(TMemberCarCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_member_car");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_car
     *
     * @mbg.generated
     */
    public String insertSelective(TMemberCar record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_member_car");
        
        if (record.getId() != null) {
            sql.VALUES("Id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getMemberId() != null) {
            sql.VALUES("member_id", "#{memberId,jdbcType=INTEGER}");
        }
        
        if (record.getCarColor() != null) {
            sql.VALUES("car_color", "#{carColor,jdbcType=VARCHAR}");
        }
        
        if (record.getCarPlateColor() != null) {
            sql.VALUES("car_plate_color", "#{carPlateColor,jdbcType=VARCHAR}");
        }
        
        if (record.getCarEngineNum() != null) {
            sql.VALUES("car_engine_num", "#{carEngineNum,jdbcType=VARCHAR}");
        }
        
        if (record.getCarIdentiNum() != null) {
            sql.VALUES("car_identi_num", "#{carIdentiNum,jdbcType=VARCHAR}");
        }
        
        if (record.getCarPlate() != null) {
            sql.VALUES("car_plate", "#{carPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getCarType() != null) {
            sql.VALUES("car_type", "#{carType,jdbcType=VARCHAR}");
        }
        
        if (record.getLockStatus() != null) {
            sql.VALUES("lock_status", "#{lockStatus,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=VARCHAR}");
        }
        
        if (record.getInParkId() != null) {
            sql.VALUES("in_park_id", "#{inParkId,jdbcType=INTEGER}");
        }
        
        if (record.getInTime() != null) {
            sql.VALUES("in_time", "#{inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutParkId() != null) {
            sql.VALUES("out_park_id", "#{outParkId,jdbcType=INTEGER}");
        }
        
        if (record.getOutTime() != null) {
            sql.VALUES("out_time", "#{outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDelete() != null) {
            sql.VALUES("is_delete", "#{isDelete,jdbcType=SMALLINT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_car
     *
     * @mbg.generated
     */
    public String selectByExample(TMemberCarCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("Id");
        } else {
            sql.SELECT("Id");
        }
        sql.SELECT("member_id");
        sql.SELECT("car_color");
        sql.SELECT("car_plate_color");
        sql.SELECT("car_engine_num");
        sql.SELECT("car_identi_num");
        sql.SELECT("car_plate");
        sql.SELECT("car_type");
        sql.SELECT("lock_status");
        sql.SELECT("create_time");
        sql.SELECT("in_park_id");
        sql.SELECT("in_time");
        sql.SELECT("out_park_id");
        sql.SELECT("out_time");
        sql.SELECT("remark");
        sql.SELECT("is_delete");
        sql.FROM("t_member_car");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_car
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TMemberCar record = (TMemberCar) parameter.get("record");
        TMemberCarCriteria example = (TMemberCarCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_member_car");
        
        if (record.getId() != null) {
            sql.SET("Id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getMemberId() != null) {
            sql.SET("member_id = #{record.memberId,jdbcType=INTEGER}");
        }
        
        if (record.getCarColor() != null) {
            sql.SET("car_color = #{record.carColor,jdbcType=VARCHAR}");
        }
        
        if (record.getCarPlateColor() != null) {
            sql.SET("car_plate_color = #{record.carPlateColor,jdbcType=VARCHAR}");
        }
        
        if (record.getCarEngineNum() != null) {
            sql.SET("car_engine_num = #{record.carEngineNum,jdbcType=VARCHAR}");
        }
        
        if (record.getCarIdentiNum() != null) {
            sql.SET("car_identi_num = #{record.carIdentiNum,jdbcType=VARCHAR}");
        }
        
        if (record.getCarPlate() != null) {
            sql.SET("car_plate = #{record.carPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getCarType() != null) {
            sql.SET("car_type = #{record.carType,jdbcType=VARCHAR}");
        }
        
        if (record.getLockStatus() != null) {
            sql.SET("lock_status = #{record.lockStatus,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=VARCHAR}");
        }
        
        if (record.getInParkId() != null) {
            sql.SET("in_park_id = #{record.inParkId,jdbcType=INTEGER}");
        }
        
        if (record.getInTime() != null) {
            sql.SET("in_time = #{record.inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutParkId() != null) {
            sql.SET("out_park_id = #{record.outParkId,jdbcType=INTEGER}");
        }
        
        if (record.getOutTime() != null) {
            sql.SET("out_time = #{record.outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDelete() != null) {
            sql.SET("is_delete = #{record.isDelete,jdbcType=SMALLINT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_car
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_member_car");
        
        sql.SET("Id = #{record.id,jdbcType=INTEGER}");
        sql.SET("member_id = #{record.memberId,jdbcType=INTEGER}");
        sql.SET("car_color = #{record.carColor,jdbcType=VARCHAR}");
        sql.SET("car_plate_color = #{record.carPlateColor,jdbcType=VARCHAR}");
        sql.SET("car_engine_num = #{record.carEngineNum,jdbcType=VARCHAR}");
        sql.SET("car_identi_num = #{record.carIdentiNum,jdbcType=VARCHAR}");
        sql.SET("car_plate = #{record.carPlate,jdbcType=VARCHAR}");
        sql.SET("car_type = #{record.carType,jdbcType=VARCHAR}");
        sql.SET("lock_status = #{record.lockStatus,jdbcType=INTEGER}");
        sql.SET("create_time = #{record.createTime,jdbcType=VARCHAR}");
        sql.SET("in_park_id = #{record.inParkId,jdbcType=INTEGER}");
        sql.SET("in_time = #{record.inTime,jdbcType=VARCHAR}");
        sql.SET("out_park_id = #{record.outParkId,jdbcType=INTEGER}");
        sql.SET("out_time = #{record.outTime,jdbcType=VARCHAR}");
        sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        sql.SET("is_delete = #{record.isDelete,jdbcType=SMALLINT}");
        
        TMemberCarCriteria example = (TMemberCarCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_car
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TMemberCar record) {
        SQL sql = new SQL();
        sql.UPDATE("t_member_car");
        
        if (record.getMemberId() != null) {
            sql.SET("member_id = #{memberId,jdbcType=INTEGER}");
        }
        
        if (record.getCarColor() != null) {
            sql.SET("car_color = #{carColor,jdbcType=VARCHAR}");
        }
        
        if (record.getCarPlateColor() != null) {
            sql.SET("car_plate_color = #{carPlateColor,jdbcType=VARCHAR}");
        }
        
        if (record.getCarEngineNum() != null) {
            sql.SET("car_engine_num = #{carEngineNum,jdbcType=VARCHAR}");
        }
        
        if (record.getCarIdentiNum() != null) {
            sql.SET("car_identi_num = #{carIdentiNum,jdbcType=VARCHAR}");
        }
        
        if (record.getCarPlate() != null) {
            sql.SET("car_plate = #{carPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getCarType() != null) {
            sql.SET("car_type = #{carType,jdbcType=VARCHAR}");
        }
        
        if (record.getLockStatus() != null) {
            sql.SET("lock_status = #{lockStatus,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=VARCHAR}");
        }
        
        if (record.getInParkId() != null) {
            sql.SET("in_park_id = #{inParkId,jdbcType=INTEGER}");
        }
        
        if (record.getInTime() != null) {
            sql.SET("in_time = #{inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutParkId() != null) {
            sql.SET("out_park_id = #{outParkId,jdbcType=INTEGER}");
        }
        
        if (record.getOutTime() != null) {
            sql.SET("out_time = #{outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDelete() != null) {
            sql.SET("is_delete = #{isDelete,jdbcType=SMALLINT}");
        }
        
        sql.WHERE("Id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_car
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TMemberCarCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}