package com.api.dao.sqlProvider;

import com.api.entity.TMemberTransaction;
import com.api.entity.TMemberTransactionCriteria;
import com.api.entity.TMemberTransactionCriteria.Criteria;
import com.api.entity.TMemberTransactionCriteria.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class TMemberTransactionSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_transaction
     *
     * @mbg.generated
     */
    public String countByExample(TMemberTransactionCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_member_transaction");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_transaction
     *
     * @mbg.generated
     */
    public String deleteByExample(TMemberTransactionCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_member_transaction");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_transaction
     *
     * @mbg.generated
     */
    public String insertSelective(TMemberTransaction record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_member_transaction");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getDate() != null) {
            sql.VALUES("date", "#{date,jdbcType=VARCHAR}");
        }
        
        if (record.getMemberId() != null) {
            sql.VALUES("member_id", "#{memberId,jdbcType=INTEGER}");
        }
        
        if (record.getMoney() != null) {
            sql.VALUES("money", "#{money,jdbcType=DOUBLE}");
        }
        
        if (record.getOrderNumber() != null) {
            sql.VALUES("order_number", "#{orderNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getPayBy() != null) {
            sql.VALUES("pay_by", "#{payBy,jdbcType=VARCHAR}");
        }
        
        if (record.getTransactios() != null) {
            sql.VALUES("transactios", "#{transactios,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.VALUES("park_id", "#{parkId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_transaction
     *
     * @mbg.generated
     */
    public String selectByExample(TMemberTransactionCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("date");
        sql.SELECT("member_id");
        sql.SELECT("money");
        sql.SELECT("order_number");
        sql.SELECT("pay_by");
        sql.SELECT("transactios");
        sql.SELECT("status");
        sql.SELECT("park_id");
        sql.FROM("t_member_transaction");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_transaction
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TMemberTransaction record = (TMemberTransaction) parameter.get("record");
        TMemberTransactionCriteria example = (TMemberTransactionCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_member_transaction");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getDate() != null) {
            sql.SET("date = #{record.date,jdbcType=VARCHAR}");
        }
        
        if (record.getMemberId() != null) {
            sql.SET("member_id = #{record.memberId,jdbcType=INTEGER}");
        }
        
        if (record.getMoney() != null) {
            sql.SET("money = #{record.money,jdbcType=DOUBLE}");
        }
        
        if (record.getOrderNumber() != null) {
            sql.SET("order_number = #{record.orderNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getPayBy() != null) {
            sql.SET("pay_by = #{record.payBy,jdbcType=VARCHAR}");
        }
        
        if (record.getTransactios() != null) {
            sql.SET("transactios = #{record.transactios,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{record.status,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_transaction
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_member_transaction");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("date = #{record.date,jdbcType=VARCHAR}");
        sql.SET("member_id = #{record.memberId,jdbcType=INTEGER}");
        sql.SET("money = #{record.money,jdbcType=DOUBLE}");
        sql.SET("order_number = #{record.orderNumber,jdbcType=VARCHAR}");
        sql.SET("pay_by = #{record.payBy,jdbcType=VARCHAR}");
        sql.SET("transactios = #{record.transactios,jdbcType=VARCHAR}");
        sql.SET("status = #{record.status,jdbcType=INTEGER}");
        sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        
        TMemberTransactionCriteria example = (TMemberTransactionCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_transaction
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TMemberTransaction record) {
        SQL sql = new SQL();
        sql.UPDATE("t_member_transaction");
        
        if (record.getDate() != null) {
            sql.SET("date = #{date,jdbcType=VARCHAR}");
        }
        
        if (record.getMemberId() != null) {
            sql.SET("member_id = #{memberId,jdbcType=INTEGER}");
        }
        
        if (record.getMoney() != null) {
            sql.SET("money = #{money,jdbcType=DOUBLE}");
        }
        
        if (record.getOrderNumber() != null) {
            sql.SET("order_number = #{orderNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getPayBy() != null) {
            sql.SET("pay_by = #{payBy,jdbcType=VARCHAR}");
        }
        
        if (record.getTransactios() != null) {
            sql.SET("transactios = #{transactios,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{parkId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_transaction
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TMemberTransactionCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}