package com.api.dao.sqlProvider;

import com.api.entity.TParkDuty;
import com.api.entity.TParkDutyCriteria;
import com.api.entity.TParkDutyCriteria.Criteria;
import com.api.entity.TParkDutyCriteria.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class TParkDutySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_duty
     *
     * @mbg.generated
     */
    public String countByExample(TParkDutyCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_park_duty");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_duty
     *
     * @mbg.generated
     */
    public String deleteByExample(TParkDutyCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_park_duty");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_duty
     *
     * @mbg.generated
     */
    public String insertSelective(TParkDuty record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_park_duty");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getActualTotal() != null) {
            sql.VALUES("actual_total", "#{actualTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getBeginTime() != null) {
            sql.VALUES("begin_time", "#{beginTime,jdbcType=VARCHAR}");
        }
        
        if (record.getDutyPerson() != null) {
            sql.VALUES("duty_person", "#{dutyPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getEndTime() != null) {
            sql.VALUES("end_time", "#{endTime,jdbcType=VARCHAR}");
        }
        
        if (record.getFreePass() != null) {
            sql.VALUES("free_pass", "#{freePass,jdbcType=INTEGER}");
        }
        
        if (record.getLastChargeTime() != null) {
            sql.VALUES("last_charge_time", "#{lastChargeTime,jdbcType=VARCHAR}");
        }
        
        if (record.getManualPass() != null) {
            sql.VALUES("manual_pass", "#{manualPass,jdbcType=INTEGER}");
        }
        
        if (record.getMatchPass() != null) {
            sql.VALUES("match_pass", "#{matchPass,jdbcType=INTEGER}");
        }
        
        if (record.getNeedTotal() != null) {
            sql.VALUES("need_total", "#{needTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getPayOnlineTotal() != null) {
            sql.VALUES("pay_online_total", "#{payOnlineTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getSysPass() != null) {
            sql.VALUES("sys_pass", "#{sysPass,jdbcType=INTEGER}");
        }
        
        if (record.getCompanyId() != null) {
            sql.VALUES("company_id", "#{companyId,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.VALUES("park_id", "#{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getPrepayTotal() != null) {
            sql.VALUES("prepay_total", "#{prepayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getQpasspayTotal() != null) {
            sql.VALUES("qpasspay_total", "#{qpasspayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getBehalfpayTotal() != null) {
            sql.VALUES("behalfpay_total", "#{behalfpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getNoconfirmPass() != null) {
            sql.VALUES("noconfirm_pass", "#{noconfirmPass,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getLocalcouponTotal() != null) {
            sql.VALUES("localcoupon_total", "#{localcouponTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getUpdatecarplatesTotal() != null) {
            sql.VALUES("updatecarplates_total", "#{updatecarplatesTotal,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_duty
     *
     * @mbg.generated
     */
    public String selectByExample(TParkDutyCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("actual_total");
        sql.SELECT("begin_time");
        sql.SELECT("duty_person");
        sql.SELECT("end_time");
        sql.SELECT("free_pass");
        sql.SELECT("last_charge_time");
        sql.SELECT("manual_pass");
        sql.SELECT("match_pass");
        sql.SELECT("need_total");
        sql.SELECT("pay_online_total");
        sql.SELECT("sys_pass");
        sql.SELECT("company_id");
        sql.SELECT("park_id");
        sql.SELECT("prepay_total");
        sql.SELECT("qpasspay_total");
        sql.SELECT("behalfpay_total");
        sql.SELECT("noconfirm_pass");
        sql.SELECT("user_id");
        sql.SELECT("localcoupon_total");
        sql.SELECT("updatecarplates_total");
        sql.FROM("t_park_duty");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_duty
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TParkDuty record = (TParkDuty) parameter.get("record");
        TParkDutyCriteria example = (TParkDutyCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_park_duty");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getActualTotal() != null) {
            sql.SET("actual_total = #{record.actualTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getBeginTime() != null) {
            sql.SET("begin_time = #{record.beginTime,jdbcType=VARCHAR}");
        }
        
        if (record.getDutyPerson() != null) {
            sql.SET("duty_person = #{record.dutyPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getEndTime() != null) {
            sql.SET("end_time = #{record.endTime,jdbcType=VARCHAR}");
        }
        
        if (record.getFreePass() != null) {
            sql.SET("free_pass = #{record.freePass,jdbcType=INTEGER}");
        }
        
        if (record.getLastChargeTime() != null) {
            sql.SET("last_charge_time = #{record.lastChargeTime,jdbcType=VARCHAR}");
        }
        
        if (record.getManualPass() != null) {
            sql.SET("manual_pass = #{record.manualPass,jdbcType=INTEGER}");
        }
        
        if (record.getMatchPass() != null) {
            sql.SET("match_pass = #{record.matchPass,jdbcType=INTEGER}");
        }
        
        if (record.getNeedTotal() != null) {
            sql.SET("need_total = #{record.needTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getPayOnlineTotal() != null) {
            sql.SET("pay_online_total = #{record.payOnlineTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getSysPass() != null) {
            sql.SET("sys_pass = #{record.sysPass,jdbcType=INTEGER}");
        }
        
        if (record.getCompanyId() != null) {
            sql.SET("company_id = #{record.companyId,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        }
        
        if (record.getPrepayTotal() != null) {
            sql.SET("prepay_total = #{record.prepayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getQpasspayTotal() != null) {
            sql.SET("qpasspay_total = #{record.qpasspayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getBehalfpayTotal() != null) {
            sql.SET("behalfpay_total = #{record.behalfpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getNoconfirmPass() != null) {
            sql.SET("noconfirm_pass = #{record.noconfirmPass,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getLocalcouponTotal() != null) {
            sql.SET("localcoupon_total = #{record.localcouponTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getUpdatecarplatesTotal() != null) {
            sql.SET("updatecarplates_total = #{record.updatecarplatesTotal,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_duty
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_park_duty");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("actual_total = #{record.actualTotal,jdbcType=DOUBLE}");
        sql.SET("begin_time = #{record.beginTime,jdbcType=VARCHAR}");
        sql.SET("duty_person = #{record.dutyPerson,jdbcType=VARCHAR}");
        sql.SET("end_time = #{record.endTime,jdbcType=VARCHAR}");
        sql.SET("free_pass = #{record.freePass,jdbcType=INTEGER}");
        sql.SET("last_charge_time = #{record.lastChargeTime,jdbcType=VARCHAR}");
        sql.SET("manual_pass = #{record.manualPass,jdbcType=INTEGER}");
        sql.SET("match_pass = #{record.matchPass,jdbcType=INTEGER}");
        sql.SET("need_total = #{record.needTotal,jdbcType=DOUBLE}");
        sql.SET("pay_online_total = #{record.payOnlineTotal,jdbcType=DOUBLE}");
        sql.SET("sys_pass = #{record.sysPass,jdbcType=INTEGER}");
        sql.SET("company_id = #{record.companyId,jdbcType=INTEGER}");
        sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        sql.SET("prepay_total = #{record.prepayTotal,jdbcType=DOUBLE}");
        sql.SET("qpasspay_total = #{record.qpasspayTotal,jdbcType=DOUBLE}");
        sql.SET("behalfpay_total = #{record.behalfpayTotal,jdbcType=DOUBLE}");
        sql.SET("noconfirm_pass = #{record.noconfirmPass,jdbcType=INTEGER}");
        sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        sql.SET("localcoupon_total = #{record.localcouponTotal,jdbcType=DOUBLE}");
        sql.SET("updatecarplates_total = #{record.updatecarplatesTotal,jdbcType=INTEGER}");
        
        TParkDutyCriteria example = (TParkDutyCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_duty
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TParkDuty record) {
        SQL sql = new SQL();
        sql.UPDATE("t_park_duty");
        
        if (record.getActualTotal() != null) {
            sql.SET("actual_total = #{actualTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getBeginTime() != null) {
            sql.SET("begin_time = #{beginTime,jdbcType=VARCHAR}");
        }
        
        if (record.getDutyPerson() != null) {
            sql.SET("duty_person = #{dutyPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getEndTime() != null) {
            sql.SET("end_time = #{endTime,jdbcType=VARCHAR}");
        }
        
        if (record.getFreePass() != null) {
            sql.SET("free_pass = #{freePass,jdbcType=INTEGER}");
        }
        
        if (record.getLastChargeTime() != null) {
            sql.SET("last_charge_time = #{lastChargeTime,jdbcType=VARCHAR}");
        }
        
        if (record.getManualPass() != null) {
            sql.SET("manual_pass = #{manualPass,jdbcType=INTEGER}");
        }
        
        if (record.getMatchPass() != null) {
            sql.SET("match_pass = #{matchPass,jdbcType=INTEGER}");
        }
        
        if (record.getNeedTotal() != null) {
            sql.SET("need_total = #{needTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getPayOnlineTotal() != null) {
            sql.SET("pay_online_total = #{payOnlineTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getSysPass() != null) {
            sql.SET("sys_pass = #{sysPass,jdbcType=INTEGER}");
        }
        
        if (record.getCompanyId() != null) {
            sql.SET("company_id = #{companyId,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getPrepayTotal() != null) {
            sql.SET("prepay_total = #{prepayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getQpasspayTotal() != null) {
            sql.SET("qpasspay_total = #{qpasspayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getBehalfpayTotal() != null) {
            sql.SET("behalfpay_total = #{behalfpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getNoconfirmPass() != null) {
            sql.SET("noconfirm_pass = #{noconfirmPass,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getLocalcouponTotal() != null) {
            sql.SET("localcoupon_total = #{localcouponTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getUpdatecarplatesTotal() != null) {
            sql.SET("updatecarplates_total = #{updatecarplatesTotal,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_duty
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TParkDutyCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}