package com.api.dao.sqlProvider;

import com.api.entity.TTicketCoupon;
import com.api.entity.TTicketCouponCriteria;
import com.api.entity.TTicketCouponCriteria.Criteria;
import com.api.entity.TTicketCouponCriteria.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class TTicketCouponSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket_coupon
     *
     * @mbg.generated
     */
    public String countByExample(TTicketCouponCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_ticket_coupon");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket_coupon
     *
     * @mbg.generated
     */
    public String deleteByExample(TTicketCouponCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_ticket_coupon");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket_coupon
     *
     * @mbg.generated
     */
    public String insertSelective(TTicketCoupon record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_ticket_coupon");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getCarplate() != null) {
            sql.VALUES("carplate", "#{carplate,jdbcType=VARCHAR}");
        }
        
        if (record.getInTime() != null) {
            sql.VALUES("in_time", "#{inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTime() != null) {
            sql.VALUES("out_time", "#{outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getCouponCode() != null) {
            sql.VALUES("coupon_code", "#{couponCode,jdbcType=VARCHAR}");
        }
        
        if (record.getCouponType() != null) {
            sql.VALUES("coupon_type", "#{couponType,jdbcType=INTEGER}");
        }
        
        if (record.getCouponPay() != null) {
            sql.VALUES("coupon_pay", "#{couponPay,jdbcType=DOUBLE}");
        }
        
        if (record.getCouponActualPay() != null) {
            sql.VALUES("coupon_actual_pay", "#{couponActualPay,jdbcType=DOUBLE}");
        }
        
        if (record.getBusineId() != null) {
            sql.VALUES("busine_id", "#{busineId,jdbcType=INTEGER}");
        }
        
        if (record.getBusineName() != null) {
            sql.VALUES("busine_name", "#{busineName,jdbcType=VARCHAR}");
        }
        
        if (record.getParkId() != null) {
            sql.VALUES("park_id", "#{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getParkName() != null) {
            sql.VALUES("park_name", "#{parkName,jdbcType=VARCHAR}");
        }
        
        if (record.getTicketId() != null) {
            sql.VALUES("ticket_id", "#{ticketId,jdbcType=INTEGER}");
        }
        
        if (record.getTicketName() != null) {
            sql.VALUES("ticket_name", "#{ticketName,jdbcType=VARCHAR}");
        }
        
        if (record.getIsUse() != null) {
            sql.VALUES("is_use", "#{isUse,jdbcType=INTEGER}");
        }
        
        if (record.getPermissionDate() != null) {
            sql.VALUES("permission_date", "#{permissionDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getCompanyId() != null) {
            sql.VALUES("company_id", "#{companyId,jdbcType=INTEGER}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=VARCHAR}");
        }
        
        if (record.getBatchCode() != null) {
            sql.VALUES("batch_code", "#{batchCode,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket_coupon
     *
     * @mbg.generated
     */
    public String selectByExample(TTicketCouponCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("carplate");
        sql.SELECT("in_time");
        sql.SELECT("out_time");
        sql.SELECT("coupon_code");
        sql.SELECT("coupon_type");
        sql.SELECT("coupon_pay");
        sql.SELECT("coupon_actual_pay");
        sql.SELECT("busine_id");
        sql.SELECT("busine_name");
        sql.SELECT("park_id");
        sql.SELECT("park_name");
        sql.SELECT("ticket_id");
        sql.SELECT("ticket_name");
        sql.SELECT("is_use");
        sql.SELECT("permission_date");
        sql.SELECT("remark");
        sql.SELECT("company_id");
        sql.SELECT("update_time");
        sql.SELECT("batch_code");
        sql.SELECT("create_time");
        sql.FROM("t_ticket_coupon");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket_coupon
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TTicketCoupon record = (TTicketCoupon) parameter.get("record");
        TTicketCouponCriteria example = (TTicketCouponCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_ticket_coupon");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getCarplate() != null) {
            sql.SET("carplate = #{record.carplate,jdbcType=VARCHAR}");
        }
        
        if (record.getInTime() != null) {
            sql.SET("in_time = #{record.inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTime() != null) {
            sql.SET("out_time = #{record.outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getCouponCode() != null) {
            sql.SET("coupon_code = #{record.couponCode,jdbcType=VARCHAR}");
        }
        
        if (record.getCouponType() != null) {
            sql.SET("coupon_type = #{record.couponType,jdbcType=INTEGER}");
        }
        
        if (record.getCouponPay() != null) {
            sql.SET("coupon_pay = #{record.couponPay,jdbcType=DOUBLE}");
        }
        
        if (record.getCouponActualPay() != null) {
            sql.SET("coupon_actual_pay = #{record.couponActualPay,jdbcType=DOUBLE}");
        }
        
        if (record.getBusineId() != null) {
            sql.SET("busine_id = #{record.busineId,jdbcType=INTEGER}");
        }
        
        if (record.getBusineName() != null) {
            sql.SET("busine_name = #{record.busineName,jdbcType=VARCHAR}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        }
        
        if (record.getParkName() != null) {
            sql.SET("park_name = #{record.parkName,jdbcType=VARCHAR}");
        }
        
        if (record.getTicketId() != null) {
            sql.SET("ticket_id = #{record.ticketId,jdbcType=INTEGER}");
        }
        
        if (record.getTicketName() != null) {
            sql.SET("ticket_name = #{record.ticketName,jdbcType=VARCHAR}");
        }
        
        if (record.getIsUse() != null) {
            sql.SET("is_use = #{record.isUse,jdbcType=INTEGER}");
        }
        
        if (record.getPermissionDate() != null) {
            sql.SET("permission_date = #{record.permissionDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        }
        
        if (record.getCompanyId() != null) {
            sql.SET("company_id = #{record.companyId,jdbcType=INTEGER}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=VARCHAR}");
        }
        
        if (record.getBatchCode() != null) {
            sql.SET("batch_code = #{record.batchCode,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket_coupon
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_ticket_coupon");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("carplate = #{record.carplate,jdbcType=VARCHAR}");
        sql.SET("in_time = #{record.inTime,jdbcType=VARCHAR}");
        sql.SET("out_time = #{record.outTime,jdbcType=VARCHAR}");
        sql.SET("coupon_code = #{record.couponCode,jdbcType=VARCHAR}");
        sql.SET("coupon_type = #{record.couponType,jdbcType=INTEGER}");
        sql.SET("coupon_pay = #{record.couponPay,jdbcType=DOUBLE}");
        sql.SET("coupon_actual_pay = #{record.couponActualPay,jdbcType=DOUBLE}");
        sql.SET("busine_id = #{record.busineId,jdbcType=INTEGER}");
        sql.SET("busine_name = #{record.busineName,jdbcType=VARCHAR}");
        sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        sql.SET("park_name = #{record.parkName,jdbcType=VARCHAR}");
        sql.SET("ticket_id = #{record.ticketId,jdbcType=INTEGER}");
        sql.SET("ticket_name = #{record.ticketName,jdbcType=VARCHAR}");
        sql.SET("is_use = #{record.isUse,jdbcType=INTEGER}");
        sql.SET("permission_date = #{record.permissionDate,jdbcType=VARCHAR}");
        sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        sql.SET("company_id = #{record.companyId,jdbcType=INTEGER}");
        sql.SET("update_time = #{record.updateTime,jdbcType=VARCHAR}");
        sql.SET("batch_code = #{record.batchCode,jdbcType=INTEGER}");
        sql.SET("create_time = #{record.createTime,jdbcType=VARCHAR}");
        
        TTicketCouponCriteria example = (TTicketCouponCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket_coupon
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TTicketCoupon record) {
        SQL sql = new SQL();
        sql.UPDATE("t_ticket_coupon");
        
        if (record.getCarplate() != null) {
            sql.SET("carplate = #{carplate,jdbcType=VARCHAR}");
        }
        
        if (record.getInTime() != null) {
            sql.SET("in_time = #{inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTime() != null) {
            sql.SET("out_time = #{outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getCouponCode() != null) {
            sql.SET("coupon_code = #{couponCode,jdbcType=VARCHAR}");
        }
        
        if (record.getCouponType() != null) {
            sql.SET("coupon_type = #{couponType,jdbcType=INTEGER}");
        }
        
        if (record.getCouponPay() != null) {
            sql.SET("coupon_pay = #{couponPay,jdbcType=DOUBLE}");
        }
        
        if (record.getCouponActualPay() != null) {
            sql.SET("coupon_actual_pay = #{couponActualPay,jdbcType=DOUBLE}");
        }
        
        if (record.getBusineId() != null) {
            sql.SET("busine_id = #{busineId,jdbcType=INTEGER}");
        }
        
        if (record.getBusineName() != null) {
            sql.SET("busine_name = #{busineName,jdbcType=VARCHAR}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getParkName() != null) {
            sql.SET("park_name = #{parkName,jdbcType=VARCHAR}");
        }
        
        if (record.getTicketId() != null) {
            sql.SET("ticket_id = #{ticketId,jdbcType=INTEGER}");
        }
        
        if (record.getTicketName() != null) {
            sql.SET("ticket_name = #{ticketName,jdbcType=VARCHAR}");
        }
        
        if (record.getIsUse() != null) {
            sql.SET("is_use = #{isUse,jdbcType=INTEGER}");
        }
        
        if (record.getPermissionDate() != null) {
            sql.SET("permission_date = #{permissionDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getCompanyId() != null) {
            sql.SET("company_id = #{companyId,jdbcType=INTEGER}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=VARCHAR}");
        }
        
        if (record.getBatchCode() != null) {
            sql.SET("batch_code = #{batchCode,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ticket_coupon
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TTicketCouponCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}